### ISSUE TITLE
responsive and mobile

### ISSUE THREAD

**Issue by sc0rp1d** [alvarotrigo/fullPage.js#1025]
Responsive is set to 1024, on mobile (iPhone 5S) horizontal orientation changed to vertical and plugin scrolling page to current section. It is normal? I think don't need to scroll when orientation change and responsive is active.

**Comment by alvarotrigo** [comment]
@sc0rp1d yeah, you may be right. 
When the `responsive` mode is fired the plugin acts like when using the option `autoScrolling:false`, like [in this example](http://alvarotrigo.com/fullPage/examples/normalScroll.html) and probably it doesn't make sense to auto-scroll if the user can scroll freely. 

I will keep it open and think about it for a future.

**Comment by alvarotrigo** [comment]
Should be solved now in version 2.5.8.
Take a look as well as the new introduced option `fitToSection`.

**Comment by ysanmiguel** [comment]
<b>autoScrolling: false,</b>
is incompatible with the class <b>fp-auto-height</b> 
If there is one fp-auto-height section, (on laptop computer) once click on one of the "menu" buttons, the "fitToSection" turns true.
In mobiles is even worse because autoScrolling is completely deactivating the the vertical touch scroll.
(tested on android).

**Comment by alvarotrigo** [comment]
@ysanmiguel make sure you use the lastest fullpage.js version 2.7.5. It sounds like you are using an old version.

**Comment by ysanmiguel** [comment]
You are right my friend, I'm using  fullPage 2.7.3.
I will try and give you the feedback.
Thank you very much!

**Comment by ysanmiguel** [comment]
Good evening Alvaro.

I'm using the new version but the problem continues.
There are 2 problems:

1.  Setting the "autoScrolling" false, using a "fp-auto-height" section in the page, in mobiles the vertical vertical scroll doesn't work, only works if "autoScrolling" is true, but works like ""autoScrolling" works, it means scrolling section by section.
2. The fullpage becomes a little bit crazy if the "fp-auto-height" is used between 2 normal sections, for example: I have a content higher or smaller than the screen size, I don't want to use the scroll option so I set false the fitToSection and autoScrolling, but the menu buttons don't recognize the top of the section if you click on a button to go to the section (#section-one) with "fp-auto-height" it will takes you to the middle of the section or you will see a little bit of the others sections on the top. I think it should work like a normal anchor.

hope you can understand what I mean.
thank you very much and congratulations for that amazing work. :)

**Comment by alvarotrigo** [comment]
Check these issues and make sure yours is none of them:
https://github.com/alvarotrigo/fullPage.js/issues/1632
https://github.com/alvarotrigo/fullPage.js/issues/1641
https://github.com/alvarotrigo/fullPage.js/issues/1489

If so, open a new issue and provide an isolated reproduction of the problem in jsfiddle or codepen.

**Comment by ysanmiguel** [comment]
Look at this mate: http://jsfiddle.net/kdy56gjm/2/

1. look the second slide, is a "fp-auto-height" just be sure that the preview square is smaller than the second slide. I understand that the class "fp-auto-height" behavior, because the scroll takes you to the button of the section (like in the footer) but that behavior doesn't in this case that the content is bigger than the screen and overflow is disable.

I think a good idea is create an "fp-auto-height-top" to scroll to the top of the auto-height section, or set parameters that recognise the height of the section, if is higher than the view port, scroll to the top or simply, always scroll to the top because if is on the footer the scroll can't go further than the en of the page.

2. with this configuration in chrome/android the vertical scroll doesn't work.

Thank you Alvaro.

**Comment by alvarotrigo** [comment]
Please open a new issue for it as I suggested.
