### ISSUE TITLE
Using Slimscroll plugin with conflict

### ISSUE THREAD

**Issue by dandad** [alvarotrigo/fullPage.js#1040]
Hi. I want use the Slimscroll plugin in another place(nested element), but this is with conflict and not working correctly in scrolling and touching. please help me.

**Comment by alvarotrigo** [comment]
Use `scrollOverflow` instead. Otherwise, use `normalScrollElements` for the elements in which yoiu apply slimscroll. But that won't make fullPage.js scroll when it reach the bottom of your scroll. You probably would need to use some slimScroll callback to detect the end or the start of the scrolling area and then call fullPage.js functions such as `moveSecionDown` or `moveSectionUp`.

**Comment by dandad** [comment]
normalScrollElements property is the best choice for me but current section isn't changed when cursor is on those elements.

**Comment by alvarotrigo** [comment]
> current section isn't changed when cursor is on those elements.

normalScrollElements is precisely for that. To prevent fullpage.js to scroll to other sections when scrolling over that element.

**Comment by dandad** [comment]
allowPageScroll - Checks if mouse wheel should scroll page when bar reaches top or bottom of the container. When set to true is scrolls the page.Default: false
but
allowPageScroll propery in slimScroll don't work.

**Comment by alvarotrigo** [comment]
I don't know about allowPageScroll. I can only answer you things about fullPage.js.

**Comment by dandad** [comment]
Thanks a lot.
