### ISSUE TITLE
AutoScroll: true and Normal Scrolling abilities

### ISSUE THREAD

**Issue by vincenthalim** [alvarotrigo/fullPage.js#1112]
Hi,

Thank you for your the great plugin. However i ran into some issues with the plugin. Below i have detailed all the necessary steps for your reproduce.

Problems:
1. In reference to the scrolling.html file that you have as the example. Which can be found from the examples you provided.

2. I tried loading this to an iPad to test things out, as that is where the it mostly be used, however, the transition is very jittery, which caused the user experience to drop. And it does not retain the AutoScroll snappy transition in between each sections. 

Solutions i have tried:

I have tried several solutions to solve this issue, however, none of them worked, as it produces a different problem, below is a list of things i have tried.

1. I have tried using normalScrollElements to make an exception for the elements and class to retain its normal scrolling functions, however it does not work at all, and the autoScroll is still true regardless.

2. I have tried using the callback functions afterLoad(), to change the autoScroll property from true to false in the section that requires scrolling and combining with onLeave() function, to return the autoScroll property to true to return back to the previous section with the snappy transition. However, this does not work, as the image in the first section will not align properly when the autoScroll is set to false, and returning it to true will cause the transition to have a major lag, which cause everything to not perform smoothly.

3. I tried using fitToSection function as well, however, this will cause the content to be centred and do not display all of the content.

An overview of the ideal solution will be like the following: 
Section 1 = autoScroll is true
Section 2 = Have normal scrolling capabilities, as the content will not fit in an iPad screen and when scrolling back to Section 1 will have the snappy transition that the autoScroll provides.

Please advise. I have attached screenshots of Section 1 and 2 of what it looks like.
![section 2](https://cloud.githubusercontent.com/assets/11673083/6860381/838498c4-d47b-11e4-9154-5d58663133e9.png)
![section 1](https://cloud.githubusercontent.com/assets/11673083/6860382/83b99812-d47b-11e4-9a68-3052912b0f4e.png)

**Comment by alvarotrigo** [comment]
The issue with `scrollOverflow:true` in touch devices [has been already treated](https://github.com/alvarotrigo/fullPage.js/issues/506) and still not solved.

If that's not working well for you, I'm afraid there's no proper solution for it. I would recommend you to use the `responsive` option to set he page to `autoScrolling:false` once reached certain `width`, or, otherwise, use CSS3 media queries or responsive techniques such as [FlowType](https://github.com/simplefocus/FlowType.JS) for text resizing.

If you really need the fix, I could try to work on it for you or some price. Just [contact me](http://alvarotrigo.com/#contact-page).

**Comment by alvarotrigo** [comment]
The issue with `scrollOverflow:true` in touch devices [has been already treated](https://github.com/alvarotrigo/fullPage.js/issues/506) and still not solved.

If that's not working well for you, I'm afraid there's no proper solution for it. I would recommend you to use the `responsive` option to set he page to `autoScrolling:false` once reached certain `width`, or, otherwise, use CSS3 media queries or responsive techniques such as [FlowType](https://github.com/simplefocus/FlowType.JS) for text resizing.

If you really need the fix, I could try to work on it for you or some price. Just [contact me](http://alvarotrigo.com/#contact-page).
