### ISSUE TITLE
Request for separate non legacy fullpage.js

### ISSUE THREAD

**Issue by mitcheal** [alvarotrigo/fullPage.js#1132]
I really value this package, however I would like to know if there is another project branched from this or planned that might be a little more light weight and drops support for IE 8-.   Leaning more on VH etc.   I don't expect this project to go that direction (I think thats a good thing) but I would like to follow any lightweight more HTML5 solutions going into the future.

**Comment by alvarotrigo** [comment]
What exactly you want to add to the plugin? What kind of HTML5 solution are you looking for?

**Comment by mitcheal** [comment]
Was thinking about leveraging VH units a bit more, and taking out as much jquery and javascript as possible (with a few exceptions that CSS3 / HTML5 can't handled).   More less a challenge to see how much of this fullpage effect can be achieved only using CSS3 / HTML5.   Because within 18 months that will be the solution i'll be leaning towards.

**Comment by alvarotrigo** [comment]
You can read [this topic] related with the use of `vh` instead of percentages or pixels.
It doesn't seem to be a good solution. Percentages should work just fine, as it is done in the pure javascript version.

Regarding the drop of javascript or jQuery, that's impossible nowadays. The plugin is already making use of CSS3 to perform animations, and that's as much as you can do with CSS nowadays.

CSS won't be able to deal with mouse / touch events or anything requiring a bit of logic. And neither HTML5. 
That's why javascript is there and that's why javascript is still being used nowadays. CSS and HTML5 are not replacements of javascript. 
Regarding animations, CSS has improved with version 3, but still not being able to deal with logic.

As I said before, you can make use of the pure javascript version of fullPage.js which gets rid of the jQuery library and its only 6Kb gzipped.

**Comment by alvarotrigo** [comment]
I close it until provided viable ideas for this request.
