### ISSUE TITLE
Problem with scrolling down

### ISSUE THREAD

**Issue by DDROTT** [alvarotrigo/fullPage.js#1141]
Hello,

I have problem with scrolling down to the next slide.
See example: http://sedmica.rs/problem/

Try to go to next slide "illustrations", and the drag slide to the left, to see new horizontal slide. Then try to go scroll down. It sends you to the first slide again. Why?

I use dragdealer plugin for dragging because your plugin does not support dragging, right? 

Can you help me to slove this problem?

Thank you

**Comment by alvarotrigo** [comment]
When you drag the slide the active class dissappears from the current section. 
Make sure your other plugin is not using the `active` class as well or change it by changing the [line 27 of fullPage.js](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L27)

I would personally apply your other plugin to another wrapper inside the section instead of to the section itself.
