### ISSUE TITLE
afterLoad callback on touch devices

### ISSUE THREAD

**Issue by br0k3n** [alvarotrigo/fullPage.js#1185]
Hi guys,

I'm using this fabulous plugin, but I stumbled upon an error on touch devices.
I'm calling a callback function fired thanks to "afterLoad", but on mobile devices nothing appends (on desktop / laptop all is ok).

Here's the code:

```
$('#my_class').fullpage({
sectionSelector: '.my_section',
css3: true,
resize: false,
controlArrows: false,
slidesNavigation: true,
afterLoad: function(anchorLink, index){
alert('test'),
}
});
```

Please, could someone help me?

Thanks

br0k3n

**Comment by alvarotrigo** [comment]
You should end with a semicolon, not a comma: `alert('test');`

And probably to test it you want to use other thing rather than an alert...

Provide a way to reproduce your problem. I can't by myself.  It's working as expected on the [callbacks demo page](http://alvarotrigo.com/fullPage/examples/callbacks.html#secondPage).
