### ISSUE TITLE
normalScrollElementTouchThreshold and Mobile Google Maps

### ISSUE THREAD

**Issue by filipetedim** [alvarotrigo/fullPage.js#1281]
Hey there. Excellent job with this plugin, hands down!

I seem to have a problem using fullPage with google maps on a mobile environment tho. No matter how much I increase the normalScrollElementTouchThreshold, and I've also set the normalScrollElements with the div that contains the map (#map_container).
That div contains the google code for the map (the directly inside div has the class='gmap').

And what is happening is kind of strange; Since the map is the last vertical page of the fullPage and it has no scrolls to the sides, I can scroll it to the sides and down, and if I start by doing that I can also move it up until I lift my finger. But if I start by scrolling it up, it just moves vertically to the previous page.

Any idea of what's going on?

**Comment by alvarotrigo** [comment]
Google maps its loaded in an iframe and I'm not quite sure if touch events can be propagated up from it. 
I would have to check it.

In any case, not quite sure if that would work in Firefox either. Check [this topic](https://github.com/alvarotrigo/fullPage.js/issues/803).

**Comment by nurulakbar** [comment]
i also have the same issue. any solution will be really apreciated :(

**Comment by alvarotrigo** [comment]
Check [this topic](https://github.com/alvarotrigo/fullPage.js/issues/1497) for possible solutions (layers, disable touch events etc).

A section with a full map in it makes no sense in fullpage.js and I believe that if you want to display a dragable map in some part of the section/slide, it still being necessary a button, arrow or something to allow the user to scroll up/down/left/right instead of forcing them to swipe outside the map.

In this case, the touch disable and enable solution seems the way to go for it. 
I'll close therefore the issue.

**Comment by guytzhak** [comment]
There is any solution?

**Comment by alvarotrigo** [comment]
@guytzhak not until you see this topic marked as "fixed" and without the "bug" tag and closed (same for any other open issue)
