### ISSUE TITLE
Return to main slide of each section on leave

### ISSUE THREAD

**Issue by adamhairfield** [alvarotrigo/fullPage.js#129]
I didn't know if this exactly qualifies as an issue so if it needs to be located somewhere else please let me know.

What I need is that when the user leaves each section, that section should automatically return back to the main slide of the section.

For example, using the my test site located here: http://trouve.thinkatmosphere.com. If I am currently on the 'about' section and I navigate to the right and then leave the 'about' section and navigate down to the 'client' section when I return to the 'about' section I need it to be on the first slide of that section again.

How would I modify the following code to allow me to perform this:

```
$.fn.fullpage.moveToSlide = function (index, slide) {
  var destiny = '';
  if(isNaN(index)) {
    destiny = $('[data-anchor="'+index+'"]');
  } else {
    destiny = $('.section').eq( (index -1) );
  }
  if (isNaN(index) && slide !== 'undefined') {
    scrollPageAndSlide(index, slide);
  } else {
    if (destiny.length > 0) {
      scrollPage(destiny);
    }
  }
};
```

**Comment by inigocanedo** [comment]
Hi Álvaro,
I've continued working on the website i asked you about a few weeks ago. My client decided that his site should return to main slide of each section on leave.

I followed the instructions in this page and all worked out, except for the last section ( http://www.avec.mx/clientes/brodeer/#Casa-Bobadilla ), where I navigate to a slide other than de first one, and then navigate to the next section ( which is the fist one [ http://www.avec.mx/clientes/brodeer/#Brodeer ] ), and then go back to the last/previous section ( http://www.avec.mx/clientes/brodeer/#Casa-Bobadilla ) where it hasn't return to the firs slide and it doesn't let me navigate to the left.

I think is the same issue <a href="#issuecomment-30771852">adamhairfield mentioned on December 17, 2013</a>. I tried to follow your instructions about  <code>landscapeScroll</code> but the code of the plug in has changed since then, so I don't know what to do. 

Could you help me please?

**Comment by alvarotrigo** [comment]
@inigocanedo I'm afraid I don't provide support for particular usages of fullPage.js or core modifications. You should better ask in other places such as stackoverflow.com where they'll help you much better.
Your issue is a javascript related issue and not a fullPage.js one.

**Comment by alvarotrigo** [comment]
This is now easier to do by just using a [fullpage.js extension](http://alvarotrigo.com/fullPage/extensions/).
This way you don't have to worry about fullpage.js updates and possible compatibility issues with your own code.
