### ISSUE TITLE
Website flashes for a moment

### ISSUE THREAD

**Issue by ArthurZubkoff** [alvarotrigo/fullPage.js#1296]
Every time I load my website, it flashes the whole content for a moment: http://dekatria.co.uk/. Could you please advise me on this issue?

**Comment by alvarotrigo** [comment]
Initialize it on DOM ready as stated in the docs, and not on load.

**Comment by alvarotrigo** [comment]
If you still preferring using fullPage.js on load, then you would have to add the following CSS:

```css
html,
body,
#fullpage,
.section{
    height: 100%;
}
```

Where `#fullPage` is the selector you use to initialize fullPage.js and `.section` is the selector you use for the classes.

**Comment by ArthurZubkoff** [comment]
**fullPage.js** was already initialised inside the DOM ready:
```
$(function() {
    $('#fullpage').fullpage();
});
```

I tried both of your approaches: moved **jQuery** and the **fullPage.js** initialisation to the ```head```, and also tried applying the CSS you have suggested. Nothing seems to work.

**Comment by alvarotrigo** [comment]
I've tried it with [this example](http://paste.ofcode.org/upjQQ2eWQJbr9ZXxjrGHcq) and it works as expected applying the CSS styles I mentioned.

The CSS file will load before your DOM is ready. 
If you make sure that your sections are 100% height before anything loads, then you won't see the flickering anymore as the flickering was caused by showing the 2nd or 3rd section before the plugin was applied.

**Comment by alvarotrigo** [comment]
> fullPage.js was already initialised inside the DOM ready:

Even though you are using document ready, you are placing the javascript at the bottom of your site, just before the closing `</body>`, and this will force the javascript to load at the end, once the whole site is loaded. 
So in this case your document ready will be like a document load.

**Comment by ArthurZubkoff** [comment]
Thank you!
