### ISSUE TITLE
slideIndex is wrong

### ISSUE THREAD

**Issue by polikin** [alvarotrigo/fullPage.js#1349]
Why `slideIndex` give me the direction and `direction` give me `undefined`

```
$('#app').fullpage({
	easingcss3: 'cubic-bezier(0.785, 0.135, 0.150, 0.860)',
	//easeInOutCirc
        verticalCentered: true,
	navigation: true,
	scrollOverflow: true,
	scrollingSpeed: 1000,
	//autoScrolling: false,
	sectionSelector: '[data-section]',
        onLeave: function(anchorLink, index, slideIndex, direction, nextSlideIndex){
		console.log(slideIndex);
	}
});
```

**Comment by alvarotrigo** [comment]
Because you are not using them in the correct order:

[From the docs](https://github.com/alvarotrigo/fullPage.js#afterslideload-anchorlink-index-slideanchor-slideindex):

>         afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){},

The order the only thing that matters, the name of the variable is whatever you want to use. Remember this is a javascript callback and therefore works as any other.
