### ISSUE TITLE
Anchors not working with angular.js ng-include

### ISSUE THREAD

**Issue by shadihrr** [alvarotrigo/fullPage.js#1429]
I already submited a question in stackoverflow. My html is as follow 
  ```
<div id="fullpage">
  <div class="section" id="main-description">
       <div class="animated fadeIn" main-description></div>
</div>
<div class="section" id="features">
    <div features></div>
</div>
```
Which in directive i used ng-include="...." directive. With doing that fullpage adds a slash between anchor name and # while switching between sections

**Comment by alvarotrigo** [comment]
> Which in directive i used ng-include="...." directive. With doing that fullpage adds a slash between anchor name and # while switching between sections

Can you explain that more in detail?

**Comment by alvarotrigo** [comment]
You would have to explain what `ng-include` does. I'll close the issue until more information is provided.

**Comment by shadihrr** [comment]
ng-includes is an angular directive. it includes another html file into your current html. It is a common angular directive. I thought since angular is used alot you would take a look at the problem.

**Comment by alvarotrigo** [comment]
> I thought since angular is used a lot you would take a look at the problem.

People using fullpage.js is using many different technologies and rather than me having to investigate and learn them, i prefer people to tell me what they do so we can both figure the problem faster. 
(By the way, I use knockout.js rather than angular.js)

Could you provide a reproduction of your problem? It would be much clearer. 
Right now there's nothing I can say as I'm not seeing the whole picture.
