### ISSUE TITLE
Screen is not normal until resizing

### ISSUE THREAD

**Issue by Chrisande** [alvarotrigo/fullPage.js#1460]
When you open the webpage, it is zoomed in on the background-pictures, and doesn't scroll normally - until you resize the window. I tried to look up the problem here on Github, but couldn't find anything similar. 

Anyway, the website is this:

http://www.repowerearth.org

You can look in the page source for the code, thanks in advance

**Comment by alvarotrigo** [comment]
You seem to be doing something wrong. It doesn't take place in any of [the demo pages](http://alvarotrigo.com/fullPage/).

I'm afraid you would have to provide an isolated reproduction of the problem (in jsfiddle or codepen) for further investigation .
I'll assume now the problem is in your side and not in fullpage.js
