### ISSUE TITLE
How to divide one section to 2 on mobile?

### ISSUE THREAD

**Issue by umarfarukm** [alvarotrigo/fullPage.js#1517]
![divide-sections](https://cloud.githubusercontent.com/assets/1221599/9935498/93b08186-5d74-11e5-9813-693b8f1149cf.jpg)

Any possibility to divide one section into two while browsing on mobile devices? I need to keep the auto scroll effect when user try to scroll and it have to land on next section.

Thank You.

**Comment by RobR8** [comment]
Hey @umarfarukm this is just a guess but couldn't you just change your head based on mobile or desktop and then have different css file(s) and load a different fullPage init.

Mobile would have an extra section and modified css for section 2 and section 3 (in reference to your mobile page), and then the Desktop would have those two sections merged into one, with css to only be half width instead of full width

**Comment by alvarotrigo** [comment]
- Listen the resize event
- Destroy fullpage.js ( with `destroy('all')`) when reaching the `with` or `height` you want.
- Create a new section from your slide or whatever 
- Initialize fullpage.js again.
