### ISSUE TITLE
Content on adjacent slides pushes down the current slide on page load.

### ISSUE THREAD

**Issue by alexshak** [alvarotrigo/fullPage.js#1578]
May have the initialising settings wrong but when I add content to offscreen slides they cause the starting slide to be pushed down on load. Problem corrects itself if the window is resized. 

Current options: 
        easing: 'easeInOutCubic',
        easingcss3: 'ease',
        loopHorizontal: false,
        slideSelector: '.page-slide', //(Using a bootstrap carousel) 
        verticalCentered: true,

Have I not used the right options - or if so is there a way to apply a resize to an afterRender callback? (tried .resizeTo with no luck) 

EXAMPLE: http://pixapops.com/

Thanks for your great work.

**Comment by alvarotrigo** [comment]
Yep, that's totally normal. 
The plugin needs your DOM structure to be ready in order to get initialized. And meanwhile, your content will be visible in the order it should.

Instead of using fullpage.js at the bottom of your page before the cosing `</body>` I would recommend you to load it on your header `<header>` of your site.

Same as with any other plugin or script you use. 
Why? 
Because the only reason to add the plugins at the bottom of the site is to prevent the site to be "locked" until they load.
But if your main purpose is to only show the site once the plugin is initialized, then there's no reason at all to add them at the bottom of your site. 

That should solve your problem.

**Comment by alvarotrigo** [comment]
You can test it here as well: http://jsfiddle.net/813euvy2/

**Comment by alexshak** [comment]
Ahh thanks for taking the time to explain. Much appreciated.

**Comment by alexshak** [comment]
I have adjusted to JS loading but not matter what I do I can't recreate the result in the fiddle even if I directly copy the entire fiddle into the index.html. I can see that you're referencing all the existing JS and CSS but just checking there isn't anything changed on a settings front that I may not have adopted.

**Comment by alvarotrigo** [comment]
Can you provide me with the link?

**Comment by alexshak** [comment]
Of course yes, http://www.pixapops.com/

Alexander Shakhovskoy
e. alexshak@gmail.com
m. 0479112280

**Comment by alvarotrigo** [comment]
> Content on adjacent slides pushes down the current slide on page load

I have reload the site multiple times forcing the load of all elements (CTRL +F5) and I'm not able to see any content of the 1st or 3rd slides at any moment.

What's the problem you are having?

**Comment by alexshak** [comment]
The content is pushed down below the frame when site first loads - if I
resize the window at all everything falls perfectly into place. I'm just
trying to work out why all my content loads below the frame and if there is
some way I can force the resize function to run on page load.

Alexander Shakhovskoy
e. alexshak@gmail.com
m. 0479112280

**Comment by alvarotrigo** [comment]
You are missing the compulsory doctype at the start of your file.
Add this in the first line of your page:

```<!DOCTYPE html>
```

**Comment by alexshak** [comment]
Thank you, can't believe it was something so basic.

Alexander Shakhovskoy
e. alexshak@gmail.com
m. 0479112280
