### ISSUE TITLE
Scrollbar still appear 

### ISSUE THREAD

**Issue by Seb33300** [alvarotrigo/fullPage.js#1613]
I would like to scroll only by clicking on buttons I put on my page.

So i set options to:
- autoScrolling: false
- scrollBar: false

But scrollbar still appear on the page!

**Comment by alvarotrigo** [comment]
> But scrollbar still appear on the page!

Because you didn't read the documentation carefully.

autoScrolling: (default true) Defines whether to use the "automatic" scrolling **or the "normal"** one. It also has affects the way the sections fit in the browser/device window in tablets and mobile phones.

This means, normal scrolling will ALWAYS have scroll bar. So you should use the default  `autoScrolling: true` and the default `scrollBar:false` as in the [demo page](http://alvarotrigo.com/fullPage/) which, by the way, is available in the examples folder.

**Comment by Seb33300** [comment]
I read that, but what I want is to disable both mouse wheel ans scrollbar

**Comment by alvarotrigo** [comment]
That doesn't exist.

**Comment by alvarotrigo** [comment]
Or, if you just want keyboard, use the method `setAllowScrolling(false)`
