### ISSUE TITLE
moveSlideLeft() doesn't work

### ISSUE THREAD

**Issue by ChizHuang** [alvarotrigo/fullPage.js#1630]
Hi,

I'm using Chrome version 46 and tried one of your examples here:
http://codepen.io/alvarotrigo/pen/gpdLjW

After I've scrolled down to the 2nd slide (the orange one), I click the "Slide Left" button at the upper right corner. The slide is supposed to slide left after clicking, but nothing happens. I tried the code in my own codepen and it doesn't work either. Basically, moveSlideLeft() is not working, but moveSlideRight works well.

My codepen: http://codepen.io/Chiz/pen/MaBwBb
(when you click the "Prev" button, slide doesn't move left, but the "Next" button works well)

Pls advise.
Tks!

**Comment by alvarotrigo** [comment]
It works perfectly in [the codepen provided in the docs](http://codepen.io/alvarotrigo/pen/gpdLjW) and in [this demo page](http://alvarotrigo.com/fullPage/examples/methods.html).

Take a look at them.

Of course, it will only scroll left if you are not in the 1st slide. 
Otherwise, you would need to use the option `loopHorizontal:true` and it will scroll **forward** to the third slide.

There's no concept of circular-inifnite-continuous horizontal scrolling in fullpage.js.
Check [this topic](https://github.com/alvarotrigo/fullPage.js/issues/316) out.
