### ISSUE TITLE
Trackpad Chrome 47 Auto Scroll Issue

### ISSUE THREAD

**Issue by MichaelCastelbuono** [alvarotrigo/fullPage.js#1695]
I'm getting identical results to what's explained here #1534. Essentially the trackpad is firing up when trying to scroll down. This was confirmed with your jsfiddle [here](http://jsfiddle.net/bpwydfne/2/). In Chrome (47.0.2526.73 (64-bit) at the moment) it will show `up` events when scrolling `down`. In fact, even if I just press down with two fingers, it fires `up` twice. Now, I know this seems like a trackpad issue, or a non fullpage.js issue, but here's where it gets weird and I'm hoping you have some insight.

The [demo example page](http://alvarotrigo.com/fullPage/) works smoothly for me. However, the [demo wordpress page)(https://themify.me/demo/#theme=fullpane) does not, and it actually suffers from the same issue that my site has. My site is using wordpress too btw.

The issue is not present with a mouse, or when using FF or Safari. I've only tested on a Mac.

**Comment by alvarotrigo** [comment]
Just to let you know, you should be testing in the latest example I provied in #1534 which is [this one](http://jsfiddle.net/bpwydfne/6/).

In any case, the problem was solved in fullpage.js 2.7.2 and the problem with the wordpress theme is that they are not using the latest fullpage.js version (2.7.5). Just update the javascript file and you should be alright.

**Comment by MichaelCastelbuono** [comment]
Thanks, 2.7.5 definitely fixes it. I thought I had tested with the newer version, but I didn't realize my theme was using an aggregated and minified version of the scripts, so it was never using the updated version.
