### ISSUE TITLE
On scroll with a video background bug

### ISSUE THREAD

**Issue by weareburo** [alvarotrigo/fullPage.js#183]
I have a video on background, an overlay + some text. When i scroll and come back to the video section my overlay and text disapeared even if my z-index is ok.
My sample home is here :https://dl.dropboxusercontent.com/u/29620302/fullPage.js-master%203/examples/home.html
Any Idea ? Does i need to adjust this with unleave function ?

**Comment by arnisjuraga** [comment]
I have the same problem. Could not fix it with any "z-index" settings, but @alvarotrigo is right - setting `css3: false` is a workaround.

Now - video stays at background, although - Chrome now works notably slower with scroll and video playback.

This problem is visible also on Fullpage.js Example page http://alvarotrigo.com/fullPage/examples/videoBackground.html 
- open page
- scroll down,
- scroll back to 1st section - You will see, that Text is not visible at first moment, because Video has come to the very Front. 
And only after full load, text appears.

Is it configurable, to keep "css3: true" but fix the scrolling with video background?

**Comment by alvarotrigo** [comment]
@arnisjuraga see my answer [here](http://stackoverflow.com/a/36671466/1081396).

**Comment by arnisjuraga** [comment]
Excellent!
