### ISSUE TITLE
Scrolling with trackpad in Firefox 44 skips sections

### ISSUE THREAD

**Issue by zrubinrattet** [alvarotrigo/fullPage.js#1846]
In Firefox 44 on OSX 10.10 and 10.11 I've noticed sometimes if you do a hard swipe up or down it will skip over 1 or 2 sections. I've tested this on your demo page: http://alvarotrigo.com/fullPage/#4thpage with browserstack. arrow keys work fine though. how can this be fixed? thanks!

**Comment by alvarotrigo** [comment]
Sorry I can not reproduce it under the same environment. (Firefox 44 on trackpad on the demo site).
It seems to me that browserstack is not the best option to test the kinetic scrolling due to the lag on receiving the scroll event on their servers, please try again in a real device and come back if you still finding the problem.
