### ISSUE TITLE
Navigation dots and dynamic sections

### ISSUE THREAD

**Issue by shawnebeyer** [alvarotrigo/fullPage.js#1873]
Hi, wondering if anyone can help with these two issues;

I have six sections on my site, however, I need to maintain a set amount of navigation dots. Basically, I need to be able to scroll from section 4 to section 5, but I don't want section 5 to have a nav dot. Is there any way to have a section without a corresponding dot?

Question 2 (apologies for the double ask:(..); I have a section that should only be visible based on an option selected by the user. So if the user selects this button, they will scroll down to this section. If they do not choose this option, they should scroll down to another section. I've tried adding a class of "section" via a click handler, also tried the old display:none/display:block way, but every time I try something like that, the page just won't scroll past the section and gets hung up.

Any help would be much appreciated!

Thanks in advance,

Shawn

**Comment by alvarotrigo** [comment]
I would encourage you to ask in http://stackoverflow.com/ for this kind of questions. 
This forum is to treat directly related issues with fullpage.js. 

Regarding your 2nd question, fullpage.js might not work properly with dynamic added or removed sections (or hidden), I would encourage you to change the content of the section rather than trying to play with sections elements.

**Comment by shawnebeyer** [comment]
Thanks for the insight, Alvarotrigo!
