### ISSUE TITLE
Audio plays on page load in Firefox

### ISSUE THREAD

**Issue by hacklab01** [alvarotrigo/fullPage.js#1895]
If an audio element is loaded it plays on page load before it's slide was ever opened. When navigating to the slide with the audio it pauses as in should when navigating away. 

Reproducable in autoMediaPlayPause.html example.

Working fine on Chromium .

**Comment by alvarotrigo** [comment]
Can you please provide a reproduction of it in jsfiddle or codepen as detailed in the [reporting issues](https://github.com/alvarotrigo/fullPage.js#reporting-issues).

Is it only on firefox then?

**Comment by hacklab01** [comment]
Sorry about that, I skipped it since I reproduced it with example code. https://jsfiddle.net/fpc26mw5/2/
Firefox 44.02 Linux Mint. Working in Chromium, can't test in other browsers right now.

**Comment by alvarotrigo** [comment]
Instead of initializing the plugin onLoad you can do it on document ready to avoid the problem.
[Reproduction online](https://jsfiddle.net/fpc26mw5/3/)

I always recommend to do it on document ready, as it makes no sense to wait for the content if the plugin hasn't created the structure yet. You don't want users to see the content without the full screen structure or even allow them to see slides or sections which are not suppose to be seen yet.

As the documentation specifies, use this:
```javascript
$(document).ready(function() {
    $('#fullpage').fullpage();
});
```

**Comment by hacklab01** [comment]
But that's how it was - on document ready. The same thing still happens on your jsfiddle link.

Am I missing something here? :)

**Comment by hacklab01** [comment]
Same think in Firefox 45.0 on Windows

**Comment by alvarotrigo** [comment]
Sorry, I was just checking it on Chrome and the problem got solve by just adding the document ready. 
I'll open it again.

**Comment by hacklab01** [comment]
Jsfiddle seems to have a slight delay on load in Chrome aswell.The audio starts briefly then pauses.  That doesn't happen in Chromium with an actual install.

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.8.0.
You'll need to use the attribute `data-autoplay` to play it on section load instead of `autoplay`.

It will get paused automatically on section/slide leave. To avoid it use `data-keeplaying`.

It is all detailed in the docs.
