### ISSUE TITLE
Slides turning to sections on responsive

### ISSUE THREAD

**Issue by faliqaiman** [alvarotrigo/fullPage.js#1919]
How to destroy **slide** function on r**esponsive mode**? Which it will display block when its in responsive mode. And will be fullpage when desktop view.

try with this method but didn't work.
`$.fn.fullpage.destroy(.slide);` 

Anyone have tried this so far?

**Comment by alvarotrigo** [comment]
> Which it will display block

What do you mean by that.
Convert horizontal slides into vertical sections?

**Comment by faliqaiman** [comment]
Would like to make slide become vertical section on mobile. Any trick can done this thing?

**Comment by alvarotrigo** [comment]
Nop, that would be a new feature request.
I'll mark it as an enhancement. 

If you really need it now you can [contact me](http://alvarotrigo.com/#contact-page) for an urgent request.

**Comment by alvarotrigo** [comment]
This is possible now with the [new fullpage.js extension Responsive Slides](http://alvarotrigo.com/fullPage/extensions/responsiveSlides.html) and the option `responsiveSlides`.

**Comment by faliqaiman** [comment]
Great, thanks mate! One more to confirm b4 purchase this extension, is there any conflict if combine **Responsive Slide + Continuous Horizontal Scroll + Scroll Horizontally** ? Please advise.

**Comment by alvarotrigo** [comment]
> is there any conflict if combine Responsive Slide + Continuous Horizontal Scroll + Scroll Horizontally ?

Well, I don't really know what you expect, but there's some kind of conflict between continuousHorizontal and scrollHorizontally.
If you use continuousHorizontal you expect to always scroll back to the 1st slide of the slider when sliding right on the last slide.
But if you also use scrollHorizontally to be able to scroll with the mouse wheel, this would create a loop from which you would never be able to escape.

So in this case, what fullpage.js does is scroll DOWN **when using the mouse wheel** on the last slide instead of sliding back to the 1st. 
This way there won't be a loop when using the mouse wheel. 

But, on the other hand, when using the arrows in the slider or the keyboard to slide right on the last slide, **it will slide back to the 1st slide** using the continuous horizontal extension. 

It shouldn't be any problem with the responsiveSlides one.

I uploaded a demo for you [here](http://alvarotrigo.com/fullPage/extensions/3.html) so you can see it in action.
