### ISSUE TITLE
Adding borders to sections

### ISSUE THREAD

**Issue by marcbakker84** [alvarotrigo/fullPage.js#1925]
Hi Alvaro,

First of all thanks for the great work on fullPage.js; it's awesome :)

I have a problem in adding a border around a section. When i add a 30px border to a section the section gets longer than fullheight (and therefore isn't showing the top or bottom border depending on the last scroll direction).

Is this an issue or can i do something myself to solve this?

Thanks!

**Comment by alvarotrigo** [comment]
Use a wrapper to do it:
http://jsfiddle.net/97tbk/1153/

**Comment by marcbakker84** [comment]
Thanks a lot!

**Comment by bevels** [comment]
Likewise, thanks!

**Comment by BartVoll** [comment]
Thanks for this!
I found one issue with it though. When the section contains slides, with responsiveSlides and responsiveWidth enabled, it will ignore the wrapper div at some point. This is happens when you resize the window until responsiveSlides and responsiveWidth gets activated, then resize it back. Is there any way to go about this?

**Comment by elebumm** [comment]
Hello, people from the future...

@alvarotrigo's jsfiddle 404's. To elaborate on what he mentioned, if you have a `<div class="section">...</div>`... add a wrapper inside like such.

```html
<div class="section">
    <div class="section-container">
        ....
    </div>
</div>
```

Then the CSS I added was: 

```css
.section-container {
    border: 10px solid white;
    height: 100%;
}
```

The height will make the height of the container the same as the fullpage.js.

Cheers!

**Comment by alvarotrigo** [comment]
@elebumm thanks for that! ;)
