### ISSUE TITLE
Reloading pages shows content all messed up for a moment before arranging it again 

### ISSUE THREAD

**Issue by arquadrado** [alvarotrigo/fullPage.js#1928]
Hello, I'm doing a website using your plugin fullPage.js and I've got almost everything working pretty well but when I reload the page or I change to another page, for a moment, some of the content of the page is shown all messed up before it rerenders all how it should be... Although the site works well it's pretty ugly to see all the content scattered around when you do change page. You have any idea about this and how can be solved? Thanks in advance!

**Comment by alvarotrigo** [comment]
See [this answer](http://stackoverflow.com/a/36061842/1081396)

I'll quote myself:

I always recommend people to use load fullPage.js in the header contrary to the popular trend which adds JS files in the body.

**Why?**
Because I consider fullPage.js is essential for the correct visualization of your site. Without fullpage.js, your sections won't be of the correct size, they will be overlapping as you mention, slides content will be visible when it shouldn't...

Some of those things require of fullpage.js to run, detect dimensions of your content, set the slides to the right position etc.

You can check this in any of [the demo pages](http://alvarotrigo.com/fullPage/) provided by fullPage.js and you'll see there's no such blink. 

**If you still don't want to go for this solution to speed up the loading of your site.**, what I would recommend is to use the critical CSS technique to set the size of your sections as fast as possible (even when fullpage.js is not initialized yet) and without any HTTP request (to speed it up even more)

Use the following inline styling in the header of your site:
```html
    <style>
        html,body {
            margin: 0;
            padding: 0;
            overflow:hidden;
        }
 
        .section,
        .slide,
        .fp-tableCell{
            height: 100vh;
        }
    </style>
```
This will solve the problem with the blinking sections.

**Some of the possible problems**
- If you are using a conditional initialization of fullpage.js, this will still be applied even when you don't need it.
- If you destroy fullpage.js dynamically, this will still be applied when you don't need it.
- Sections with bigger content than the viewport won't have scroll bar until the plugin is loaded and initialized. 
- Slides will be accessible for the user even when you don't want it by using `setAllowScrolling(false)` in some slides.

**Comment by arquadrado** [comment]
Well, thank you for your answer, I'll try out!
