### ISSUE TITLE
Problem when using waypoints

### ISSUE THREAD

**Issue by Bondra** [alvarotrigo/fullPage.js#2014]
Hi!

First of all, thanks for this awesome plugin!

I've implemented waypoint.js which works good in most cases but when scrollOverflow is set to true I run into problem. Since I have content that is larger than the viewport I need to have the content scrollable. The problem is that no waypoints are getting triggered in a scrollOverflow container by some reason. waypoint.js is supposed to work with containers with overflow:auto as far as I can see over here: http://imakewebthings.com/waypoints/guides/jquery-zepto.

Is there a solution to this?

**Comment by alvarotrigo** [comment]
slimScroll.js is the vendor library used when using scrollOverflow, and it doesn't provide a way to do it.

**Comment by xmon** [comment]
Hi @Bondra you can find a alternative solution like me, [here](http://stackoverflow.com/questions/39359639/with-fullpage-js-can-y-position-inside-sections-be-reported-during-scrolloverfl), now fullPage use iScroll (fork).

There are a [pending pull-request](https://github.com/alvarotrigo/fullPage.js/pull/2531) to this repo with scrollOverFlow-probe.js, and I change waypoints.js to [jquery.visible.js](https://github.com/customd/jquery-visible)

This issue is from a year, but I didn't find a working solution for this question, I like to share.

cheers.
