### ISSUE TITLE
Is it possible to have not sections elements on page, such as footer?

### ISSUE THREAD

**Issue by vk011** [alvarotrigo/fullPage.js#2032]
Hello,

Say I have 5 sections and a footer below, I want that if on the last section and scrolling down for scrolling to be normal so the user can see the footer. And if ithe footer is not in the viewport the scrolling should continue.

Sounds like a handy thing.

Is something like this possible?

**Comment by alvarotrigo** [comment]
You should be using 'fp-auto-height' for the footer. Read [the docs](https://github.com/alvarotrigo/fullPage.js#creating-smaller-sections) about it.

Otherwise, use `scrollOverflow` as in [this example](http://alvarotrigo.com/fullPage/examples/scrolling.html).

**Comment by smachi** [comment]
Hi Alvaro,

I have the same exact problem.
But the solution you mention here would be valid for a footer that is part of the fullPage div (as an inner section), right?

The problem is how to get this for any div outside and below the fullPage container.
To be more specific: I'd want to get a similar behavior as in this example:
[](http://alvarotrigo.com/fullPage/examples/oneSection.html)

But with a vertical slide with multiple autoScrolling sections and more content out of the fullPage slides under it with a normal scroll

I've tried to enable the scroll bar and works dragging down the scrollbar with the mouse but don't apply any scroll with the mouse wheel or keyboard down key (if the KeyboardScrolling is enabled) after the last slide.

Is there a way to fix this?

**Comment by alvarotrigo** [comment]
> But with a vertical slide with multiple autoScrolling sections and more content out of the fullPage slides under it with a normal scroll

Not possible yet.

**Comment by MaciejJanyska** [comment]
@alvarotrigo Any chances to add this in the near future?

**Comment by alvarotrigo** [comment]
@MaciejJanyska maybe.

**Comment by MikeiLL** [comment]
I could really use this too, as I'm using it in a Wordpress theme built with the Unyson framework and I would like users to be able to dynamically add sections within a "page builder" div, but also have a footer we can get to.

**Comment by MikeiLL** [comment]
I can kind of achieve it with the following code:

```
$('#fullpage').fullpage({
  menu: '#vertical-nav',
  navigation: true,
  navigationPosition: 'right',
  fixedElements: '.header-wrap',
  onLeave: function(index, nextIndex, direction){
      var leavingSection = $(this);
      var allSections = $('.section');
      if (index === (allSections.length) && direction === 'down') {
        $.fn.fullpage.setAutoScrolling(false);
        $.fn.fullpage.setFitToSection(false);
      }
      if (index >= (allSections.length) && direction === 'up') {
        $.fn.fullpage.setAutoScrolling(true);
        $.fn.fullpage.setFitToSection(true);
      }
  }
});
```
But it is hacky.
