### ISSUE TITLE
fp-auto-height does not seem to be working

### ISSUE THREAD

**Issue by vk011** [alvarotrigo/fullPage.js#2061]
### Description
I have 5 sections, the first 4 are supposed to have page height but the last is supposed to have content height. I've applied the 'fp-auto-height' class to the last section but it does not seem to have an effect, it still acts full height.

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/qrqf3c76/

### Versions 
2.5.9

**Comment by alvarotrigo** [comment]
Update to 2.8.1.

**Comment by jtlscout** [comment]
I figured out that the reason it doesn't work is because the CDN on the GitHub repository doesn't support fp-auto-height. Here's what does:
<link href="https://rawgit.com/alvarotrigo/fullPage.js/master/jquery.fullPage.css" rel="stylesheet"> <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.js"></script> <script src="https://rawgit.com/alvarotrigo/fullPage.js/master/jquery.fullPage.js"></script>
