### ISSUE TITLE
The plugin seems to disable regular scroll event detecting

### ISSUE THREAD

**Issue by vk011** [alvarotrigo/fullPage.js#2063]
Awesome plugin (the best I've tried). but it seems to disable detecting other scroll events, for example

```
$( window ).on( "scroll", function() {

        alert('code');

    });
```

never alerts `code` while scrolling.

Can we enable detecting page scrolling?

https://jsfiddle.net/qrqf3c76/1/

**Comment by alvarotrigo** [comment]
Because the plugin never really scrolls. See the [FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions).

Also, you should be using the plugin callbacks such as onLeave or afterLoad or the state class added to the body as explained in [this tutorial](https://www.youtube.com/watch?v=qiCVPpI9l3M).
