### ISSUE TITLE
scrollOverflow: true, still causes not clickable links in section2 only

### ISSUE THREAD

**Issue by metrickstar** [alvarotrigo/fullPage.js#2073]
In release 2.80 aswell as in 2.81 `scrollOverflow: true` causes not clickable links in section2 - so in fact inside of the third section.
All links are working in section0 as well as in secion1 or section3, but in section2 it's impossible to click any link, if content is bigger than display - scroll is needed.

**Comment by alvarotrigo** [comment]
The bug was fixed in 2.8.1 as you can see here https://github.com/alvarotrigo/fullPage.js/issues/2035

Another bug which is yet to solve is the propagation of the click event: https://github.com/alvarotrigo/fullPage.js/issues/2047

Which one of these is your problem? 
Can you provide a reproduction of it? Otherwise I'll close it as a duplicate.

**Comment by alvarotrigo** [comment]
I'll close the issue until a reproduction is provided.
