### ISSUE TITLE
Fixed elements within fullpage.js

### ISSUE THREAD

**Issue by RealMakAttak** [alvarotrigo/fullPage.js#2079]
Hello all,

I hope you can help. Within a section I have a modal (overlay) which is set to scroll normally. Within this modal I would like some elements to be fixed when scrolling however, it will not work. I read that there is a bug that "position: fixed" will not work within any element that has had a 3d transform applied to it (fullpage.js). Is that the case or is there a workaround other people on here use?

Thanks

**Comment by alvarotrigo** [comment]
I guess you want to use the option `normalScrollElements` in there.
Not quite sure what's your problem and can't help without a reproduction in any case. 

I'll close the issue until an isolated reproduction is provided.

**Comment by tduncandesign** [comment]
I have run into this issue. I have an idea how to overcome it, but my js skills are not quite there. 

There is a long slide with a vertical timeline. I have my own next/previous horizontal scroll arrows. On the timeline slide, would like to keep the next/prev arrow tabs position:fixed so that they remain centered on screen as the timeline scrolls down, similar to how the bullet navs remain on screen (although they are outside the fullpage div). Those arrow tabs are inside the slide div, inside #fullpage. 

Because div#fullpage gets transform: translate3d(0px, -5060px, 0px); applied dynamically, the position:fixed fails. 

Now, if I put my arrows outside #fullpage and make them display:block when the body acquires the timeline slide's class, they work, however they are positioned at the "top" of the stack of slides... i.e., on the cover... relative to the entire height of the body, instead of the viewport. 

If I knew a way to read the current Y coordinate (-5060px in the pasted style above) when we enter that slide, I could maybe build some code into the onSlideLoad or SlideLeave callback that would dynamically set that top measurement to an inline style element on the positioned arrows. 

Does that make any sense? I don't know how to setup a codepen or anything. Anyway, maybe it will spur an idea to help someone else.

**Comment by tduncandesign** [comment]
Alright, I have figured this out. Caveat, I am a designer, not a programmer, so i really don't know what I am doing, I have cobbled this together from various snippets of js found on stack overflow.
 
The issue is set out in the OP: position: fixed fails when the fixed element is within a 3d transformed element. FullPage's #fullpage div is such. Per my post above, I wanted fixed previous/next arrows on my long scrolling slide. If I put those arrows within the slide's div, they scroll with the slide. If I set the arrows outside #fullpage div, they will be position fixed, but they appear at the top of the page, on the cover. 

This is how I fixed it. Arrows outside the full page div, but set initially to display none. When the body acquires the slide's class, css tells the arrows to display block. Then they are positioned via javascript on the afterSlideLoad callback. 

If anyone cares to read this and suggest a better way, please do. Otherwise, hope it helps someone else along. Here are my code snippets: 

**CSS:** 
```
div.timeline-arrows {display:none;}
body.fp-viewing-s4-3 div.timeline-arrows {display: block;}
body.fp-viewing-s4-3 div.timeline-arrows .fixedArrowLeft {
	position: fixed;
	left: 0;
 }
body.fp-viewing-s4-3 div.timeline-arrows .fixedArrowRight {
	position: fixed;
	right: 0; 
}
```

**Function for document.ready** 
```
// function to get the 3d transform offset on a slide so I can position the timeline arrows. - td
    function getTransform(el) {
    var results = $('#fullpage').css('-webkit-transform').match(/matrix(?:(3d)\(-{0,1}\d+(?:, -{0,1}\d+)*(?:, (-{0,1}\d+))(?:, (-{0,1}\d+))(?:, (-{0,1}\d+)), -{0,1}\d+\)|\(-{0,1}\d+(?:, -{0,1}\d+)*(?:, (-{0,1}\d+))(?:, (-{0,1}\d+))\))/)
 if(!results) return [0, 0, 0];
    if(results[1] == '3d') return results.slice(2,5);
 results.push(0);
    return results.slice(6, 7); // this gets me just the top offset from the array...  
}
```

**JS for inside the afterSlideLoad callback in Full Page init code:**
 ```
// echo out the 3d transform value (distance from top for fixed arrows on timeline slide)
//window.alert(getTransform());
var viewportHalfHeight = $(window).innerHeight()/2;  // half the viewport height
var viewportHalfHeightInt = parseInt(viewportHalfHeight); // turn it into an integer
var initialOffset = parseInt(getTransform()); // get the offset from top to this slide
var initialOffset = -initialOffset; // turn the negative number positive
var fixedArrowOffset = initialOffset + viewportHalfHeightInt; // add the positive offset to the half window height

//window.alert (initialOffset); // uncomment for testing to see what you are getting back
 // set the css top declaration on our fixed position arrows
$('body.fp-viewing-s4-3 div.timeline-arrows .fixedArrowLeft').css('top', fixedArrowOffset); 

$('body.fp-viewing-s4-3 div.timeline-arrows .fixedArrowRight').css('top', fixedArrowOffset);

```

**Comment by RealMakAttak** [comment]
tduncan, i've run in to this problem again, I'll have a look at what you said and see what I can come up with, thanks
