### ISSUE TITLE
Fixed background not fixed in Chrome

### ISSUE THREAD

**Issue by fluxxus** [alvarotrigo/fullPage.js#208]
I have four sections, and they use background-attachment:fixed. It works in all browsers, except Chrome. In Chrome the backgrounds move, but I want them fixed.

Here is the link:
http://www.madebym.me/test/PoligateV2/

Is there any workaround for this?

**Comment by gasbb** [comment]
i have same issue... when i put inside the fullpage fixed attachment bg div it doesnt working in chrome

**Comment by Quaked** [comment]
How about allowing for translate rather than translate3d on said element? It's rather annoying having to use jquery animations instead of CSS just because I want one background attachment fixed. So is there a fix you can make instead? E.g. adding options so css3: true, css3d: false; or even css3d_sections: ['#section-1', '#section-2'] etc..

Thanks.

**Comment by alvarotrigo** [comment]
@Quaked translate3d is usually faster as it makes use of hardware acceleration. 

I would say that, this being [a Chrome bug](https://code.google.com/p/chromium/issues/detail?id=450265), it doesn't make much sense to try to provide a solution in fullpage.js when the problem is in the browser itself. 

Why don't you juse use `css3:false` instead? Probably the difference in performance won't be much with jQuery.

You can even use `scrollBar:true` and that will fix the problem.

**Comment by alvarotrigo** [comment]
To push a bit more Chrome guys just [star the issue](https://code.google.com/p/chromium/issues/detail?id=428376#makechanges).

**Comment by Quaked** [comment]
@alvarotrigo css3: false drastically decreases performance (mobile and desktop) and having to use it because one wants a single section background attachment as fixed is just sad. Sure it's a Chrome bug. And it's been there for quite some time without indication it'll get fixed any time soon. Meanwhile it's one of the most used browsers. I'd still prefer to have the control; I'd pick translate over jquery.animate() any day. Also that'd enable me to trigger GPU acceleration for specific sections as I see fit, either by calling translateZ(0) or translate3d() both of which should work.

Using jQuery as the fallback if "all else fails" is a good enough fallback and it should remains as such.

More options for zeh ppl! :)

**Comment by rietzschel** [comment]
I made a workaround for this issue. Not using css3:false because of the decrease in performance. Beside that it was difficult to match the easing of css3 with the easing of jQuery.

What i did:
A div before all divs: <div class="divclass">$nbsp;</div>
Css: 
.divclass { height: 100%;width: 100%;position: fixed;top: 0;left: 0;background-size: cover;z-index: -10;visibility: hidden;background-image: url(images/bgimage.jpg);	}
.divclass.view {visibility: visible;}

Then in the fullpage script (where the value of nextindex is the section offcourse, here 3):
onLeave: function(index, nextIndex, direction) {
var $divclass = $('.divclass');                
  if (nextIndex == 3 && direction === 'up') { $divclass.addClass('view' ); } 
  else if (nextIndex == 3 && direction === 'down') { $divclass.addClass('view' ); } 
},
afterLoad: function(anchorLink, index) {
var $media = $('.bg-media');
  if (index != 3) { $media.removeClass('view'); }
},	

That's it. Using fullpage callback and leaving the css3 as it is :-). Works for me.

**Comment by imjared** [comment]
Note for anyone coming here in the future that this issue is resolved upstream in Chrome
