### ISSUE TITLE
Android Chrome address bar

### ISSUE THREAD

**Issue by asdangus** [alvarotrigo/fullPage.js#2130]
please, is there a way to use fullPage.js on android chrome by hiding the address bar - either right after launch or after first scroll?

(fullscreen API is no the solution for me)

**Comment by alvarotrigo** [comment]
We as developers dont have control over the browsers' address bars.
So the answer is no. You can try different fullpage.js configurations such as not using anchors, or using `lockAnchors:true`, `autoScrolling:true`... etc, but the resulting behaviour will be different in different browsers and different versions of their browsers / os.

**Comment by tdquan** [comment]
@alvarotrigo that is not true. for a normal page, the address bar will disappear the moment the page is loaded or after the first scroll. However something in fullpage.js prevent this default behaviour. May be something with how it calculates the size of the viewport. I have the same problem and my site is displayed incorrectly and different from the simulator due to the fact that the screen is taken up by the address bar so some elements are pushed out of the page.

**Comment by alvarotrigo** [comment]
> @alvarotrigo that is not true.

What exactly is not true? :)

**Comment by tdquan** [comment]
> We as developers dont have control over the browsers' address bars.
This is not true to a certain extent. Clearly fullpage.js does some calculation that makes the browser calculate the viewport size in a way that makes the address bar to always show.

**Comment by alvarotrigo** [comment]
> This is not true to a certain extent. Clearly fullpage.js does some calculation that makes the browser calculate the viewport size in a way that makes the address bar to always show.

That's a side effect. There's no browser API that allows developers to deal with the browser top or bottom bars.

**Comment by tdquan** [comment]
Is there anyway around this? I saw in some discussion about a new merge using the innerHeight instead if height. Will this work?

**Comment by alvarotrigo** [comment]
Feel free make the changes and try it yourself. 
I haven't merged it and haven't checked it since my last test [here](https://github.com/alvarotrigo/fullPage.js/pull/1690).

Or, if you really need it and don't feel confident enough to make the changes yourself, feel free to [contract my services for a customization](http://alvarotrigo.com/#contact) of the library.

**Comment by tdquan** [comment]
Alright thanks a bunch :)

**Comment by asdangus** [comment]
even if you can trick the mobile browser, i'd feel insecure about complications anyhow.
i suggest another point of view - instead of fighting your limitation, make it your strength: you can give der mobile browser's bar your site's theme color like dis:

<meta name="theme-color" content="#f00f10">
<meta name="msapplication-navbutton-color" content="#f00f10">
<meta name="apple-mobile-web-app-status-bar-style" content="#f00f10">

cheers!

**Comment by asdangus** [comment]
Chrome, Firefox OS, Opera and Vivaldi: <meta name="theme-color" content="#f00f10">
Windows Phone: <meta name="msapplication-navbutton-color" content="#f00f10">
iOS Safari <meta name="apple-mobile-web-app-status-bar-style" content="#f00f10">

**Comment by asdangus** [comment]
sorry, not sure why Github is ommiting my code (am a noob)

Chrome, Firefox OS, Opera and Vivaldi: meta name="theme-color" content="#f00f10"
Windows Phone: meta name="msapplication-navbutton-color" content="#f00f10"
iOS Safari meta name="apple-mobile-web-app-status-bar-style" content="#f00f10"

**Comment by alvarotrigo** [comment]
> sorry, not sure why Github is ommiting my code (am a noob)

I've fixed it.

**Comment by alvarotrigo** [comment]
Interesting solution!

**Comment by webbycrown** [comment]
@alvarotrigo How you fix this issue?

**Comment by alvarotrigo** [comment]
@webbycrown nope. See my 1st answer. We lack control over it.
