### ISSUE TITLE
Pages are shifting when I scroll

### ISSUE THREAD

**Issue by sharonwelch** [alvarotrigo/fullPage.js#2152]
### Description
I have four sections and autoscroll is turned off. If I scroll down one section and then back up to the top section, the top section has shifted upwards so that everything in the top of the first section has been cut off. This happens each time I scroll up from a lower section.

### Link to isolated reproduction with no external CSS / JS
[in jsfiddle.net or codepen.io if possible, link to personal websites won't be reviewed unless isolated reproductions are provided. Reported issues without a reproduction might be closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the issue skeleton.

**Comment by nadeauco** [comment]
Having the same issue many years later

**Comment by alvarotrigo** [comment]
> Having the same issue many years later

And I'm having the same response after 5 years :)

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for reproduction.

[The demo page](https://alvarotrigo.com/fullPage/) (or any [example pages](https://github.com/alvarotrigo/fullPage.js/tree/master/examples)) works as expected so we'll need you to provide us a reproduction to find out if the issue is on your side or on fullpage.js itself, and in that case, under what conditions.
