### ISSUE TITLE
Section within a slide

### ISSUE THREAD

**Issue by jppag** [alvarotrigo/fullPage.js#218]
Hi Alvaro, 

I'm creating a project where I need to have a hidden content within each slide, that appears only when you click a "view more" link in the nav.

Is it possible to have nested sections and to trigger them when you click the "view more" link? Even if I create a navigation for each slide?

**Comment by alvarotrigo** [comment]
@jppag This is now possible using the [Interlocked Slides extension](http://alvarotrigo.com/fullPage/extensions/interlockedSlides.html) of fullpage.js.

The behaviour can be now emulated by using it combined with `setAllowScrolling` and `setKeyboardScrolling` in order to disable horizontal scrolling for any other level of slides rather than the first one.
