### ISSUE TITLE
Parallax only within a section

### ISSUE THREAD

**Issue by schnubor** [alvarotrigo/fullPage.js#2197]
Hi,

I've read the FAQ and a couple of kind of related issues, but I can't seem to find a feasible answer for the problem I'd like to solve. Heres what I'd like to do:

- imagine 3 sections.
- the first section is just a normal section. you scroll down to the next section using your mouse wheel.
- on the 2nd section if you keep scrolling instead of jumping to the 3rd section right away, you want to do some parallax/animation according to your scrollpos just within that section.
- as soon as you scroll to a certain threshold and your animation is finished you jump to section 3 and go back to fullpage.js "normal" scroll/jump behaviour to go to the next section.

I feel like I'd need `scrollBar: true` and potentially also `slideOverflow: true` for this but I don't really know how to combine those or how to use parallax just within one section and not the whole page. Any hints?

Cheers,
Christian

**Comment by alvarotrigo** [comment]
`scrollBar:true` won't help you here as it won't allow you to scroll inside the same section.
`scrollBar:true` would only help if you want to have parallax effects when moving between sections. This is, causing jumps from one to another section and stopping. Which seems it is not what you want in this case.

You can try it by using `scrollOverflow:true` for that parallax section. This way you'll be able to "scroll" inside the section and stop whenever you want.
scrollOverflow uses a forked and modified version of iScroll.js as detailed in the docs.
This means you should use iScroll.js in order to get the position of the scroll.

Unfortunatelly it seems the default iScroll.js doesn't provide such option and you'll have to go for the `iscroll-probe.js` version as detailed in [the custom events section of its docs](http://iscrolljs.com/#custom-events).

And I say unfortunatelly because this means you'll have to modify a single line I modified when forking iScroll.js. Check [this issue](https://github.com/cubiq/iscroll/issues/1041) to know which line I'm referring to.

Hope this helps!

**Comment by alvarotrigo** [comment]
There's now a [parallax extension](http://alvarotrigo.com/fullPage/extensions/parallax.html) to create parallax effects!
