### ISSUE TITLE
Unable to preventDefault inside passive event listener (...)

### ISSUE THREAD

**Issue by reddo** [alvarotrigo/fullPage.js#2362]
Getting the following error in chrome dev. tools while scrolling:

`Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080`

It's happening on the demo page.

Open the demo page, bring up chrome dev tools, set to responsive mode and select ipad as device and turn it to portrait mode and drag to next section.

See screenshot attached:
![screen shot 2016-10-26 at 16 13 38](https://cloud.githubusercontent.com/assets/1180060/19727301/824131f4-9b97-11e6-8a62-afab9f949063.png)

It looks like it's caused by the preventBouncing() function.

**Comment by alvarotrigo** [comment]
I'm not able to reproduce it in the [demo page](http://alvarotrigo.com/fullPage/#3rdPage).
Tested in the latest Chrome 53.0.2785.143 m for Windows and Mac.

What version of Chrome are you using? If you are using Canari, that's a developers version which can contain bugs and therefore support for it is not provided.

**Comment by reddo** [comment]
Chrome v. 54.0.2840.71 - latest stable. Have you set your renderer to tablet as in the screenshot?

**Comment by alvarotrigo** [comment]
Yeap, tried the responsive and the iPad view. No luck.
You can test it yourself in www.browserstack.com Mac and Windows.

**Comment by alvarotrigo** [comment]
I noticed on the Chrome dev tools, in the bar where the iPad device is selected. You have something next to the rotate icon saying "Mobile". 
I can't see that in my Chrome for Windows and neither in the ones in Browserstack.com.

**Comment by reddo** [comment]
That's not important, that's just a setting. Here's a video: https://drive.google.com/open?id=0B43KK3gJHYn4STNmTG5RZ1hHakU
Weirdly I couldn't reproduce in browserstack either. I'm running Mac OsX Sierra with latest chrome.

**Comment by alvarotrigo** [comment]
@reddo possible related with [this topic](https://github.com/WICG/EventListenerOptions/issues/54) and therefore with [this issue in Chrome issues tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=658847).

According to [Chrome docs](https://www.chromestatus.com/features/5093566007214080) events are treated as passive by default. In fact, this is why [this other fullPage.js issue ](https://github.com/alvarotrigo/fullPage.js/issues/2311) was raised.
It seems your Chrome is interpreting the event listener as passive. But clearly mine doesn't and anyone in Browserstack either.  I would say a default installing of Chrome wouldn't treat events by default as passive.

So the problem is clearly in Chrome.
Check out [this docs](https://docs.google.com/document/d/1II7oSIpd8pK91V5kEM3tDLKcIj398jOJn8Niqy6_loI/edit) and see how you can change the default behaviour of Chrome for passive events by accessing your chrome flags: `chrome://flags` and changing the property `
Passive Event Listener Override`.

**Comment by RByers** [comment]
What you're seeing is probably the result of an experiment @dtapuska ran on a tiny subset of Chrome users, sorry for the confusion, we know such experiments make the platform less [predictable](https://www.chromium.org/blink/platform-predictability)).

But we've decided to try [launching](https://www.chromestatus.com/features/5093566007214080) this [behavior](https://github.com/WICG/interventions/issues/35) to all users in Chrome 56.  So trying on current Chrome dev channel I see it reproduces reliably.  We're working on a blog post for this, but the short answer is to use the [touch-action CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) to indicate declaratively where you don't want scrolling to occur, and then avoid calling `preventDefault` when you see `TouchEvent.cancelable` is false (it's guaranteed to be a no-op).

**Comment by RByers** [comment]
Oh, I see the `fullpage` div already has `touch-action: none` (as is already required to work well on Edge) so really the warning is entirely noise in your case.  We'll [try to get that fixed in Chrome 56](https://bugs.chromium.org/p/chromium/issues/detail?id=667799).

**Comment by alvarotrigo** [comment]
@RByers thanks for the insight! Hopefully the change will be smooth for the fullPage.js!

**Comment by SulphurDioxide** [comment]
#3600

**Comment by enesyteam** [comment]
This will fix:
document.addEventListener( 'wheel', this.onMouseWheel, {passive: false} );

**Comment by vorasudh** [comment]
Is this problem solved? Because it seems default Chrome behaviour is to not allow passive event listeners

**Comment by alvarotrigo** [comment]
@vorasudh yeah it was solved, that's why the issue is not open anymore :)

You can test the [fullpage site](https://alvarotrigo.com/fullPage/) or any of the other examples online. You shouldn't get any error in the JS console.

Make sure to always use the latest fullpage.js version.
