### ISSUE TITLE
Fixed div with scroll is scrolling fullPage & trying to reuse iScroll from fullPage.

### ISSUE THREAD

**Issue by ImranBug** [alvarotrigo/fullPage.js#2399]
Hi, Thanks for all your work on this plugin.

I am trying to create a menu with fixed position but it will have it's own scroll but I am having 2 issues:
1) When scrolling the fixed menu div the scroll sections also scroll.
2) I cant find a way to reuse iScroll inside my menu div. It is showing a console error `Uncaught TypeError: this._init is not a function(…)`

[View Demo](https://jsfiddle.net/Imran_Bughio/yywgagv7/)

Any help would be much appreciated.

Thanks.

**Comment by alvarotrigo** [comment]
> When scrolling the fixed menu div the scroll sections also scroll.

Use the fullpage option `normalScrollElements` or if it is necessary the functions `setAllowScrolling` to turn off the scrolling when opening the menu.



> I cant find a way to reuse iScroll inside my menu div. It is showing a console error Uncaught TypeError: this._init is not a function(…)

You should probably be using the file in the vendors folder `scrolloverflow.min.js`. Which is a fork of iScroll.
But in any case, the problem is not in fullPage.js code and therefore it doesn't seem to be a fullPage.js issue.
