### ISSUE TITLE
iScroll issue when using its method scrollTo? 

### ISSUE THREAD

**Issue by santoshsunagar** [alvarotrigo/fullPage.js#2404]
Hi, we are using fullPage.js (2.8.6) and sections have an inside scroll i.e. each section has a scroll inside them. There is a requirement that when i click on one of the anchor tags, I should scroll to the top of the individual section. 
We tried to do it using iScroll method -  scrollTo(0,0). It goes to the top but as soon as any click or scroll takes place, the focus directly shifts to the bottom of the section.
Is there any way to do achieve this without the above issue?
Note : scrollOverflow option is set to true.

**Comment by alvarotrigo** [comment]
Please add an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

Also, try to use iScroll method without fullpage.js to do the same and see if you have the same results. It might be that the problem is in iScroll and not in fullPage.js.
fullPage.js doesn't deal directly with the scroll of the iScroll content.

**Comment by alvarotrigo** [comment]
- [ ] 
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
