### ISSUE TITLE
Touch doesn't work in Firefox 50

### ISSUE THREAD

**Issue by Voo2** [alvarotrigo/fullPage.js#2413]
### Description
Touch functionality doesn't work in Firefox 50. Maybe in Firefox 49, too. The last ff version I've successfully tested was version 48.

### Link to isolated reproduction with no external CSS / JS
Just take a look at the official [example page](http://alvarotrigo.com/fullPage/#firstPage).

### Steps to reproduce it
1. Open the example page with Firefox 50
2. Try to navigate by touch

### Versions 
Windows 10, Firefox 50, Microsoft Surface 3 Pro

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/1016
No solution was ever found.

**Comment by alvarotrigo** [comment]
As a side note, the problem might get solved in a future release due to a new feature I'm working on:
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Soon in fullpage a huge improvement! <a href="https://t.co/6vu1QTeKuY">pic.twitter.com/6vu1QTeKuY</a></p>&mdash; Álvaro Trigo (@IMAC2) <a href="https://twitter.com/IMAC2/status/796070516004192256">November 8, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
