### ISSUE TITLE
Not working with wow.js

### ISSUE THREAD

**Issue by darky02** [alvarotrigo/fullPage.js#249]
Hello! 
I'm trying to make fullpage work with wow.js (plugin that allows the launching of an animation only when the element is in view).

But, so far, I failed (also, my javascript knowledge is close to none).

One thing interesting is that, when i'm on the right section, if i resize, even a tiny little bit, my browser's window, then, the animation fires.

So i figure something can be done with the callback function, like actualising the window position or something,
but, as i said, i have no clue of the js functions that i could use.

Any idea would be great! :)
(this plugin is awesome by the way)

**Comment by shadat501** [comment]
Hi,
I Want to use your fullpage.js but if i use afterLoad or onLeave function it's good but i can not use wow js data-duration function.
Please help me.

**Comment by alvarotrigo** [comment]
@shadat501 as said in [fullPage.js FAQ](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions#index):

> fullPage.js doesn't actually scroll the site but it changes the top or translate3d property of the site. Only when using the fullPage.js option scrollBar:true or autoScrolling:false it will actually scroll the site in a way it is accessible for the scrollTop property.

**Comment by shadat501** [comment]
Thanks for your quick and friendly answer.

**Comment by magentapose** [comment]
Hi alvarotrigo,

I'm just getting started with fullPage.js and obviously have noticed that it won't work with wow.js out-the-box as fullPage doesn't use scrollTop.

I am interested in getting the elements on each horizontal slide to animate when the slide is changed. I am therefore trying to integrate the afterLoad function into my code to add the class 'go' to all elements with an 'animated' class in the slide. I've been playing around with afterLoad but I can't actually get it to work... it isn't adding the 'go' class to my elements. Perhaps I am using the anchorLink/index properties incorrectly? Does anchorLink refer to the section anchor or the horizontal slide anchor? I'm trying to animate the elements in individual slides, rather than in vertical sections.

Here is the code I am using, but it is not working:

afterLoad: function(anchorLink, index){
  var loadedSection = $(this);
  //using anchorLink
  if(anchorLink == 'slide2'){
    $('.animated').addClass('go');
  }
},


The class 'go' is not added. In fact, nothing I put in the function is executed. The anchorLink I'm specifying is the data-anchor property I have set for an individual horizontal slide.

Any help would be (very) gratefully received. Thank you!

**Comment by alvarotrigo** [comment]
fullpage.js provides now the option `scrollBar:true`. 
This way wow should work while we can maintain the auto scrolling of the site.

**Comment by mattyfew** [comment]
^^^^awesome thank you

**Comment by joeyaza** [comment]
I still cant get them working together, do I have to add anything else to my jq function other than....        $(document).ready(function() {
                $('#fullpage').fullpage({
                    scrollBar: true,
            });
        });

feel like im missing something, as firing the wow animations on the first section but onwards it isnt? (ie happening before I can scroll down..)

**Comment by alvarotrigo** [comment]
If you are using `scrollBar:true` then the problem you have is with wow.js and not with fullpage.js

**Comment by joeyaza** [comment]
thanks for the quick response :)

theres nothing other than adding wow to my classes to do though right ?
is 

$(document).ready(function() {
$('#fullpage').fullpage({
scrollBar: true,
});
});

syntactically correct ?

**Comment by alvarotrigo** [comment]
Also, make sure you initialise wow in the afterRender callback as detailed in the [fullpage.js FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions)

```javascript
$(document).ready(function() {
    $('#fullpage').fullpage({
        scrollBar: true,
        afterRender: function(){
              new WOW().init();
        }
    });
});
```

**Comment by joeyaza** [comment]
now it doesnt scroll at all :( :( :( :( this is so sad and its friday night

**Comment by alvarotrigo** [comment]
Unless you provide a reproduction in jsfiddle or codepen there's nothing we can do to help you.

**Comment by joeyaza** [comment]
https://jsfiddle.net/54rsmgpy/

is this of any help? for some reason its not bringing in the libraries/ frameworks though?

**Comment by alvarotrigo** [comment]
> for some reason its not bringing in the libraries/ frameworks though?

Then not helpful at all.

**Comment by joeyaza** [comment]
okay will do that in a second sorry not used jsfiddle before :(

**Comment by joeyaza** [comment]
https://jsfiddle.net/54rsmgpy/1/

is this slightly more helpful?

**Comment by alvarotrigo** [comment]
> is this slightly more helpful?

Just slightly. Where is wow.js I dont see you are importing it anywhere. 
How can I reproduce the problem you are having? Details it step by step.

**Comment by alvarotrigo** [comment]
Also, I didn't say use it in `afterLoad`, I said `afterRender`.

**Comment by joeyaza** [comment]
At the moment the wow.js isnt showing up even though I have used the cdn.

anyway so the issue is if I have 

    $(document).ready(function() {
            $('#fullpage').fullpage({
                scrollBar: true,
                }
            });
            new WOW().init();
        });

the wow animations work on the first section, as I then scroll to the second the animations do not show (as I guess they have already happened)..

if i use ..

    $(document).ready(function() {
            $('#fullpage').fullpage({
                scrollBar: true,
                afterRender: function(){
                 new WOW().init();
                }
            });
        });

I cannot scroll down from the 1st section .. so it is just stuck on the first fullpage.js page..

**Comment by alvarotrigo** [comment]
> At the moment the wow.js isnt showing up even though I have used the cdn.

You haven't include it in the external files in jsfiddle.
I'll wait for your reproduction to help you.

**Comment by joeyaza** [comment]
https://jsfiddle.net/54rsmgpy/3/

wow.js is in there on the left isnt it ?

**Comment by alvarotrigo** [comment]
> wow.js is in there on the left isnt it ?

Now it is, but it wasn't on the previous link you posted. 

Now the second part:

> How can I reproduce the problem you are having? Details it step by step.

**Comment by joeyaza** [comment]
At the moment the wow.js isnt showing up even though I have used the cdn.

anyway so the issue is if I have

$(document).ready(function() {
        $('#fullpage').fullpage({
            scrollBar: true,
            }
        });
        new WOW().init();
    });
the wow animations work on the first section, as I then scroll to the second the animations do not show (as I guess they have already happened)..

if i use ..

$(document).ready(function() {
        $('#fullpage').fullpage({
            scrollBar: true,
            afterRender: function(){
             new WOW().init();
            }
        });
    });
I cannot scroll down from the 1st section .. so it is just stuck on the first fullpage.js page..

**Comment by joeyaza** [comment]
maybe that is not too helpful as its not showing on the jsfiddle

**Comment by alvarotrigo** [comment]
Sorry can't help you without a reproduction in jsfiddle or codepen.

**Comment by joeyaza** [comment]
okay will give it a try in codepen

**Comment by joeyaza** [comment]
thanks sorry this is taking ages

**Comment by joeyaza** [comment]
just to confirm I fixed with afterRender, was just a silly syntax error in jquery, sorry about that :D

**Comment by faliqaiman** [comment]
@joeyaza can you share the reproduction code here? thanks..

**Comment by kkorushkin** [comment]
$(document).ready(function() {
$('#fullpage').fullpage({
scrollBar: true,
});
})
and then simply: body {overflow: hidden!important;}

**Comment by kkorushkin** [comment]
that solution working for me
