### ISSUE TITLE
Horizontal scroll of sections

### ISSUE THREAD

**Issue by codytooker** [alvarotrigo/fullPage.js#2521]
I would like my sections to scroll horizontally. Is this possible? I know that the slide options exist within a section. I however would like the scroll wheel to navigate to the next section but behave like a slide in that it scrolling up and down makes sections slide left and right.

**Comment by alvarotrigo** [comment]
Check the option `scrollHorizontally` and [the extension Scroll Horizontally](http://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html)

**Comment by cgmultimedia** [comment]
Hi Alvaro,

I'd like a clarification on your answer to Cody's question above. From what is says on the description, the extension provides "horizontal scroll within sliders" — which is not what Cody asked, or what I would like to know. Will that extension make it so horizontal scrolling is available in the SECTIONS, not just the slides?

**Comment by cgmultimedia** [comment]
I should also add what I'm trying to achieve is a site that is ALL horizontally-scrolling. I realize I might be able to do that using slides rather than sections, but before I dive into changing a lot of code I've already written (before I discovered your plugin, unfortunately!), it would be good to know if there's a disadvantage to using the slides vs the sections.

**Comment by alvarotrigo** [comment]
> Will that extension make it so horizontal scrolling is available in the SECTIONS, not just the slides?

It is easier if you just check [the demo link I posted](http://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html) and you see it by yourself :) 

> but before I dive into changing a lot of code I've already written (before I discovered your plugin, unfortunately!), it would be good to know if there's a disadvantage to using the slides vs the sections.

Not really. You can check the docs for any doubt you have as well as any examples and try to see if you discover anything you don't like of them.

**Comment by cgmultimedia** [comment]
Hi Alvaro,

thanks for your reply. The demo link you posted confirms that only the slides go horizontally, not sections. I suppose that might be okay except the URLs that are generated are less than ideal — http://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html#firstPage/2 — I think I'd prefer if it didn't have anchor AND the second level ("/2") in the address.

I guess a related question would be if that slide address ("/2" etc.) can be an ID/anchor (i.e. "#registration" or something like that) instead of just a number.

And just to confirm, all this requires purchasing the Scroll Horizontally extension, correct?

Thanks again,
Carlos

**Comment by alvarotrigo** [comment]
> I guess a related question would be if that slide address ("/2" etc.) can be an ID/anchor (i.e. "#registration" or something like that) instead of just a number.

Sure. It's detailed in the docs. Use `data-anchor` attributes.

> And just to confirm, all this requires purchasing the Scroll Horizontally extension, correct?

Yeap.

**Comment by alvarotrigo** [comment]
> I think I'd prefer if it didn't have anchor AND the second level ("/2") in the address.

That's not possible I'm afraid.

**Comment by cgmultimedia** [comment]
Sorry, one more question, is it possible to make the slides NOT loop or rewind after the last slide? Can it just stop?

**Comment by alvarotrigo** [comment]
Yeah. It is as well detailed in the docs. Read it there.

**Comment by cgmultimedia** [comment]
Thanks for all your help! I will do some testing to see if it will work for me. Have a great weekend.
