### ISSUE TITLE
Autoplay video/audio stops when a section is firing fitToSection 

### ISSUE THREAD

**Issue by johnvanhulsen** [alvarotrigo/fullPage.js#2526]
### Description
On a page with full-width/height video's in fullpage.js and scrollbars enabled in config; in most times, the video will stop after hiding scrollbars (autosetting in OSX) in Firefox 50 and 51.

### Link to isolated reproduction with no external CSS / JS
http://jsfiddle.net/97tbk/1694/

### Steps to reproduce it
1. Scroll down
2. Wait until scrollbar dissapear
3. Video stop...

### Versions 
Firefox 50 and FIrefox 51 on OSX (Sierra) with scrollbars hiding after a second or something.

**Comment by alvarotrigo** [comment]
Your issue is in `.js-section` which is setting an height of 500px making it bigger than the viewport in jsiddle,. 
Then, fullPage.js tries to adjust itself using `fitToSection` what is causing the issue.

If you use `fitToSection:false` or just remove the `min-height` property from the `.js-section` style you'll solve the issue. 

In any case, I'll keep it open as an issue with `fitToSection` with the pausing of a video.

**Comment by bengaochuan** [comment]
First of all, thank you for creating this super awesome plugin! 
I encounter the same issue as well. On your example page, just add `autoScrolling: false` and `fitToSection: true`, the video will stop playing.

**Comment by alvarotrigo** [comment]
Fixed in the dev branch 2.9.4. Will get merged soon in the next release.

**Comment by alvarotrigo** [comment]
Fixed in the latest release 2.9.4
