### ISSUE TITLE
Slide item auto height

### ISSUE THREAD

**Issue by WCLab** [alvarotrigo/fullPage.js#2598]
Hi Alvaro, i recently used your plugin.

I have a slide into section, the first item has an image and a lot of text, second has a list of images. In mobile, the second slide has more content (taller with inner height) and the first has a lot of white space under content.

I hope i was specific.

An example of that is in http://testcloug.gq/gastro

It's possible to change parent height (section element) fit to slide item?

Regards

**Comment by alvarotrigo** [comment]
You have a few options:

- Use [the responsive slides extension](http://alvarotrigo.com/fullPage/extensions/responsive-slides.html) to turn slides into sections on responsive.
- Use `scrollOverflow:true` in your slide with long content.

**Comment by WCLab** [comment]
Thanks Alvaro.

I don't like `scrollOverflow:true` behavior  because i have scrollbar enabled. The second option is great, but is not considered by administration project to pay for plugins unfortunately.

I'll make it with css waiting for good behavior.

Thanks, regards!

**Comment by Paperweb** [comment]
Hi there. 

I'm having the same issue, where when using `fp-auto-height-responsive` on my sections, slides with less content than others of the same section get a lot of white space below them.

I cannot use the responsive slide extension because of the site concept which has to keep its structure.

I was first using `scrollOverflow : true` (and I still am for the desktop version), but it is a bit unstable on mobile, so I recently switched to `fp-auto-height-responsive`.

Would there be any other way to move to the next section or stopping the scroll when getting to the end of the short slides' content? 
@fdorantesm, did you figure a way to go around that issue?
