### ISSUE TITLE
Vertical align not working on a few specific viewport heights. 

### ISSUE THREAD

**Issue by pim013** [alvarotrigo/fullPage.js#2628]
### Description

On a few viewport heights, the content stops being vertically aligned in the middle. This happens at 868px. Not at 869px (it jumps back being vertically aligned in the middle) but then it happens again at 870px height. I did not make any adjustments in the core code and didn't apply more CSS classes. 

### Link to isolated reproduction with no external CSS / JS
You can see our staging website here. It happens on the second slide. 
Besides fullPage.js and an extension of it, scrolloverflowJS, jQuery and jQuery Rotate are loaded.  

[http://wespire.nl/klanten/floriaan/djbus/#section/about](url)

### Versions 
Chrome Version 56.0.2924.87 (64-bit)
macOS Sierra 10.12.3

Although this problem isn't a dealbreaker, I thought it was interesting enough to share to see what we can do about it.

**Comment by alvarotrigo** [comment]
Well, that's clearly not an isolated reproduction :) Lot of external JS and CSS to fullPage.js.

I can only say that this is happening because you are using `scrollOverflow:true` and somehow fullPage.js believes it needs to create an internal scrolling for your slide. 
I can see how it is indeed necessary in [the 3rd slide of the section](http://wespire.nl/klanten/floriaan/djbus/#section/clients) on 1040px width. Avoid that, and you'll probably solve your issue. 

You are probably doing something funny with your CSS styles in the 1st slide and making fullPage.js believe it needs scrollbar.
