### ISSUE TITLE
pure javascript version maintenance 

### ISSUE THREAD

**Issue by soenkekluth** [alvarotrigo/fullPage.js#2697]
is the[ pure javascript version](https://github.com/alvarotrigo/fullPage.js/tree/master/pure%20javascript%20(Alpha)) beeing maintained?

if not i would love to contribute. best thing would be if you had a list of features / fixes of the jquery version that should to be ported to pure js.

what do you say?

**Comment by alvarotrigo** [comment]
Hey @soenkekluth! 
It is not maintained at the moment so if you want to contribute that'd be great! 

Ideally it should have the same features as the jQuery version. The jQuery version kept being updated after the pure javascript version was created in March 2015. 
So almost all the new features and bug fixes in fullPage.js since version 2.6.2 were never implemented in the javascript version.

You can see a change log of fullPage.js versions [here](https://github.com/alvarotrigo/fullPage.js/releases?after=2.6.7), which can server as a "to do" list for this task.

**Comment by soenkekluth** [comment]
@alvarotrigo  perfect! thanks - ok i will see what i can do!

**Comment by alvarotrigo** [comment]
Now fullpage.js v3 got rid of the jquery dependency!
jQuery is no longer necessary!

**Comment by MishUshakov** [comment]
@alvarotrigo excited for jquery-less vue version!

**Comment by alvarotrigo** [comment]
@MishUshakov that will come out soon too!
