### ISSUE TITLE
Is it possible to use the menu for selected sections only?

### ISSUE THREAD

**Issue by assaf244** [alvarotrigo/fullPage.js#2721]
let's say i have those section
- Intro
- Process step 1
- Process step 2
- Process step 3
- Summary

i want to keep the process step flexible, one day i'll have 3, the next day i can have 5 etc.
and i want my meny to display links to the intro, the first step and the summary,
i want to display those sections only - without using their index - cause it can change

any suggestions?

**Comment by alvarotrigo** [comment]
> any suggestions?

Create your own menu and instead of using the `menu` option make use of the [fullpage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) to set the active state for the element when you require it.

You have examples of callbacks usage in the docs and in the examples folder.

The state class is quite straight forward, but feel free to check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M).
