### ISSUE TITLE
OverflowSroll white space on mobile

### ISSUE THREAD

**Issue by TylerOlthuizen** [alvarotrigo/fullPage.js#2910]
Hello,
I am using overflowscroll:true; in my project for oversized sections. When I am on mobile and I am pressing pulling the screen down to get back to the first section, the scrollable transform becomes negative and pulls the section down leaving an ugly white bar. I know I can solve this by adding a color on the section but I would rather not to do. Any ideas how I can make it not apply a negative transform value?

![unnamed](https://user-images.githubusercontent.com/10456029/30706363-4ca14274-9eb5-11e7-841a-b67c572613e5.jpg)

http://96.30.9.8/~wildpine/ (website in dev);

Thanks,

Tyler

**Comment by alvarotrigo** [comment]
Just apply the background to the section and not to the content of the section.

Otherwise, take a look at [iScroll docs](http://iscrolljs.com/) to see if you find any option that can be configured to avoid the easing behaviour. Then you can pass them through the fullpage.js option `scrollOverflowOptions`.
