### ISSUE TITLE
fp-auto-height not scrolling

### ISSUE THREAD

**Issue by prakashdesai77770** [alvarotrigo/fullPage.js#2925]
i am trying to ue fp-auto-height for last section which is bigger than screen, but is unable to scroll by mouse wheel, can be scrollable by scroll bar 

![download](https://user-images.githubusercontent.com/25239305/31173366-d41da002-a924-11e7-85ab-06c0f8689bb6.png)

**Comment by alvarotrigo** [comment]
`fp-auto-height` is usually used to deal with sections that are smaller than the viewport.
If you want to use it for a bigger section then you'll have to use it in responsive mode or using `autoScrolling:false`.

Otherwise you'll have to go for the `scrollOverflow`al option that is designed to deal with bigger content than the viewport at the same time that it maintains the autoScrolling to another sections.
Check [the example online](https://alvarotrigo.com/fullPage/examples/scrolling.html).
