### ISSUE TITLE
scrolling to section is delayed by video loading in Safari (mobile)

### ISSUE THREAD

**Issue by QSSRobert** [alvarotrigo/fullPage.js#2959]
A client's site I'm working on has a html 5 video embedded in it. Part of the navigation of this site includes a link directly to a fullpage.js section on the same page as the video (www.example.com/#sectionID). Unfortunately it seems the call to scrollToAnchor isn't made until the document's readyState is 'complete', and this doesn't happen in Safari until a certain amount of the video data is loaded; which can take a fair amount of time on a mobile connection.

The result being that going to the anchor link URL will load the fullpage page at the top and pause until it downloads 'enough' video data, and it finally scrolls down to the correct section (5-10 seconds).

(unfortunately I can't host a large video file somewhere to reproduce this in jsfiddle. And as it's a navigation bug I'm not sure if it would even work. I can't link the client's production site directly for obvious reasons)

I've edited the javascript to call scrollToAnchor on $(document).ready() instead of document.readyState === 'complete' on line 564, which removes the delay, but means that fullpage.js incorrectly calculates the height of each section (because all the content hasn't loaded yet). If the user manually scrolls a section the correct heights are recalculated.

Honestly I'm not sure how you could fix this, but I thought I'd post this issue here to save others some googling. If you've got any suggestions I'd appreciate it. It's a difficult bug to explain to a non-technical client...

### Steps to reproduce it
1. Include a moderately sized <video> element on the page will fullpage.js
2. Add anchors to the sections
3. Navigate directly to one of the sections using mobile Safari on a non-wifi connection (from a separate page)
4. the correct page will open then pause for a number of seconds before scrolling to the correct section

### Versions 
(mobile) Safari 10, Safari 11

**Comment by alvarotrigo** [comment]
I would suggest you to add the video using jQuery / Javascript on the `afterRender` callback. 
I guess this should fix the issue you are having. Or even using [lazy load](https://github.com/alvarotrigo/fullPage.js#lazy-loading) for it.

You could even do it outside fullPage.js initialization if you want. I guess as long as it is an asynchronous call it should be fine.
You could even use a simple `setTimeout` to add it. 

The reason fullPage.js waits for the page to be loaded is because it needs to calculate the size of each section based on its content, which can be images, videos etc. And those many times do no have a pre-defined size, so we have to wait for them to load to know what to do.

**Comment by alvarotrigo** [comment]
Definetely modifying the core code is not the best idea, as you won't be able to update to newer versions or you'll always have to modify the code before doing so. 
Also, if you ever plan to use [fullPage.js extensions](https://alvarotrigo.com/fullPage/extensions/) that won't be that easy.
