### ISSUE TITLE
White Line When Using With Bootstrap

### ISSUE THREAD

**Issue by ngoctran271** [alvarotrigo/fullPage.js#2968]
My website have a white line when scroll. If i set width of container bootstrap:auto white line is hidden. 
Demo:(1920 x 1080)
http://khowebsites.com/htmldemo/fifaevent/

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by SuperSebbe** [comment]
I have the same issue. Since I just registered my account on github, I am not quite sure how I should post my code. But here´s a link to a google doc with my index.html code. 

https://docs.google.com/document/d/1h_PTmUEX3G5VvizInSx8MAYQNaqUuXTpa4sbgXObzpE/edit?usp=sharing

I apologize for any grammar, spelling, etc. mistakes since English is not my mother tongue.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
