### ISSUE TITLE
Vertical and horizontal scrolling with extension

### ISSUE THREAD

**Issue by michalbehal** [alvarotrigo/fullPage.js#3027]
### Description
Hi, I need to have both scrolling effects on same page. Only vertical for mobiles (for screen width 800px and lower) and horizontal for everything else. Can I somehow manage it in one html file without collide IDs? I have one div for pc and one div for mobile, where is everything, so I'm switching between them.

 I bought scroll horizontally extension and I tried to test it on http://neugraf.laceup.cz/test.html, but I can't manage it to work. I have no idea how to make the slider work, your example content still redirecting itself. And after that, I don't know how to manage to work both together.

### Link to isolated reproduction with no external CSS / JS
[Removed link]

### Versions 
Mozilla Firefox 57.0 (64-bit), Windows 10 Home, Acer aspire E 15

**Comment by alvarotrigo** [comment]
See your JS console:

> fullPage: fullpage.js extensions require jquery.fullpage.extensions.min.js file instead of the usual jquery.fullpage.js. Requested: scrollHorizontally

And read carefully [how to use fullPage.js extensions](https://github.com/alvarotrigo/fullPage.js#use-extensions).

That should solve the problem you have using the extension.
Regarding how to use only horizontal scrolling or only vertical, you can make use of the [Responsive Slides extension](https://alvarotrigo.com/fullPage/extensions/responsive-slides.html) in order to convert all horizontal slides into vertical ones on responsive. This way you'll only have vertical scrolling, but notice you'll lose the autoScrolling behaviour as it will scroll normally without snapping. 

If you want to keep using the autoScrolling behaviour, then I would recommend you to change the HTML markup on responsive and then destroy and initialize fullpage.js again.
