### ISSUE TITLE
Slideshow Autoplay and ScrollOverflow conflict?

### ISSUE THREAD

**Issue by jberg1** [alvarotrigo/fullPage.js#3032]
Hello, I'm having an issue with combining the Slideshow Autoplay and the ScrollOverflow features (scrollOverflow used on other sections than the slideshow).
This setup is working fine for the autoplay.
```javascript
afterRender: function () {
   setInterval(function () {
   $.fn.fullpage.moveSlideRight();
   }, 4000);
}
```

My issue comes up when I'm using in combination with ScrollOverflow and resize the browser window (or minimize/maximize). After resizing window the slideshow autoplay starts to go very fast and ignores my intervals until I reload. This happens in Firefox, Chrome and IE.  When I remove the scrolloverflow.min.js from being loaded then the autoplay works fine after resizing window. But now I have no scrollOverflow on the other sections.  Any thoughts or a work around?

Thanks for your help.
This script is Awesome!

**Comment by alvarotrigo** [comment]
That's a bug! Got it solved now on the dev branch!
It was firing the `afterRender` callback on resize when using scrollOverflow.

In order to solve it please make sure to use the [latest version of the scrolloverflow file. (0.0.4)](https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.js)

**Comment by jberg1** [comment]
You Rock Álvaro!
That works perfect now. Thanks for the quick resolution.
