### ISSUE TITLE
how to deal with sections with slide downs

### ISSUE THREAD

**Issue by evgeniy85** [alvarotrigo/fullPage.js#3033]
Hello, thanks for the great plugin.
I am using scrolloverflow: true;
```
$('#fullpage').fullpage({
          anchors: [...],
          scrollOverflow: true,
          fitToSection: true,
          scrollingSpeed: 700,
          bigSectionsDestination: 'top',         
        });
```
It works good, but I have a question, one of my sections has slider which expands when user click on the show more button, it shows even more than section itself. By default the section is fit the screen and doesn't add scroll to it, but section is expanded is not possible to read expanded information it goes to next section when scroll.

How can I add scrolling to that section? or how to force scrolling not leave the section until all new information was scrolled?

Thanks,
Eugene.

**Comment by alvarotrigo** [comment]
You need to use `$.fn.fullpage.reBuild` after you change the content of that section, so the scrollbar can get updated with the new content. Read more about it [on the docs](https://github.com/alvarotrigo/fullPage.js#rebuild).

**Comment by amityweb** [comment]
after you change the content of that section,

**Comment by amityweb** [comment]
@evgeniy85 did you manage to fix this? I think I have the same issue. 

@alvarotrigo What do you mean by this in relation to this issue? "_after you change the content of that section" -> in my case I am not changing the content of the section, its all output using PHP to the screen, then no dynamic changes. 

I have a grid style (display: grid) of items which click to pop up the slide show. It all works, EXCEPT there are more items that can fit on the screen. I have set scrollOverflow: true which works on all other sections that the content is higher than the view, but on this slide section it does not work. I cannot slide down to view the items that do not fit on the screen. It jumps to the next section. 

If I remove the <div class="slide">'s then scrollOverflow: true works on the items. 

Its as if fullpage.js is working out its height using the slide heights, not the height of all the visible items.

**Comment by evgeniy85** [comment]
@amityweb in my case I had a problem because my section had slide down section, and I had something like this
 $(id).slideDown('fast');
$.fn.fullpage.reBuild();
and it didn't work, but when I changed to
 $(id).slideDown('fast',function(){
  $.fn.fullpage.reBuild();
 })
it works fine.

**Comment by amityweb** [comment]
Ok thanks. We have some slides which we want to hide but then show on click of the thumbnails (layed out in grid), and then we use grid layouts for thumbnails of the slides. Its been a nightmare using fullpage with it, I dont think its very good for more advanced layouts. In the end I had to not use the fullpage slide support because the thumbnails were not being used to decide how the big screen was, I think the slides were, and the thumbnail grid was bigger than the slide, so being cut off. We took the slider outside of #fullpage and used JQuery Cycle, so fullpage then started to use the grid thumbnails for the page size correct.

**Comment by alvarotrigo** [comment]
@amityweb if you believe it is a bug, please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Then open a new issue.

**Comment by amityweb** [comment]
I doubt its a bug per se. Its a conflict. Its just in my experience fullpage.js does not play well with other things going on on the page 

A jsfiddle example will not be able to reproduce whats going on with other things all conflicting together. I'd need to build the whole site in jsfiddle, can that even be done? You need to start looking at peoples websites to see whats going on.

**Comment by alvarotrigo** [comment]
> I'd need to build the whole site in jsfiddle, can that even be done? You need to start looking at peoples websites to see whats going on.

I'm not asking you to reproduce your site in jsfiddle. I'm asking you to reproduce the issue, which is a different thing. 
In any case, you don't need to use jsfiddle or codepen. I'm happy taking a look at your hosted page as long as it is an isolated reproduction with no external code to fullPage.js.

Why is that? Because I am not a free consulting agency :) I am not here to fix your website, but to fix fullPage.js related issues. As long as you can prove the issue is in fullpage.js and not in your own code (which many times is), I'm can't afford myself to lose time checking webspages and navigating through the minified / combined / hidden code or trying to figure out where you are over writing CSS values, or where you are initialising fullPage.js etc. 

Make it easy for me to help. Because I can't solve everybody's issues for free.

**Comment by amityweb** [comment]
Issues can often be conflicts between systems though. Its easy to say its not a bug because it works "on its own". But mostly people will have other things going on that could conflict, or they want to do a custom solution that goes beyond the documentation. Often people are not interested whether its a bug or not, but are just looking for some help to resolve the issue. As you developed fullpage you are probably the best person to take a look and see whats going on and advise. It could be some simple CSS that fixes the issue, but I dont know how fullpage works. 

I never said anything about free either. I think its fine for you to offer paid support if its not a bug and helping people out. Dont assume everyone only wants free here, some of us are professional developers getting paid by customers to build their site, or in this case fix an issue on a site, so would be OK to pay if its reasonable. It would have saved me days if its something you could spot and know about. Maybe you have experience in the exact issue I have.  

My main issue is the request to create it an isolated or jsfiddle area rather than just send a link to you to take a look at. If its conflicts with other plugins, then then the entire site needs to be looked at, not a small section of code.

**Comment by alvarotrigo** [comment]
@amityweb fair enough. I indeed provide payed support sometimes to people who contact me personally. But of course, that depends on the kind of issue, and I'll always charge a non-refundable amount. 

If you need personal support for the next time, just [contact me](https://alvarotrigo.com/#contact) and I'll let you know if I'm interested on it.

**Comment by amityweb** [comment]
Great, thank you. I am to get back onto the project shortly because we just cant get sliders to work how we want.
