### ISSUE TITLE
Please update pure javascript version

### ISSUE THREAD

**Issue by trsh** [alvarotrigo/fullPage.js#3060]
It's 1 year not touched and missing some features?

**Comment by trsh** [comment]
Mostly I miss "destroy" command

**Comment by alvarotrigo** [comment]
The Javascript version was never a final version. 
I stopped working on it time ago due to lack of interest from developers. So I kept improving the jQuery one and left the Javascript version in Alpha version. 

I might continue working on it in a future depending on the interest from developers, but right now, it is no longer maintained I'm afraid.

**Comment by alvarotrigo** [comment]
I will open a quiz in [Twitter](http://twitter.com/imac2) / Newsletter / Website in a month or so. Depending on the answer, I might start working on it this year or treat it as a low priority task.

**Comment by trsh** [comment]
@alvarotrigo clear! Btw- would hardly recommend it, as JQuery, with new modern JavaScript is becoming more and more obsolete. It's just a bunch of KB for nothing.

**Comment by alvarotrigo** [comment]
@trsh yeap, you are right, but it requires a big investment of my time, not only to move the library but also all the extension. I need to know if it is worth the effort and if people really ask for it. So far I didn't get many people who asked for it.

> It's just a bunch of KB for nothing.

Well, I would argue it is not "for nothing" when I need to provide full support for old browsers and specially to IE 8 and 9. 
It clearly makes things much easier in many scenarios.
