### ISSUE TITLE
Vanilla JS

### ISSUE THREAD

**Issue by rogeriorioli** [alvarotrigo/fullPage.js#3089]
this is work whitout jquery ?
label : Question

**Comment by alvarotrigo** [comment]
No. fullPage.js is jQuery plugin.
You could use the [vanilla version of it](https://github.com/alvarotrigo/fullPage.js/tree/master/pure%20javascript%20(Alpha)), but it is not up to date and won't have many features, such as extensions or many other options/methods.

**Comment by rogeriorioli** [comment]
Thanx a lot ! great project  <3

**Comment by julmot** [comment]
@alvarotrigo Is this still the case? Is vanilla JavaScript still not recommended?

**Comment by alvarotrigo** [comment]
Since version 3, fullPage.js doesn't require jQuery anymore, therefore being pure vanilla JS.
None of the extensions requieres jQuery as long as you got them after the 1st of July.

If you were using fading effect for version 2, then you'll have to acquire the extension again for version 3. You had 50% discount for 20 days as was detailed in the emails sent to every developer who purchased any extension. Unfortunately that's over now.
