### ISSUE TITLE
Double advance on "hard" swipe

### ISSUE THREAD

**Issue by theraccoonbear** [alvarotrigo/fullPage.js#310]
We're seeing an issue (confirmed by testing on the fullPage.js demo page) where a "hard" swipe (big/long/aggressive) on both a MacBook Pro touchpad and on an Apple Magic Mouse causes a double advance through sections.

With a hard swipe the section will advance and land on the next, stop briefly, and then advance to the next section.

**Comment by d4nyll** [comment]
@alvarotrigo I've done some [research](http://blog.danyll.com/lethargy-tackling-inertial-scroll/) on this and it's not because of "jQuery believes the user still scrolling when they are not...", it's because the trackpad and Apple Magic Mouse emits scroll events long after the user has finished scrolling.

**Comment by alvarotrigo** [comment]
@d4nyll yeah I agree. Basically its the kinetic scrolling that keeps firing scrolling events because of its inertia.

**Comment by alvarotrigo** [comment]
I forgot to mention, this issue was solved time ago. Fullpage.js doesn't scroll twice anymore with hard swipes. It is able to detect deceleration (inertia) and prevent the scrolling.
