### ISSUE TITLE
add section by changing class name on mobile 

### ISSUE THREAD

**Issue by ilmatty** [alvarotrigo/fullPage.js#3116]
I'm trying to do this layout:  have 2 sections with split screen (by div) one side text and other side image. When I turn to mobile phone I need to change the layout removing the split screen, so 4 section fullscreen one below the other (text-image-text-image). Like this:

![1](https://user-images.githubusercontent.com/24493880/36454363-dbecde26-169b-11e8-99dd-3fc4c126b5af.jpg)

i tried with js and jquery to change the class name of div to increase sections, and then reload fullpage.js, but it works only with 2 sections and me don't know why.

**Comment by alvarotrigo** [comment]
You'll have to destroy and initialise fullpage.js again. You'll have to do it with `destroy('all')`function.

But I would recommend you to use the [Responsive Slides extension](https://alvarotrigo.com/fullPage/extensions/responsive-slides.html). It won't Convert it exactly as you want, because it will maintain the original order, but well, close enough and much easier :)

You'll have section 2.1 as Section 3 and Section 2.2 as Section 4.
