### ISSUE TITLE
设置水平滚动时 页面中间会发生抖动的现象

### ISSUE THREAD

**Issue by potatoesji** [alvarotrigo/fullPage.js#3160]
### 相关代码如下
```html
<div class="slide">
    <div class="sd-tj">
        <div class="sd-page" id="depth_big_1" cpt="component_4_3" tool="Dwnews5slider" style="position: relative;"><img data-id="431750" src="20180320/4e3156b3a4932f389b71e85d346b371c_w.jpg"></div>
        </div>
    </div>
</div>
```

**Comment by alvarotrigo** [comment]
哪个水平选项？
`scrollHorizontally:true`? `loopHorizontal:true` ? `continuousHorizontal:true`?

**Comment by alvarotrigo** [comment]
请提供一个单独的问题的复制链接。 没有外部CSS或JS代码或文件到fullPage.js和最小的HTML可能。

如果可能的话。 你能用英文写作吗？:)
我在网上使用了一个翻译网站，我相信它并不完美。

**Comment by alvarotrigo** [comment]
我会解决这个问题，因为我没有回复你，所以我不明白你的问题。

**Comment by alvarotrigo** [comment]
I don't know, because you didn't answer my previous question and therefore I don't know what is your problem.

Which fullpage.js initialisation are you using?
Could you please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.
