### ISSUE TITLE
How to scroll over iframe

### ISSUE THREAD

**Issue by VictorChen** [alvarotrigo/fullPage.js#3206]
### Description
Scrolling while hovering over the iframe doesn't actually scroll the page.

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/ens43v4o/17/

### Steps to reproduce it
1. Scroll down to second section
2. Hover mouse over the iframe content
3. Scroll up/down (doesn't work)

### Working example (without fullpage.js)
https://jsfiddle.net/gjxxugfs/3/

---

The default behavior without fullpage.js works (can scroll while hovering over iframe). This makes me think that fullpage.js is doing something that's preventing it from working. Is there **ANY** way I can temporary turn off fullpage.js's scroll hijacking so that this example will still work?

**Comment by webdevyaros** [comment]
@SergProduction @VictorChen 
Try my solution: https://jsfiddle.net/th0LxLbv/2/ - seems it works.

**Comment by alvarotrigo** [comment]
@webdevyaros no it doesn't? http://jsfiddle.net/q884Lv0a/26/

**Comment by AmanSahota** [comment]
Hey Guys, simply use the <video> tag and direct urls from vimeo or youtube.. works perfect.

**Comment by T7team** [comment]
I found solution by JavaScript

[https://codepen.io/t7team/pen/KOPqqV](https://codepen.io/t7team/pen/KOPqqV)

**Comment by kirkbross** [comment]
> I found solution by JavaScript
> 
> https://codepen.io/t7team/pen/KOPqqV

Dead link. What was your solution?

**Comment by kirkbross** [comment]
@alvarotrigo!  GavinsBro! Is there a solution to maintain page scrolling (mouse wheel) over iframes, like embedded 3rd party forms?

**Comment by kirkbross** [comment]
The issue with @webdevyaros' solution is that you can't click anything under the .wrapper::after CSS pseudo element. I have a form in my iframe so it needs to be clickable **and** fp scrollable.

**Comment by alvarotrigo** [comment]
@kirkbross if it needs to be scrollable, then how are you suppose to decide if you want to scroll your iframe or the whole page?

**Comment by mhndra96** [comment]
I'm sorry, I try to answer though it's late, and It's just for sharing. But, when I look the hood of pagePiling JS, which is maybe nearly same to FullPage, I change the `container` to `window` and `document` at the `addEventListener` line. The issue is still the same, can't activate the `wheel` event over the `iframe`, but it can activate the `wheel` event when the pointer is over the other element (the menu and the bullet). But, i don't know what the bug is existed when changing the `container` to `window` and `document` . You can see the simplified wheel event tab example in my codepen https://codepen.io/Mhndrakhrisna96/pen/KKQjpjB. Thanks..

**Comment by alvarotrigo** [comment]
@mhndra96 iframes won't bubble up the scroll or touch events. It's a different Window context that fullPage.js can't control. 
So, unfortunately, there's not much we can do there.
