### ISSUE TITLE
Slide not working at first section

### ISSUE THREAD

**Issue by tkoutso** [alvarotrigo/fullPage.js#3232]
Hello, congratulations for your app. It helped me a lot.

However I have an issue at a webpage: When I insert class slide to a div found at second section, everything works fine. However when I insert it at the first section everything gets ruined. Any ideas?

I give the code for the slider to be at second section:

```
<!DOCTYPE html>
<html>

<body>	
  <header>
    <nav>
	<ul id="menu">
	  <li data-menuanchor="welcome" id="m0"><a href="#firstPage">first</a></li>
	  <li data-menuanchor="biography" id="m1"><a href="#secondPage">second</a></li>	
	</ul>	
    </nav>
  </header>

<main>

  <div id="wrapper">

   <div class="section" id="ch0" data-anchor="firstPage">
   </div>

   <div class="section" id="ch1" data-anchor="secondPage">
   
    <div class="box">
      <div class="slide"></div>
      <div class="slide"></div>
    </div>
</main>
     
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.js"></script>
<script type="text/javascript" src="plugins/jquery.fullPage.js"></script>
        
<script>
$(document).ready(function() {
	$('#wrapper').fullpage({
		menu: '#menu',
		anchors:['firstPage', 'secondPage',],
		navigation: false,
		loopHorizontal: false,
	});
});
</script> 

</body>
</html>
```

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by JasonHeyburgh** [comment]
I have just had a similar issue but I figured out the issue, so thought I would leave it here in case anyone else runs into a similar problem. 

When initializing fullpage.js I normally leave my first anchor empty so that the homepage url isn't appended with the anchor. When adding slides to my first page the controls did not work, upon investigating I realized that this issue was being caused by the empty anchor. 

@alvarotrigo would you consider this a bug? I'd assume most people would leave this blank.. or maybe it's just me :)

**Comment by alvarotrigo** [comment]
> @alvarotrigo would you consider this a bug? I'd assume most people would leave this blank.. or maybe it's just me :)

Anchors are set for all sections or for none. You can't just leave one section without anchor because otherwise fullpage won't know where you are exactly. 
On page load the 1st section never appends the anchor, only when you go back to it. So, when there's no anchor, fullpage assumes you just landed on the page.
