### ISSUE TITLE
vue Switching routing error

### ISSUE THREAD

**Issue by fanchaot** [alvarotrigo/fullPage.js#3379]
I use fullpage.js in VUE to report a route jump:   [Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'removeEventListener' of undefined"      On the mobile side

**Comment by alvarotrigo** [comment]
The issue is already being treated on the vue-fullpage.js issues forum:
https://github.com/alvarotrigo/vue-fullpage.js/issues/44

It was marked as "pending reproduction" and I was not able to reproduce the issue on my own.
Please provide an reproduction of it in CodePen (https://codepen.io/alvarotrigo/pen/zpQmwq) or on CodeSandbox
