### ISSUE TITLE
Problem with white space

### ISSUE THREAD

**Issue by Ryzlane** [alvarotrigo/fullPage.js#3383]
Hello,

I'm experiencing trouble with the white space on my application using fullPage.js (with React, maybe it is important to precise it). I have quite a lot of input and in all of those which require typing, the white space does not work..

I was surprise to not find anyone experiencing the same problem on the Internet but well. Can you help me with that? Thanks a lot, really enjoying the package otherwise!

**Comment by alvarotrigo** [comment]
I can not reproduce it:
https://jsfiddle.net/alvarotrigo/ea17skjr/8/

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

If you are using the [official fullpage.js component for React](https://alvarotrigo.com/react-fullpage/) please open an issue on [its github issues forum](https://github.com/alvarotrigo/react-fullpage).

**Comment by eribertocaria** [comment]
Hello,
I have the same problem, in the input and textarea it doesn't leave blank spaces. You can see it in this page http://alicantecls.pixelarte.com/contacta/

I have tried to reproduce it in Jsfiddle and Codepen, but the bug is not present. However, if you try it in the file simple.php in the examples folder, it crashes.

I hope you can help me.

Best regards 
Eriberto Caria

**Comment by eribertocaria** [comment]
Hi, I have not been able to download version 4.0.9, but with version 4.0.8 I have been able to fix it.
Thanks
