### ISSUE TITLE
Horizontal Navigation Dots are not Active

### ISSUE THREAD

**Issue by JanisOppliger** [alvarotrigo/fullPage.js#3385]
Hello,
First Fullpage.js is super and it helps me for my Projects. Thanks.
My Problem: i added Horizontal Navigation Dots  but they are not Active. They are only active on Hover and Click. 
How can i make them stay active on the actual Slide?

I have isolated my problem here:
https://www.autour.ch/Soul-Riders/Test1.9.5/

**Versions**
all Browser
i‘m working with a Mac in Visual Studio code2
FullPage 3.0.2

**Comment by ervandra** [comment]
Hi @JanisOppliger , indeed fullPage.js is very powerful and awesome.

To help answering you, I've created a pen to replicate the issue.
* I suppose you're using slides and not the sections for the horizontal slides.
* And slides have their own navigation using `slidesNavigation: true` option.

Please take a look here: https://codepen.io/vahnisme/full/EeKwZa

Please let us know if you've solve this issue, otherwise we'll look around to help you with.

**Comment by JanisOppliger** [comment]
@ervandra Thanks a lot, it‘s working.
i knew it has to be something very simple...

**Comment by alvarotrigo** [comment]
@ervandra thanks for that answer ;)
