### ISSUE TITLE
Scroll not working.

### ISSUE THREAD

**Issue by Hetashah2498** [alvarotrigo/fullPage.js#3387]
### Description
Hi Alvaro,
Thank you for this is nice plugin and it is totally working fine in desktop site even it is working food in mobile responsive of browser but when i open this site in mobile scroll of nav bar is not working. actually i used custom nav bar and in mobile site menu is open from right side and scroll of menu is not working. even i make custom navigation with some images so in landscape mode there is also scroll issue in navigation too.
i used this demo
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/scrollOverflow.html
and put options same like that and add scrolloverflow js too.
i checked all issues related to my problem but not getting any solution. i tried with different options but not getting any idea even menu option is also not working so help me out from this.

Any help would be much appreciated! Thank you!

**Comment by ervandra** [comment]
Hi @Hetashah2498 , i'm trying to help by creating this pen: https://codepen.io/ervandra/pen/dqXWOM

* My assumption is that you're trying to create a menu (custom nav bar you're mention), and the nav bar will be an fixed element, that will be shown / stay across the sections.
* But then, you cannot scroll inside your navbar, the scroll from fullPage kept intercepted user's scroll on the navbar and change the sections (moving up / down)

My quick solution for your issue might be:
* You might not need the `scrollOverflow: true` options, since this option only applied to the section if the content within is bigger than the height / container, so you can scroll inside the section to see the complete content.
* you might need a `fixedElements: '.someClass, #someID'` and setup your fixed elements with css styles. apply the maximum width/height and set the css `overflow:auto` as you need, then the element (in your  case the nav bar) will have their own scrollbar, without getting intercepted by the fullpage.js as it was defined as `fixedElements` above.

Please let me know if your case was resolved :)

**Comment by Hetashah2498** [comment]
Hello @ervandra 
Thank you for your quick reply.

* But i am strugglng with scroll of menu in mobile phone in which i open taht navbar from right side and then in landscap 
menu scroll is not working. i tried it with removing fullpage js code so it is working fine so how can i scroll that  menu in landscap.
 
* Even same thing i made custom navigation bar so even scroll is not working in #fp-nav.  I tried it with normalScrollElements so it scroll some of the time.

Please let me know what i can do in this. Thank you!

**Comment by ervandra** [comment]
Yes @Hetashah2498 ,

My opinion for your case:
* you need to isolate the navbar (with fixedElements, and position:fixed / absolute, as well as its z-index
* any element's scroll behaviour might intercepted / disabled by the fullPage if those elements is contained inside the sections, you need to get them out, use the first solution above.
* other possibility is you can change your layout structure to made the element isolation possible.

Again, i've made the demo for you: https://codepen.io/ervandra/pen/mGEBER
* you can check on the left navbar, when you scroll on it, the fullpage also triggered and moving up/down
* on the right navbar (navbar2), we add into the `normalScrollElements: '#navbar2'` options, so the scroll happened on the element wont be intercepted by the fullpage scrolling event.

Its quite tricky to made this working, and other people might have their own solution for this case, my example just one of them :)

**Comment by Hetashah2498** [comment]
Thank You @ervandra 
yeah it is little bit tricky to do that.
i already tried what you said but still it did not work for me.

**Comment by alvarotrigo** [comment]
@Hetashah2498 try using `normalScrollElements` for your menu element.

**Comment by alvarotrigo** [comment]
Difficult to say without a reproduction. It would be nice to be able to see exactly what you mean by using an isolated reproduction on jsfiddle or codepen.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
