### ISSUE TITLE
I'm not able to make my html animate. I'm using animate.css. Also, Using "index == 1 && direction ==" unable auto-scrolling mode. 

### ISSUE THREAD

**Issue by amanbalooni** [alvarotrigo/fullPage.js#3394]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
You might need to use `scrollBar:true` or `autoScrolling:false` as detailed in the [fullPage.js FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions)

Otherwise, just make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.

**Comment by amanbalooni** [comment]
Please Tell me how can I reveal animation when I scroll. I'm trying my ass off but couldn't achieve. 
I'm using Animate.css. But all animations loads at the same time. Please help me out with this. 
And thank you very much for your previous reply.

**Comment by alvarotrigo** [comment]
I already provided you all you need to know.
If you require further assistance you can contract my support services. [contact me](https://alvarotrigo.com/#contact) for more info.
