### ISSUE TITLE
Create a beforeLeave event

### ISSUE THREAD

**Issue by NinoFloris** [alvarotrigo/fullPage.js#340]
Sometimes you want to cancel the leave or change some elements before the scroll starts.

At the moment I have to change your code to be able to cancel a specific scroll. Because you strip all the touchhandlers before adding your own, this way mine can never be the first handlers and therefore never succesfully do event.stopImmediatePropagation() without your handlers having already started the scroll animation.

The usecase for this by the way is when you have a few pages, starting on the second. Continuousvertical on. And then being able to scroll to the first but not back to the last pages, this is then only possible when going down to the last page and then you come back to the top page. So basically a kind of loopBottom without the jump effect.

(Same guy as ellos btw, yay for multiple accounts...)

**Comment by alxbrg** [comment]
I’ve been trying to add animations before the scroll starts, and I guess that's why most people might want a 'beforeLeave' event. There's a very simple workaround that I thought might be useful to share: simply add a timeout to perfomMovement within the scrollPage function: 
	`setTimeout(function(){performMovement(v);}, 400);`
That creates a lag though, i.e. if you scroll or press keys rapidly, things get messy. Fixed this by temporary disabling KeyboardScrolling until sections are fully loaded: 
	`FP.setKeyboardScrolling(false); setTimeout(function(){FP.setKeyboardScrolling(true);}, 1400);`
(--still within the scrollPage function)
Same logic for scrolling, replacing 'canScroll=true’  in the afterSectionLoads function by:
            `canScroll = false; setTimeout(function(){canScroll = true;}, 400);`
Gives a behavior similar to this: https://cloudmagic.com/ or this: http://torchbrowser.com/
It means users can’t bolt through sections by scrolling, but I guess that’s why god made nav-dots and anchor links :)

By the way, this is a truly amazing plugin, I’ll make sure to make a donation. Cheers!

**Comment by alvarotrigo** [comment]
@alxbrg you might want to take a look at this pull request: https://github.com/alvarotrigo/fullPage.js/pull/1194 it hasn't been reviewed yet. But you can give it a try.

**Comment by alxbrg** [comment]
I missed this. Thanks, I'll look into it!

**Comment by alvarotrigo** [comment]
A new functionality has been introduced in fullPage.js 2.6.6 that provides a way to cancel a move before it takes place.

It can be done by using the callbacks `onLeave` and `onSlideLeave` and returning `false` as specified [in the docs](https://github.com/alvarotrigo/fullPage.js#cancelling-the-scroll-before-it-takes-place).

**Comment by Diargon345** [comment]
And how to use it? I read the documentation. It says only how to stop the action. How to renew? I tried this:
onLeave (index, nextIndex, direction){
 var $info_panel = $('.info_panel');
	var $el2 = $('.el2');
            if(index == 1){ 
                return false;
			$info_panel.removeClass('slide_panel');
            $el2.removeClass('slide_content');
                return true;
            }
    }

**Comment by alvarotrigo** [comment]
To disable it, you return false. Otherwise it will scroll normally. 
You might want to use javascript callbacks to return true if you make some action,  your code doesn´t make sense with two returns.

You'd better ask for javascript question in other place such as stackoverflow.com
