### ISSUE TITLE
Calling destroy on second time is not working

### ISSUE THREAD

**Issue by senthil-wd** [alvarotrigo/fullPage.js#3438]
I would like to integrate this text effect plugin - http://michalsnik.github.io/aos/ after section scrolled.
On 'afterLoad' I do destroy('all') so the text effect appearing then initialize the fullpage extension again, but again when afterLoad callback gets fired the destroy('all') should not work. 
Please refer https://jsfiddle.net/f4m7v3ao/

**Comment by alvarotrigo** [comment]
Just use `scrollBar:true` or `autoScrolling:false` so you can function as normal.

Otherwise, make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.

**Comment by senthil-wd** [comment]
Thank you for the suggestion.
On <afterLoad> I set <false> for <autoScrolling>so the text in with effect and after 5 seconds of time I set <true> for <autoScrolling>, when it is enabling the text are out. Actually the text should be there after the effect. Please help me to fix this.
