### ISSUE TITLE
Activation not working

### ISSUE THREAD

**Issue by adamf321** [alvarotrigo/fullPage.js#3443]
### Description
We activated our scrollOverflowReset and Parallax plugins against the domain pemex.com. However, the red warning is still showing when the site is hosted at http://www.pemex.com/negocio/gasolineras/nuestros-productos/Aditec/files/index.html

Currently it is private, client does not want to launch until the issue is fixed.

Any ideas what we could be doing wrong? Eg does the site need to be public for it to work?

### Link to isolated reproduction with no external CSS / JS
Can't, client won't allow it to be public unfortunately.

### Steps to reproduce it
1. ActivateI licesnes against pemex.com
2. Add activation keys to JS object:

```
parallaxKey: '--key--',
scrollOverflowResetKey: '--KEY--'
```

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Just make sure to read [how to use extensions](https://github.com/alvarotrigo/fullPage.js#use-extensions) and [how to activate fullpage extensions](https://github.com/alvarotrigo/fullPage.js/wiki/How-to-activate-a-fullPage.js-extension)

Notice the difference between activation key and license key. 

Also, notice you'll have to use another file instead of the usual fullpage.js.
