### ISSUE TITLE
onleave problem when change slide

### ISSUE THREAD

**Issue by reverter** [alvarotrigo/fullPage.js#3444]
hi,

I have problems with the "onLeave" function.

this is my code:

```
<script type="text/javascript">
            var myFullpage = new fullpage('#fullpage', {
                menu: '#menu',
                anchors: ['marameo','pizzeria','ristorante','gelati','servizi'],
                autoScrolling: true ,
                navigationPosition: 'right',
                scrollOverflow: true, 
                licenseKey: 'OPEN-SOURCE-GPLV3-LICENSE',
                onLeave: function(index, nextIndex, direction)
                            {           
                            var leavingSection = $(this);
                            if(index == 2 && direction == 'down'){
                            alert("Going to section 3!");
                            $( ".logo2 img" ).replaceWith( "<img src='img/assets/titoli/titoli_gelato.svg'>" );
                            }
                            }
            });
        </script>
```

I use the last version of your script.

when I go to the next page, my logo does not change. I had already used this feature on other web pages and I never had problems.

can you help me?
Thanks in advance

**Comment by alvarotrigo** [comment]
As you can see on the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js), you are using the old signature for fullpage.js callbacks. 

Use the option `v2compatible` and set it to `true` if you want to keep using the old way of using callbacks.

I see also you are using the open source license. Is your whole project and website open sourced? Otherwise you would be violating the license terms unless you purchase a license for your site. More info here: https://alvarotrigo.com/fullPage/pricing/
