### ISSUE TITLE
Dom and styles always load first before fullpage initializes

### ISSUE THREAD

**Issue by saket-wdev** [alvarotrigo/fullPage.js#3597]
Hi there,
When i hit the refresh, I see flashes of the dom and sidebar w/o fullpage styles.
I have tried all the possible solutions -

1. put native js and fullpage js in the head tag
2. initialize fullpage in document.ready function 
3. set height to 100% on all sections 

Please look at the codepen here:
https://codepen.io/saket-wdev/pen/EMoBZY

As you can see, when one hits refresh, the section heading is seen on the top for a second and then fullpage css is applied.  This happens almost every time.

Please reply the solution to this problem

**Comment by alvarotrigo** [comment]
That's because you are relying on fullpage.js to center the content vertically by using the default option `verticalCentered:true`.

You can fix it by applying fullpage.js class `fp-table` in each of your sections and adding a wrapper around your sections' content with the class `fp-tableCell`.

Like this:

```html
<div class="section fp-table">
    <div class="fp-tableCell">
             <h1>My content</h1>
    </div>
</div>

**Comment by saket-wdev** [comment]
Thank you for the quick reply.
Actually centering content is not the concern here. Its just a demo that showcase the problem of fullpage.js getting initialized after the dom and styles have loaded.

As you may see on fullpage.js homepage as well. When you hit refresh, one can see the sidebar for a moment and then fullpage initializes, and gets rid of the sidebar. 

So, is there a way that when ever I refresh, fullpage.js initialize first and I only get to see the styles applied by fullpage first and not dom and personal styles.

**Comment by alvarotrigo** [comment]
> As you may see on fullpage.js homepage as well. When you hit refresh, one can see the scrollbar for a moment and then fullpage initializes, and gets rid of the scrollbar.

Yeap, that's like that by design.
Bare in mind that some people will want to use fullpage.js with scroll bar, and that depends on the JS initialisation :)

> So, is there a way that when ever I refresh, fullpage.js initialize first and I only get to see the styles applied by fullpage first and not dom and personal styles.

I'm not quite sure what you mean.
If you don't want to see the styles before fullpage.js loads, place the stylesheet after the JS file in the closing body.

**Comment by alvarotrigo** [comment]
If you just want to hide the scroll bar, do it yourself in your styles:

```css
html,body{
overflow:hidden;
}
```
