### ISSUE TITLE
Cancel a move

### ISSUE THREAD

**Issue by leemul** [alvarotrigo/fullPage.js#364]
Hi,

Would it be possible to cancel the slide moving to the next slide at all.

For example, I have large form split by slides, and i'd like to validate the fields before allowing them to click the navigation arrows.

I've got the validation working fine, it fires on 'onSlideLeave', would it be possible to send an args.cancel(); or similar to prevent the page moving on?

Thanks

**Comment by Vitalij-Petras** [comment]
Not working for me! Can you please make function for stop moving slides? It would be realy usefull.

For example I have web page for desktop, where in mobile devices I create some slides in these section, so I would love to (if scroll down) to first scroll throw the sections and then scroll to another section. 

Or before leave function. These 2 things are just missing in this plugin. Fullpage is awasome, but just because of that 2 things i need to search to alternative. Your bad.

**Comment by alvarotrigo** [comment]
Good luck with it.

**Comment by dademaru** [comment]
Hi alvarotrigo,
thanks for your awesome plugin.
I need to hide a text in the first slide of each section before sliding to the next slide.
I'm using onSlideLeave callback, hiding the text with CSS3 transform and returning false to stop sliding to next slide.
But I need to re-enable sliding to next slide when the animation has ended.
I've tried:
`$('.text_to_hide').one('webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend', function(){
      //animation is over
     $.fn.fullpage.moveSlideRight();
});`
inside the onSlideLeave callback, but it doesn't slide right.

Is there a way to re-enable the move after it's canceled returning false?
Thanks again
Davide

**Comment by alvarotrigo** [comment]
@dademaru just call `moveSectionDown` or `moveSectionUp`

**Comment by dademaru** [comment]
@alvarotrigo 
Hi,
I also tried (from your snippet above):
```
$('.section').find('.fp-controlArrow').on('click', function(e){
	if(!$('body').hasClass('text-is-hidden')){
		e.stopPropagation();
		$('body').addClass('text-is-hidden');
	}
});
```
and worked as expected, but only for click event (I have to do the same for key move).
But with onSlideLeave + moveSectionDown it's simpler and works perfectly (although I wrongly thought it would have moved the section down!).
Thanks!!
