### ISSUE TITLE
Seo issues

### ISSUE THREAD

**Issue by webmaster-Seenk** [alvarotrigo/fullPage.js#3687]
Hi,

All seems to be good with the use of fullpage.js expected the SEO. Maybe my bad but i don't know why.
The Google search console tell me that each slides can't be indexable even if they are on the sitemap.txt.
I also add the css visibility: hidden; for each slides so that google can't see the content.

Do I have to create a new page for each slides ?

Best regards

**Comment by alvarotrigo** [comment]
Google will index your whole page. That means, it will consider all sections and slides are in the same page. That's because anchors (#) in the URL are not considered different pages. 

You can test this yourself by googling some text of the [main fullpage.js page](https://alvarotrigo.com/fullPage/). For example, we can search in google "It includes tens of examples, great documentation and both community and personal support", which is a text in the 3rd section.

You'll see how Google finds the page and displays it in the 1st result. 

> I also add the css visibility: hidden; for each slides so that google can't see the content.

Why don't you want it to see the content? I though you wanted Google to be able to index them?

If you are asking how to index sections/slides separatelly, that's not possible at the moment. 
Related with this issue https://github.com/alvarotrigo/fullPage.js/issues/2131

**Comment by webmaster-Seenk** [comment]
Yes i want Google to index all slides. And i Prefer to index the first slide in the home page, that is why i am using css visibility:hidden.
I will create a new page for each slide only for google indexation.

Thanks
