### ISSUE TITLE
Modal scroll not working

### ISSUE THREAD

**Issue by forpenguinonly** [alvarotrigo/fullPage.js#3706]
Hi,

I am currently having problem on scrolling my modal when there is too many contents in my modal.

I tried with code below:

> $('#myModal2').on('shown.bs.modal', function () {
   $.fn.fullpage.setAllowScrolling(false);
   $.fn.fullpage.setKeyboardScrolling(false);
});

AND

>normalScrollElements: '.modal .modal-open',

but somehow it just doesn't work on my script. Is there anyone can help me with this? I really appreciate your help!

Thanks in advance!

Regards, 
Jasmine

**Comment by alvarotrigo** [comment]
That should work.
Otherwise, can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by forpenguinonly** [comment]
Hi @alvarotrigo, 
Thanks for your speedy reply. I think I know what happened to the scroll. It's because of the way I display my images. 
I can't display image from local file. I have to upload all the images somewhere to get it display. I found out when I tried it on jsfiddle, it works fine in both jsfiddle and codepen but not on local.

**Comment by alvarotrigo** [comment]
Glad you figured that out!
I'll close the issue then :)
