### ISSUE TITLE
circular slider issue

### ISSUE THREAD

**Issue by laleet11** [alvarotrigo/fullPage.js#3721]
sir, I got an issue on full page.js. I need a continuous horizontal slider in a circular loop.
I have used continuous horizontal: true this is not working,
I had referred all the solutions in these links 
and other solutions from this link Continuous horizontal slider · Issue #124 · []( alvarotrigo/fullPage.js)

but I can't solve this issue.

**Comment by alvarotrigo** [comment]
> I have used continuous horizontal: true this is not working,

It works perfectly in the [demo online](https://alvarotrigo.com/fullPage/extensions/continuous-horizontal.html). 

Did you purchase the continuous horizontal extension from the [fullpage.js extensions](https://alvarotrigo.com/fullPage/extensions/) page?

**Comment by laleet11** [comment]
no, i have not purchased it yet.

**Comment by alvarotrigo** [comment]
You'll need to purchase it in order to try it. As detailed in the  [fullPage.js extensions FAQs](https://alvarotrigo.com/fullPage/extensions/faqs.html) that's he only way.

Then you are entitled to a 30 days refund if you do not generate any activation key or ask for support as detailed in the license terms.
