### ISSUE TITLE
Clarity of documentation regarding ScrollOverflow: true

### ISSUE THREAD

**Issue by clselin** [alvarotrigo/fullPage.js#3752]
### Description

Sorry, this isn't exactly a bug, but I just wanted to make a comment and request clarity in the docs. Please feel free to close if this is not helpful or if I'm re-asking something. 

I'm encountering issues with using ScrollOverflow: true in that certain sections of my page won't trigger the scroll to the next section with the mousewheel when the section's overflowed content is scrolled to the bottom. The page gets 'stuck' and the only way to scroll to the next section is to use keyboard arrows or click on a navigation element. 

I've googled related issues, for example, https://github.com/alvarotrigo/fullPage.js/issues/2172 and https://github.com/alvarotrigo/fullPage.js/issues/2071

Supposedly this issue is closed and resolved in the plugin, and people who have encountered if have resolved it with comments like "Oh I had some trouble with margins" and 'adding overflow:hidden to fp-scroller should do it." (In my case fp-scroller having overflow:hidden doesn't resolve it, sadly).  

So my assumption is this is a CSS issue where the existence of margins within my sections is causing some problem with the calculation of their height, which impacts the ability of the scrolloverflow feature to determine when to scroll to the next section. 

However the documentation around scrollOverflow doesn't indicate any best practices, dos/don'ts around what kind of css formatting is valid inside sections to avoid this issue 

My request would be for some clarity on how to avoid this issue, eg. Children of the main scrolling section should or should not contain this, that, or the other. 

I'm not necessarily after any troubleshooting of my individual problem, but further information about best practices for formatting sections when using scrollOverflow would be a wonderful addition to the docs.

**Comment by alvarotrigo** [comment]
The solution for #2071 was fixed by [this commit](https://github.com/alvarotrigo/fullPage.js/commit/6f8e2978035997dc4034842c1fc7e2d3a466332a). So there's no dark magic there :)

And regarding #2172, chances are he was using an old version of fullPage.js when he opened the issue, as he opened just a few days after the release that fixed #2071.

So, having said this, it is yet possible that there's an issue on that regard, so can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by clselin** [comment]
Thanks, I will try to make time to do an isolated reproduction soon.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
