### ISSUE TITLE
How to disable & re-enable fullPage using responsive plugin?

### ISSUE THREAD

**Issue by thedesigncore** [alvarotrigo/fullPage.js#3768]
I want to disable fullPage on screens smaller than 768px which I was able to accomplish by purchasing the responsive extension and adding the following to my script:

```js
responsiveWidth: 768,
afterResponsive: function(isResponsive){
    if (isResponsive == true) {
        fullpage_api.destroy('all');
    }
}
```

How can I re-enable fullPage once the screen width goes above 768?

**Comment by alvarotrigo** [comment]
You can just initialise it again:

```js
       new fullPage('#fullpage', {
             scrollingSpeed: 700
       });
```

You can wrap that in a function and call it whenever you do:

```js
function initFullpage(){
       new fullPage('#fullpage', {
             afterResponsive: function(isResponsive){
                 if (isResponsive == true) {
                     fullpage_api.destroy('all');
                }else{
                      initFullpage();
                }
             }
       });
}

//on page load
initFullPage();
```

But I would recommend you rather than destroying fullPage.js to just use the `responsiveWidth` option combined with the `fp-auto-height-responsive` class so sections can be bigger than the viewport if required.

fullPage.js should't bother you that way :)

**Comment by NPanayotov** [comment]
In this case, he'll get:

> FullPage: Fullpage.js can only be initialized once and you are doing it multiple times!

Because you're trying to re-init the plugin.

I want to do the same thing in my special case. 

Could you please advise how we can use destroy and then re-init when we prefer?
