### ISSUE TITLE
Overlapping Issue

### ISSUE THREAD

**Issue by Tuseef** [alvarotrigo/fullPage.js#3843]
### Overlapping Issue

when i'm scrolling my page sections are overlapping and sometime 3rd or 4th section load directly!!!
or sometime header #menu hide automatically.

**Comment by alvarotrigo** [comment]
The demo page and the tends of examples on the examples folder work as expected.

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by Tuseef** [comment]
http://tct.brawaa.com/hm/gms-html/

**Comment by alvarotrigo** [comment]
> http://tct.brawaa.com/hm/gms-html/

That's not an isolated reproduction. 
Try to reproduce it in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Otherwise, use your own site but remove all external CSS / JS files and code external to fullPage.js.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
