### ISSUE TITLE
Navigation labels don't hide when changing section - mobile

### ISSUE THREAD

**Issue by ika-codes** [alvarotrigo/fullPage.js#3857]
### Description
Active labels on navigation on mobile don't deactivate when swiping down or up to another section.

### Link to isolated reproduction with no external CSS / JS
Happens everywhere, even on demo pages:
https://alvarotrigo.com/fullPage
https://alvarotrigo.com/fullPage/examples/navigationV.html

### Screen
![screen_fullpagejs](https://user-images.githubusercontent.com/32020954/72146653-3036c800-339d-11ea-82aa-bd7625536e87.png)

### Steps to reproduce it
1. Click on any of the navigation points on the right. The active view will change to that section, and the label of that section will be visible next to the dot.
2. Swipe down to another section. The dot of the previous section is still visible with its label. The dot of the current section is also active, but without label.

### Versions 
Checked on Android 9 Pie
Was able to replicate it in Chrome dev tools for any mobile (on Windows)

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 👍 
We'll take a look at it!

**Comment by alvarotrigo** [comment]
You can force them to become visible by using the fullPage.js option `showActiveTooltip: true`.
On mobile however the behaviour is different in the example you mention because when you click on the navigation bullet the brower triggers the "hover" css state. Then, it stays like that unless you click somewhere else. This is a common problem on mobile devices that doesn't really have a proper solution.

I'll close this issue and remove the bug tag as it is not really a fullpage.js bug :)
