### ISSUE TITLE
Elementor: Sections not fitting screen  - Horizontal sections with inner sections

### ISSUE THREAD

**Issue by gjwjr** [alvarotrigo/fullPage.js#3933]
Hi,

Fullpage sections are working fine if they are single sections. When they have an inner section nested inside to allow for horizontal scrolling, there is an issue with the section not fitting the screen properly which then effects sections below...see screenshots. You can see  on the white section, the text is not centered, this is because it is overflowing below the screen.

Thanks

<img width="1440" alt="Screenshot 2020-03-21 at 12 06 16" src="https://user-images.githubusercontent.com/54316792/77219892-99407600-6b6c-11ea-8d83-b389466f1488.png">
<img width="1440" alt="Screenshot 2020-03-21 at 12 06 24" src="https://user-images.githubusercontent.com/54316792/77219895-a3fb0b00-6b6c-11ea-9135-21942683441a.png">

**Comment by gjwjr** [comment]
Here is the URL - https://daisy.garywestjr.com/portfolio/dj-snake/

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
However we only provide support for the Elementor plugin through the [contact form](https://alvarotrigo.com/#contact).

Can you please fill it to get your support? Thanks.
I'll procede to close the issue here. This forum is only to treat the fullPage.js JavaScript library issues.
