### ISSUE TITLE
inner scroll using scrolloverflow:true glicht on mobile with long swipes

### ISSUE THREAD

**Issue by tomlillo** [alvarotrigo/fullPage.js#4025]
im using a simple fullpage code like on this page: https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html . And this sample page has the same issue.

On mobile Iphones devices when I scroll inside the slide, it behaves strangely when I reach the end. it glicht

### Versions 
[ ios 13 , safari ]

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
Yeah, I'm aware of the issue and I started noticing it a few months ago, perhaps because of the new version of the browser? Not sure.

I'll mark it as bug, but do not expect a quick fix this time, the issue seems to be inside the vendor component iScroll.js which is noto maintained anymore by its author, so kinda tricky getting into it.

**Comment by williharder** [comment]
Setting `bounce` to `false` in the scrollOverflowOptions solved for me the glitchy and jumpy behaviour.

**Comment by alvarotrigo** [comment]
@williharder awesome! Thanks for the info! 👍  
I'll look into it and if it solves it I'll use this option by default!!

**Comment by yann2-0** [comment]
Hello, I have one last concern that I still have to adjust fullpage works however on my smartphone my scrollable divs (fp-scroller) if I scroll too fast there is an unpleasant jump I do not see how to adjust it? I think it comes from a touch event because on a browser in simulation no problem. here is the link to try on a smartphone please
https://yann2-0.github.io/yann.github.io/mon_site/index.html#firstPage

**Comment by alvarotrigo** [comment]
@yann2-0 try using what @williharder suggested.

**Comment by yann2-0** [comment]
yes!!! it's ok thank you

**Comment by alvarotrigo** [comment]
This issue seems that no longer exist in neither Safari, Chrome or Firefox. 
I'll close this issue for now.
