### ISSUE TITLE
ScrollHorizontally extension problem

### ISSUE THREAD

**Issue by Nolweyn** [alvarotrigo/fullPage.js#4026]
### Trying to make ScrollHorizontally work with the activated key I received + fullpage.js commercial license key. I don't think that I'm missing any files / links / scripts, I can send my html file if needed.

###https://codepen.io/clo-schorderet/pen/VwaLYYa

### Steps to reproduce it
1. Bought 1 Commercial Hobby License, + 1 license key for ScrollHorizontally extension, activated it.
2. Following the steps from https://github.com/alvarotrigo/fullPage.js/blob/master/README.md#options
3. Might be an error somewhere else in the code, I can't find it :( .
<img width="744" alt="Capture d’écran 2020-08-08 à 18 56 38" src="https://user-images.githubusercontent.com/69396042/89715840-f4062d00-d9a8-11ea-95d7-5ee58bcf9389.png">
<img width="705" alt="Capture d’écran 2020-08-08 à 18 56 46" src="https://user-images.githubusercontent.com/69396042/89715843-f799b400-d9a8-11ea-9c49-c73cd65ccb63.png">
<img width="731" alt="Capture d’écran 2020-08-08 à 18 56 55" src="https://user-images.githubusercontent.com/69396042/89715844-f8324a80-d9a8-11ea-9dc8-5ecc9eaae702.png">

### Versions 
[Google chrome, OS X, macbook pro, ...]

**Comment by alvarotrigo** [comment]
Sections = vertical panels
Slides = horrizontal panels.

You are missing the horizontal slides, you are only using vertical ones.
As detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js):

In order to create a landscape slider within a section, each slide will be defined by default with an element containing the slide class:

```html
<div class="section">
	<div class="slide"> Slide 1 </div>
	<div class="slide"> Slide 2 </div>
	<div class="slide"> Slide 3 </div>
	<div class="slide"> Slide 4 </div>
</div>
``` 
You can see a fully working example of the HTML structure in the [simple.html](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/simple.html) file.
