### ISSUE TITLE
Does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by JoseDeHaros** [alvarotrigo/fullPage.js#4036]
### Description
Does not use passive listeners to improve scrolling performance

Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance. [Learn more](https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools).

URL | Location
…fullpage/fullpage.min.js?ver=3.0.8 | line: 10

### Link to isolated reproduction with no external CSS / JS
1- Devtools in chrome
2- Test Lighthouse
3- Go to Performance
4- Check "Does not use passive listeners to improve scrolling performance"

### Versions 
Chrome 84 on Windows 10
(Maybe it doesnt matter)

**Comment by alvarotrigo** [comment]
What URL are you running for the test?

I can't see the problem you mention on this example:
https://alvarotrigo.com/fullPage/examples/continuous.html

Also, are you testing for desktop or for mobile?

**Comment by JoseDeHaros** [comment]
Alvaro, es en mobile solo.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Álvaro<mailto:notifications@github.com>
Enviado: jueves, 27 de agosto de 2020 12:06
Para: alvarotrigo/fullPage.js<mailto:fullPage.js@noreply.github.com>
CC: JoseDeHaros<mailto:josedeharo@outlook.com>; Author<mailto:author@noreply.github.com>
Asunto: Re: [alvarotrigo/fullPage.js] Does not use passive listeners to improve scrolling performance (#4036)


What URL are you running for the test?

I can't see the problem you mention on this example:
https://alvarotrigo.com/fullPage/examples/continuous.html

Also, are you testing for desktop or for mobile?

**Comment by JoseDeHaros** [comment]
Sorry Alvaro, is only in mobile.
![fullpagejs](https://user-images.githubusercontent.com/37634222/91462965-1940d980-e88b-11ea-882c-20605fe4c7d2.png)

**Comment by alvarotrigo** [comment]
Yeah there's nothing to worry about. That's just a warning that's why the error uses the word "consider" :)

As can be read [on the docs](https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools) pointed out by the "Learn more" link on the error, passive event listeners are used to indicate the browser that our event listener won't be preventing the scroll:

> Passive event listeners solve this problem by letting you indicate that an event listener will never prevent scrolling.

However fullPage.js works by preventing the default scroll behaviour and therefore it needs to prevent both touch and scroll events. 

See this lines:
https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js#L1528
https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js#L1552
https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js#L1432
https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js#L1552
https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js#L1410
