### ISSUE TITLE
elementor plugin - fixed header

### ISSUE THREAD

**Issue by janabetis** [alvarotrigo/fullPage.js#4041]
Hello and thank you for your time in advance!

I have read about how to exclude a section when inserting fullPage.js manually.
But I am using the elementor plugin (great work btw) and I cannot understand how to enable my global header (which I use as a nav bar) outside of the fullPage so that the header stays visible while scrolling on different sections.

Can you provide some guidance about fixing sections through the elementor plugin?

**Comment by alvarotrigo** [comment]
For questions regarding the [official Elementor plugin](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) please ask on the [contact form](https://alvarotrigo.com/#contact).

**Comment by merchantweb** [comment]
Also curious about this... the elementor section 'motion effects' > sticky: 'top/bottom' option does not work when fullpage for elementor is enabled. Would be nice to see the answer to this rather than need to fill out a form as it seems to be a standard plugin conflict that could be addressed for the open source community.
