### ISSUE TITLE
Premature next section loading when using scrollOverflow

### ISSUE THREAD

**Issue by JulianBroudy** [alvarotrigo/fullPage.js#4063]
### Description
Hello, I saw best to use `scrollOverflow: true;` for my needs where certain sections won't fit into full viewport.
**Problem:** Next section is loaded once the scrollbar reaches the end without pausing or requiring another scroll. This results in the content seen only briefly.

**Expected behavior:**
- User reaches a section that is bigger than the `vh`.
- User scrolls down, content is gradually shown **until the last part**.
- User scrolls again, next section is rendered.

**Actual behavior:**
- User reaches a section that is bigger than the `vh`.
- User scrolls down, content is gradually shown.
- Last part becomes visible and next section is immediately rendered.

### Link to isolated reproduction with no external CSS / JS
[CodePen](https://codepen.io/JulianBroudy/pen/zYqXoPp)

### Steps to reproduce it
1. Create a section that does not fit viewport's height. Ideally, between other sections.
2. Use scrollOverflow option.
3. Scroll.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
Unfortunately this bug is a well known one and we haven't been able to find a solution for it yet.

[Here's the original issue](https://github.com/alvarotrigo/fullPage.js/issues/941) we keep open to deal with the topic.

I'll close this one so we can keep the conversation in a single place.
