### ISSUE TITLE
Normal scroll in big section?

### ISSUE THREAD

**Issue by selfagency** [alvarotrigo/fullPage.js#4121]
### Description
So I understand you can have a big section that is larger than the window height, but how do you scroll within that section so that it scrolls normally down to the bottom, instead of just scrolling to the next page?

### Link to isolated reproduction with no external CSS / JS
This is your own demo https://codepen.io/alvarotrigo/pen/vYLdMrx

### Steps to reproduce it
Scroll to a big section, then scroll again

**Comment by alvarotrigo** [comment]
Use `scrollOverflow:true`.

Demo:
https://alvarotrigo.com/fullPage/examples/scrolling.html

**Comment by ArthurShlain** [comment]
It's possible to have default whole page scroll with 100% and more height sticky sections?

**Comment by alvarotrigo** [comment]
Unfortunately not at the moment, but I might have to review this in the future and see if browsers have improved this feature on mobile devices.

The reason why scrollOverflow exists is because there were quite a lot of issues making the scroll look natural on mobile devices, they would stop the scrolling when your finger stopped touching the screen.
