### ISSUE TITLE
Prevent instant jumping to the next section when using scrollOverflow

### ISSUE THREAD

**Issue by IcyFoxe** [alvarotrigo/fullPage.js#4189]
When using **scrollOverflow** on a section, whenever I reach bottom of this section it **immediately** switches to the next section.

Is there a way to lock scrolling to the next section for at least half a second or give it some scroll offset before it can switch to the next section? Normal sections work fine, because they wait for the animation to end before you can scroll to the next section.

You can perfectly see the problem here:
https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html#secondPage

**Comment by alvarotrigo** [comment]
It's actually quite a complex issue. 
[There's an open issue about it](https://github.com/alvarotrigo/fullPage.js/issues/941) that has never been closed and it doesn't seem to have a simple solution due to kinetic scrolling behavior. 

If you think there's a potential solution we are open to any pull request you can provide :)

I'll close this issue to keep the conversation centralised in a single place.
