### ISSUE TITLE
How to reset interval after manual move?

### ISSUE THREAD

**Issue by marek-dol** [alvarotrigo/fullPage.js#4218]
Hi guys,
you'll probably laugh at me, but I don't really know javascript at all.. I wanna use fullPage.js on on my friend's website. The code that i managed with the great help of google is below, it finally works as I need, but I would like to add a reset timer and I really can't handle it myself.

Basically I need to reset my 6 seconds interval each time the visitor clicks on the navigation or moves the section with the mouse wheel.

Could anyone please modify the code to make it work?

jQuery(document).ready(function($) {
    $('#fullpage').fullpage({
        //options here
      	licenseKey: '*******-'*******-'*******-'*******',
        autoScrolling:true,
      	continuousVertical: true,
        navigation: true,
      	afterRender: function(){
        setInterval(function(){
                $.fn.fullpage.moveSectionDown();
        }, 6000);
      },
      	  
});

    //methods
    $.fn.fullpage.setAllowScrolling(true);
});

**Comment by alvarotrigo** [comment]
As this is a generic JS question and not a fullPage.js specific one I would recommend you ask in stackoverflow.com where they'll be able to help you much better.

You can also read [how to create automatic vertical scroll with fullPage.js ](https://alvarotrigo.com/fullPage/help/how-to-autoplay-vertical-section-in-fullpage-js/) and [how to create automatic sliding for fullpage.js horizontal slides](https://alvarotrigo.com/fullPage/help/how-to-autoplay-horizontal-slides-in-fullpage-js/)

**Comment by marek-dol** [comment]
I assumed you could be more enjoyable when I paid you for your product and I require simple customer care 😠

**Comment by alvarotrigo** [comment]
Sure, if you paid for the Business license that includes premium support please use the [contact form](https://alvarotrigo.com/#contact) and we will attend you there.

Otherwise, notice basic fullPage.js licenses only include basic support on GitHub and this only includes fullpage.js usage questions.

**Comment by marek-dol** [comment]
If I knew you were so arrogant person, I would never buy anything from you.

**Comment by alvarotrigo** [comment]
> If I knew you were so arrogant person, I would never buy anything from you.

We have thousands of questions like yours (github, stackoverflow, email and youtube) and we can't deal with all of them if we want to keep on working on creating new things. Especially when they are not related to fullPage.js code.
I offered you an alternative (pay for premium support) as well as articles providing you the full code you need and websites where they can help you out.

If this is not enough for you, I guess nothing will.

We do our best to provide the best support we can. And that's why we created a licensing system that allows us to focus on those who are really in need and value not only their time but also ours. 

Expecting us to fix your JS code is like asking Apple to fix Windows computers (and for free).
