### ISSUE TITLE
Not working smoothly on iMac safari

### ISSUE THREAD

**Issue by akash-dew** [alvarotrigo/fullPage.js#4255]
I am using fullpage js on my website and found its not working smoothly on iMac safari. I don't know why its very jittery and unresponsive sometime sections jumping top to bottom.

**Comment by akash-dew** [comment]
Hello alvarotrigo,, Why you closed this Issue? I didt get any solution for that

**Comment by alvarotrigo** [comment]
I didn't get any isolated reproduction, so there's no way for me to help you out.

**Comment by akash-dew** [comment]
> I didn't get any isolated reproduction, so there's no way for me to help you out.

So you are saying i need to share your code with you so that you can replicate the issue. Is that you want ? Because "isolated reproduction" you want your code with no elemet and other js in it.

**Comment by alvarotrigo** [comment]
What I need is a page with the minimum amount of code possible to reproduce the issue.
To make sure the problem is not in your code, use as little code as possible that doesn't belong to fullPage.js. 

Remove all external CSS and JS to fullPage.js unless strictly required for the reproduction of the issue.
Use a single heading in each section unless strictly required for the reproduction of the issue.

Bear in mind this forum helps you get answers to questions regarding the use of fullpage.js as well as to report possible bugs in fullpage.js.
We won't be doing free consulting services for people for free, checking their whole page and fixing their own bugs :)
