### ISSUE TITLE
Elementor plugin reverse columns not working

### ISSUE THREAD

**Issue by ellepeony** [alvarotrigo/fullPage.js#4284]
Hi and thank you for an awesome plugin. I have a problem with reversed columns not working when fullpage.js is enabled though.

### Steps to reproduce it
1. Create a page with Elementor and enable fullpage.js and also set a responsive width. Put a section with two columns that are 50% each on the page and some content in each column.
2. For tablet make each column 100%.
3. In the section's advanced tab, responsive mode, enable Reverse Columns (Tablet) and Reverse Columns (Mobile). The column at the bottom will be moved up to the top as expected when viewing in elementor editor, but it won't work on the page itself.
4. Same issue seem to happen when using any of the Visibility options.

Thank you in advance

**Comment by alvarotrigo** [comment]
> 1. Create a page with Elementor and enable fullpage.js and also set a responsive width. Put a section with two columns that are 50% each on the page and some content in each column.

If the issue is regarding Elementor official plugin, you can use the [contact form](https://alvarotrigo.com/contact/) and we'll answer you there. This forum is only to treat questions/issues regarding the JavaScript library.

If the issue is related with a custom integration with Elementor, that's not something we cover here unfortunately.

However, if you think you can reproduce this issue on an isolated scenario with the minimum amount of HTML, CSS and JS, then feel free to create a reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp)and we'll check it out.

**Comment by ellepeony** [comment]
Thank you. Yes it is the Elementor official plugin so I'll send you the question through your contact form later. Apologise for posting in the wrong place at first.

**Comment by alvarotrigo** [comment]
No worries! ;)
