### ISSUE TITLE
Scroll Horizontally extension

### ISSUE THREAD

**Issue by halodevcr** [alvarotrigo/fullPage.js#4312]
I have purchased the scroll-horizontally extension for this library, and I was wondering if there is ANY way for me to achieve normal scrolling while using the extension. 

Or if do you have any suggestion on how I could avoid the autoScrolling from happening but still be able to scroll through the slides?

**Comment by alvarotrigo** [comment]
Unfortunately, fullPage.js doesn't provide free scroll in horizontal slides. 
There's an open issue about it [here](https://github.com/alvarotrigo/fullPage.js/issues/3360).

The Scroll Horizontally extension works only when using `autoScrolling: true` as stated on the docs:

>  It can only be used when using: autoScrolling:true. Ideal for story telling. Requires fullpage.js >= 3.0.1.

> Or if do you have any suggestion on how I could avoid the autoScrolling from happening but still be able to scroll through the slides?

Sorry, not at the moment. I'll consider this for the future!

So far, let us know if you want a refund of your extension if you are not planning to use it because of t
