### ISSUE TITLE
autoScrolling: true,

### ISSUE THREAD

**Issue by RameesV** [alvarotrigo/fullPage.js#4321]
in my design i have a issue related with this autoScrolling, wchich is i need to use one or more common html section and footer after fullpage wrapper. the main issue is the footer is not directly written in the page, its calling from stncil. 
*. if i made autoScrolling: false, there will be a animation sections inside **fullpage div** which will not work properly. 
*. is this possible to use auto _scrolling false_ after a particular section in side the full page or at the end of **fullpage wrapper**.?

**Comment by alvarotrigo** [comment]
> and footer after fullpage wrapper.

Unfortunately that's not supported.

I would recommend you to add the footer in the last section and then use `fp-auto-height` to have a non full-screen footer.
See an example here.
https://alvarotrigo.com/fullPage/examples/autoHeight.html#anchor3

>  is this possible to use auto scrolling false after a particular section in side the full page or at the end of fullpage wrapper.?

That's not possible with the current fullpage.js version 3.
I'm working on it for version 4, so that might be possible soon! :) (no estimate time for the release yet)
