### ISSUE TITLE
Incorrect data on "this" for callbacks

### ISSUE THREAD

**Issue by BurgerMenu** [alvarotrigo/fullPage.js#4337]
Hi Alvaro, I've struggled for multiple hours but it may be a bug inside the fullpage.js. When I scroll down or up the page, the callback function feedbacks incorrect index. The index initialed with 0, as the page scroll down from top to bottom and back to top, the index will be 0-1-2-3-2-1. If I repeat it, the index will be an incorrect cycle.

There are lots of errors on console also.

Here is the reproduction: https://jsfiddle.net/BurgerMenu/uad3npqw/3/

I found this problem on Vue CLI firstly and consider fullpage.js have some compatibility issues with Vue CLI, but later the problems appear in pure environment.

**Comment by alvarotrigo** [comment]
Thanks for reporting it! This seems like a bug!
The  problem is on the `this` value.

Instead, use `destination` and you'll be fine :)

Regarding the errors on the console, that's due to  using `menu:  ""` on  your fullpage.js options.
Remove the `menu` option if you don't plan on using it.

I've marked the issue as a bug and this will get fixed in the next release! 👍

**Comment by BurgerMenu** [comment]
Thanks for your helping, it now works on pure environment as well as Vue Cli :-)

**Comment by alvarotrigo** [comment]
Fixed in 4.0.7 🎉
