### ISSUE TITLE
Unable to activate fullpage.js - Scroll Horizontally

### ISSUE THREAD

**Issue by pradhanrak** [alvarotrigo/fullPage.js#4354]
### Description
We've bought the license for fullpage.js and extension twice and tried them, but we are still seeing the [Unlicensed fullPage.js Extension](http://alvarotrigo.com/fullPage/extensions/) on our website.

### Link to isolated reproduction with no external CSS / JS
our production site: https://forkandgoode.com/
We do not have isolated site.

### Steps to reproduce it
Can be seen on the site

### Versions 
All

**Comment by alvarotrigo** [comment]
Thanks for the heads up!
On the update to full-page version 4 we introduced a bug on the activation page.

The issue has been fixed.

I see you purchased the extension for version 3.
fullPage.js version 3 and 4 are not fully compatible.

You can get the version 4 files for free as you just purchased it a few days ago. However, can you confirm me you want to use fullpage.js version 4 instead of 3?

Check it out and let me know before I can reset your activation key counter.
See the migration guide here:
https://github.com/alvarotrigo/fullPage.js/wiki/Migration-from-fullPage-v3-to-fullPage-v4
