### ISSUE TITLE
Disabling Scroll Overflow in Sections Not Working as Expected

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#4430]
Hi,

The scroll overflow disable `fp-noscroll` class name is not working as expected with fullpage v4.

https://codepen.io/meceware/full/zYWNKzx

I think the CSS something like below would be necessary:

```
.fp-noscroll {
    justify-content: flex-start;
    overflow: hidden;
}
```

However, with this one, `bigSectionsDestination` is not working as expected.

**Comment by alvarotrigo** [comment]
Thanks Mehmet! ;) 
Fixed on the dev branch!

**Comment by alvarotrigo** [comment]
Fixed in version 4.0.10! 🥳

**Comment by alvarotrigo** [comment]
I'll be reverting this change.

The problem adding `justify-content: flex-start;` on `fp-noscroll` is that people might apply it to sections that are not currently overflowing but that might overflow when resizing the viewport down.

This causes the content to be aligned to the top even when it's not overflowing and `verticallyCentered` is `true`.

So I believe it  will cause less issues to leave it  as  it was.
If the user wants the overflowing content to align to the top they can:

- Turn `verticallyCentered` off
- Or just add `justify-content: flex-start;` to that section/slide.

**Comment by alvarotrigo** [comment]
The reason why this behaved different in v3 is because of the behaviour of `display: table` & `display: table-cell` vs the current `display: flex` & `justify-content: center;`

I managed to find a fix by modifying a bit the fullPage.js behavior when fp-noscroll is present. 

Current behaviour is:

- `fp-noscroll` with no scrollable content will respect `verticalCentered` and have no effect.
- `fp-noscroll` with scrollable content will show the top of the content as it did on v3. Just as if we remove the scrollbar but leave the rest as it is. Showing the top and hiding the bottom. (no matter  what `verticalCentered` is)

**Comment by meceware** [comment]
All right, thank you, I will test it more.
