### ISSUE TITLE
button href target a section after its impossible to scroll up 

### ISSUE THREAD

**Issue by cid-wings** [alvarotrigo/fullPage.js#4443]
Hi!

added a simple button that target a section . He goes to the right section  after we cant scroll-up but we can scroll-down 
the fun part is to be able to scroll back up again u have to scroll all u way down when u reach the bottom u have to scroll one more time and you will be able to reach the top by scrolling up ....

https://jsfiddle.net/cidwings/bmsp4o0f/2/

### Versions 
all device/system on the version 4.0.10 i dont try on the other

**Comment by alvarotrigo** [comment]
You can use the `anchors` optino to assign a different anchor to each section:

```js
new fullpage('#fullpage', {
	anchors: ['one', 'two', 'here', 'four'],
	
        //your other options...
});
```

This way the `#here` anchor will be linked to the 3rd section.
https://jsfiddle.net/g26adykw/

The other option is just using the fullPage.js JS methods such as `moveTo`.

**Comment by cid-wings** [comment]
thank u for ur answer but ...
even on ur answer we cant go back to section 1 ...

**Comment by alvarotrigo** [comment]
Right, that's because I forgot to remove `id="here"` from your section element in the HTML markdown.
In fact, there was an error in the JS console warning you about it:
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/1706326/185717207-a9ea34a7-d558-4dd7-b37b-5661035a3250.png">

Here's the fixed version:
https://jsfiddle.net/zav9ofj5/

**Comment by cid-wings** [comment]
Okay now I got it perfectly how its works thanks you so much ! 
I will be soon the owner of a licence then ^^
