### ISSUE TITLE
Fullpage adds fp-is-overflow also if not 

### ISSUE THREAD

**Issue by plcdnl** [alvarotrigo/fullPage.js#4460]
### Description
With new version 4.0.11 it adds a wrapper fp-overflow that broke some of my old css style

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/plcdnl/pen/YzLWBvQ

### Versions 
Firefox, Chrome and Safari on Macbook Pro 13 M1

**Comment by alvarotrigo** [comment]
Yeah. 
Sorry about that :)

But we'll go this route now.
Using `scrollOverflow` will add a wrapper to your content.

**Comment by davITnemec** [comment]
Hello @alvarotrigo, I'm having a similar issue after upgrading to 4.0.11. 

I'm using for some of my last divs in sections `margin-top:auto;` what pushes the content to the bottom. It was working till upgrade 4.0.11. because you wrapping the content with `fp-overflow` automatically for every section. 

If I delete the `fp-overflow` div, it's pushed to bottom again (see both screenshots).

Is there any way how to fix it?

![image](https://user-images.githubusercontent.com/9250148/195315093-4719243e-61fb-4b7a-b41b-3d13e718ce3a.png)
![image](https://user-images.githubusercontent.com/9250148/195315108-39cffbde-d8da-4b65-a08c-2d383d4c8ff4.png)

**Comment by alvarotrigo** [comment]
Try using the dev version 4.0.12 and see if you still having problems. 

If so, can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by davITnemec** [comment]
Here is the jsfiddle - https://jsfiddle.net/cxu9qz34/2/

As default, the text "text at the bottom of the section" is not at the bottom. Once I delete via Inpsect `fp-overflow` div, the div goes to the bottom. 

See before and after screenshots. as well.
![image](https://user-images.githubusercontent.com/9250148/195531922-352c7373-5ed5-46e1-80e5-5572d47bdf40.png)
![image](https://user-images.githubusercontent.com/9250148/195531937-61efd441-8acd-490e-a65d-c20a01174888.png)

**Comment by alvarotrigo** [comment]
@davITnemec you can use the fullPage.js option `scrollOverflow: false` to solve the issue if you are not planning on using scrollable sections with content larger than the viewport.

Otherwise, notice the `fp-overflow` is not a flex element and it's not taking 100% height of the viewport. 
So in this case you'll have to go another route.

I'd probably use an absolute positioned element to place the item on every bottom of the section.

**Comment by davITnemec** [comment]
Ok, I need to keep option `scrollOverflow: true` because some of my sections are overflowing. 

Anyway, thank you for your guideance - the working issue is here if someone will handle similar issue - https://jsfiddle.net/e73otkz1/
