### ISSUE TITLE
Is it possible to have the source code of the homepage?

### ISSUE THREAD

**Issue by Fatichti** [alvarotrigo/fullPage.js#4486]
Hello 👋 ,

You have already made a wonderful and beautiful product.

I would like to know if it is possible to have the code (HTML, JS, CSS) for the page https://alvarotrigo.com/fullPage/ ?

It is for an open source project to have vertical and horizontal scrolling with the mouse.

**Comment by alvarotrigo** [comment]
It's not something we provide.
But I guess you can always check the source code? :)

I'd recommend you to check the examples folder otherwise:
https://github.com/alvarotrigo/fullPage.js/tree/master/examples

You can download and try them all and choose the one you like the most as your starting point.
