### ISSUE TITLE
Scroll not full height content

### ISSUE THREAD

**Issue by Rollengor** [alvarotrigo/fullPage.js#4487]
I ran into a problem when autoscrolling to another section occurs without completing the scroll of the previous one where the content exceeds the height of the section. You can see the example I copied from https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html and just added more text https://codepen.io/rollengor/pen/WNyOZJd

Как можно это исправить?

**Comment by alvarotrigo** [comment]
A few things are wrong with that codepen:

- The scrollOverflowReset file is a [paid extension](http://alvarotrigo.com/fullPage/extensions/). The file you are using is the limited version for the demo page and won't work in other websites. You need to replace it for the one you get on the purchase.
- fullPage.js 3 is being loaded instead of version 4 (use a CDN like [this](https://unpkg.com/fullpage.js@4.0.14/dist/fullpage.min.js) instead for both CSS and JS) 

Fix those and if you still having issues after purchasing the extension, use the [contact form](https://alvarotrigo.com/contact/) to get support.
