### ISSUE TITLE
Scrolling without having to wait for section load finish

### ISSUE THREAD

**Issue by porocode11** [alvarotrigo/fullPage.js#4532]
### Description
Is it possible for this library to handle scrolling while in the middle of another scroll. From my testing (even on the demos) there's a delay at the end of section loading. Even if i set the scrollingSpeed to 1,  I can feel quite the huge delay when moving via keyboard or scrolling with the mouse.

Is there any way to disable this?

**Comment by alvarotrigo** [comment]
Unfortunately, that's not possible. 

The main reason for this is that fullPage.js has measures in place to prevent unwanted scrolls caused by kinetic scrolling devices like Apple's Magic Mouse, Apple's trackpads, and other laptops' trackpads and mouses like Logitech MX Master.

Those devices throw tens or hundreds of scroll events per "swipe" and the only way we have to prevent unwanted scrolls is by trying to define what a scroll is and usually setting a minimum time when we won't accept new events.

What you consider to be 2 swipes, can also be a long/fast swipe on these other devices.

**Comment by porocode11** [comment]
Is it possible to decrease that minimum time somewhere (like code location)?

**Comment by alvarotrigo** [comment]
Sure!
You can do in this line, replace the `700` (milliseconds) for a lower value, for example `100`:
https://github.com/alvarotrigo/fullPage.js/blob/master/dist/fullpage.js#L2571

Just be aware this might result in unwanted scrolls for certain visitors. 

Note this only applies for `scrollingSpeed` < 700.
