### ISSUE TITLE
Video background do not play on safari

### ISSUE THREAD

**Issue by obemer** [alvarotrigo/fullPage.js#4535]
Hello Alvaro, 

Sorry to bother you with this, 

Do you have any idea why the video autoplay works one time out of ten loadings in Safari ? 
Even on your page: https://alvarotrigo.com/fullPage/examples/videoBackground.html

I get this on the console: 
![Capture d’écran 2023-04-17 à 17 06 08](https://user-images.githubusercontent.com/48288198/232531959-7f1fe95e-a562-4dae-a2a1-01811597c296.png)

**Comment by alvarotrigo** [comment]
Can you try using the latest version?
Try using this demo:
https://codepen.io/alvarotrigo/pen/pXEaaK

> https://alvarotrigo.com/fullPage/examples/videoBackground.html

This page is not using the latest fullPage.js version

**Comment by obemer** [comment]
Thank you for your answer. 

The video in section 3 is not autoplaying and I got this in the console. 
<img width="1788" alt="Capture d’écran 2023-04-17 à 20 23 29" src="https://user-images.githubusercontent.com/48288198/232577714-dd4ce0fa-fa37-4265-8adc-68a180b29fd5.png">

My Safari is up to date, and I have no specific settings for any websites. 
I'm guessing you don't have this problem ? 
Weird...

**Comment by obemer** [comment]
I'm asking because I'm having this issue on my website too.

**Comment by alvarotrigo** [comment]
I've tested it using browserstack.com and Safari 16.3 and it seems to be working just fine.

The error message on your screenshot says "possible because the user denied permission", so I'd check your browser configuration to make sure you allow auto playing videos. 

You can also try from different computers to see if you get any problem in those and discard the possibility of being a configuration on your current browser.

Another thing you can try is adding the attribute `playsinline` to your video element, so instead of this:

```html
 <video width="400" controls muted data-autoplay>
``` 

You use:

```
 <video width="400" controls muted data-autoplay playsinline>
```
