### ISSUE TITLE
Issue with FullPage.js on Mobile - Unable to Scroll in Footer

### ISSUE THREAD

**Issue by corne-aardig** [alvarotrigo/fullPage.js#4559]
Dear gitters,

I am writing to seek assistance with a problem I am encountering on my website while using FullPage.js on mobile devices. I have been facing difficulties in scrolling within the footer section, as the footer extends beyond the viewport. Although I have enabled the "scrollOverflow" option in the configuration by setting it to true and the .fp-auto-height class for the footer section, the scrolling functionality still does not work as expected.

Here are some additional details and relevant information:

Website URL: https://tommetje.webflow.io/
FullPage.js version: 4.0.20
Dependencies: iScroll 5.2.0 (included via CDN)
Below is a snippet of the code I am currently using:

```js
var myFullpage = new fullpage('#fullpage', {
		scrollOverflow: true,		
		scrollBar: true,
		fitToSection: false,
    touchSensitivity: 15,
    scrollingSpeed: 700,
    easing: 'easeInOutCubic',
    easingcss3: 'ease',
      afterLoad: function(origin, destination, direction) {
    if (destination.index === 1) { // Check if it's the second section
      $('.nav-link, .tommetje-logo, .nav-hamburger-line').addClass('is-black');
    } else {
      $('.nav-link, .tommetje-logo, .nav-hamburger-line').removeClass('is-black');
    }
  },

  onLeave: function(origin, destination, direction) {
    if (origin && origin.index === 1) { // Check if leaving the second section
      $('.nav-link, .tommetje-logo, .nav-hamburger-line').removeClass('is-black');
    }
  },

});
```

It significantly impacts the overall user experience on mobile devices. It is crucial for the footer section to be scrollable without any bugs or glitches. Please let me know if there are any recommendations, updates, or modifications that can rectify this problem.

Best regards,

Aardig

**Comment by alvarotrigo** [comment]
> Dependencies: iScroll 5.2.0 (included via CDN)

fullpage.js 4 doesn't require any vendor library for scrollOverflow.
You can remove that.

What exactly is failing?
We don't check personal websites here, only for customers of the Business plan (Check more on the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a>).

I'd recommend you to take a look at the examples using fp-auto-height like these ones:
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/auto-height.html
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/responsive-auto-height.html

And the one using scrollOverflow like this:
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/scrollOverflow.html

If you are able to provide an isolated reproduction in codepen or jsfiddle with no external CSS and JS files and the minimum amount of HTML code, I'll be happy to assist.
Otherwise, I'd recommend you get the Business license for premium support.
