### ISSUE TITLE
Is there a way to change horizontal scrolling to vertical?

### ISSUE THREAD

**Issue by tomhimsworth** [alvarotrigo/fullPage.js#4614]
I inherited a Wordpress site using BeTheme that utilizes fullpage.js to scroll horizontally between slides and vertically between sections. Does anyone know how to adjust to make the entire thing scroll vertically? I don't know if you need specifics of the site, I am familiarizing myself with it but couldn't figure out how to make this adjustment.

**Comment by alvarotrigo** [comment]
Sure!

Just use sections instead of slides.

See more on the <a href="https://alvarotrigo.com/fullPage/docs" target="_blank">fullpage.js documentation</a>.

Basically instead of having a single section with multiple horizontal slides:

```html
<div id="fullpage">
  <div class="section">
    <div class="slide">
      Slide 1
    </div>
    <div class="slide">
      Slide 2
    </div>
    <div class="slide">
      Slide 3
    </div>
  </div>
</div>
```

You should have multiple sections with no slides on them:

```html
<div id="fullpage">
  <div class="section">
    Section 1
  </div>
  <div class="section">
    Section 2
  </div>
  <div class="section">
    Section 3
  </div>
</div>
```

If you are using the [fullPage.js plugin for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) or the one [for Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/) then you should follow a similar approach.
