### ISSUE TITLE
need of a nice smooth darken and lighten effect on the panel views.. 

### ISSUE THREAD

**Issue by halukkaramete** [alvarotrigo/fullPage.js#4624]
### Description
I got YT players on all the full-page panels. As I scroll down, they play and pause automatically exactly like YouTube shorts behaviour. However, to avoid the buffering, I pre-start the next panel's video and mute it.  This makes the next video ready to go as soon as we scroll down to it.  ( otherwise, I'd see a buffering spinner ). This technique does work, however, when I scroll to that panel, I have to run a seekto(0) method so that the video can be shown to the users properly that is from the very beginning.  This idea works except that for a split second, I do see the video playing a bit then being forced back to 0 location before it starts playing from the very beginning. Needless to say, it is not a desirable experience. 

I tried slowing down the scrolling speed to 1700. That did not help either. Since I'm firing the playVideo event on "afterLoad", the "1700" does not help. 

So I started thinking, maybe for about 300ms I can darken the screen ( meaning the current panel ) so by the time, it lightens up that next video would have been set to 0 so we do not view that "play a bit, then go back and play again" thing. 

What's the most elegant way to achieve this?
I'm trying to fade out and fade in in the 2 to 3 hundred ms. 

By the way, since I'm stuck with 2.6.6, I may not use some of the techniques you may have developed in your latest versions. 
With 10K+ js code planted, it is too late for me to switch to the new version.   

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
You can try to play the video on the `onLeave` event instead. This way it might be loaded once you completely land on the section.

Otherwise, you can also rewind the video using `onLeave`. Not just when it leaves the current section to move to the destination, but a bit later using some timeout. This way, you can try to rewind it just at the right time. After leaving a section but before landing on the destination. You know the transition takes "X" (being X the value of scrollingSpeed), so you can use this in your favour to calculate the ideal timeout.

> What's the most elegant way to achieve this?

To be honest, I don't know :) I never tried it. 
But I'd say this is more of a web design issue rather than a fullPage.js one. 

> With 10K+ js code planted, it is too late for me to switch to the new version.

I'd say it's never too late :)

fullPage.js version 2 is almost 100% compatible with version 3, and version 3 and version 4 don't have many differences either in terms of usage or API. 
You can see [the migration guide](https://alvarotrigo.com/fullPage/help/migration-from-fullpage-3/) for v3 to v4.

One thing is for sure, fullPage.js v2 has tens of critical bugs. A quick look on [the releases page](https://github.com/alvarotrigo/fullPage.js/releases) and you'll notice.

**Comment by alvarotrigo** [comment]
> One thing is for sure, fullPage.js v2 has tens of critical bugs. A quick look on [the releases page](https://github.com/alvarotrigo/fullPage.js/releases) and you'll notice.

My point here is that right now you are trying to fix a "small" issue with the videos that almost no visitor will really care much about, while there are tens of critical bugs in fullpage.js version 2 that can prevent users from even scrolling up/down properly depending on the device or configuration of your setup. Serious bugs that you might not always see personally, but that be annoying visitors too.
