### ISSUE TITLE
Rebuild/destroy fullPage instance when transitioning from desktop to mobile

### ISSUE THREAD

**Issue by neilmuralee** [alvarotrigo/fullPage.js#583]
Hi,
Before I start, awesome plugin.

I'm building an app where i need to be able to rebuild the instance of fullpage on viewport resize.

Basically, I don't want to have fullPage on mobile (less than 768px), but I do on desktop sizes (greater than 768px), - i can't change this threshold, as it is part of a wider project setting. 

I understand that I can call the plugin to work just for desktop:

``` javascript
if ($(window).width() > 768) {
 $('.fullpageSelector').fullpage();
}
```

There is a case where a user may resize the viewport from mobile to desktop.

Is it possible to rebuild/destroy fullPage when it crosses that threshold?

My initialisation code:

``` javascript
function fullPageIntroInit() {
            if ($(window).width() > 768) {
                $('.intro.slides').fullpage({
                    verticalCentered: true,
                    paddingTop: '4%',
                    paddingBottom: '35px',
                    menu: ".slides-nav",
                    navigation: true,
                    anchors: ['Themes', 'DragDrop', 'DesktopMobile', 'HostingDomains'],
                    navigationTooltips: ['Beautiful Themes', 'Simple to Edit', 'Dektop / Mobile', 'Web Address and Hosting'],
                    slideSelector: '.fs-slide',
                    scrollOverflow: false,
                    css3: true,
                    resize: true
                    //resize: true,
                    // onLeave: function(index, nextIndex, direction) {},
                    // afterLoad: function(anchorLink, index) {},
                    // afterRender: function() {},
                    //afterResize: function() {}
                    // afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex) {},
                    // onSlideLeave: function(anchorLink, index, slideIndex, direction) {}
                });
            }
        }
```

Calling the function:

``` javascript
$(window).resize(function() {
                if ($(window).width() < 767) {
                    //if ($.fn.fullPage) {
                    $.fn.fullpage.destroy();
                    //}
                }
                if ($(window).width() > 768) {
                    $('.fullPageIntroInit').fullpage();
                }
            });
```

…doesn’t destroy the instance from initialisation. Alternatively ...

``` javascript
$(window).resize(function() {
                    homeButtonClassSwap();
                    if ($.fn.fullPage) {
                        $.fn.fullpage.destroy();
                    }
                    if ($(window).width() > 768) {
                        fullPageIntroInit();
                    }
                });
```

…this version on initialisationlooks and works fine on both desktop and mobile version, it doesn't seem to work on rebuilding/ the instance but does create duplicate navigation dots on resize.

Any help would be appreciated. Hope that all makes sense!

**Comment by porridj** [comment]
Just wanted to say cheers for 'flagging' that. Was struggling with it, but managed to get the final pieces of my puzzle using @byzanth's jsfiddle :) Also cheers to @alvarotrigo for helping me understand why I needed to do it haha

**Comment by mnotw** [comment]
@porridj haha! @alvarotrigo is a kind and patient guy

**Comment by mcranisnational** [comment]
Here is an updated fiddle that includes the flag variable triggered on resize instead of just using the destroy/build buttons!  http://jsfiddle.net/4vpepcsq/

**Comment by faliqaiman** [comment]
@mcranisnational great tricks man.. but I've try to set width and height but it only reflect for height function only.. [jsfiddle](https://jsfiddle.net/4vpepcsq/1/) try any luck for this one.. since would like to make the page go normal when in landscape mode..

**Comment by ParkJinHyoung** [comment]
Add it here source [no button]
http://jsfiddle.net/JinHyoung/m5k7wvk7/1/
Note please hahahaha...

**Comment by alexrumsey** [comment]
thanks all! super helpful

**Comment by Grahamfleminghsc** [comment]
Thanks for the help everyone. That all works great but I am trying to run two different HTML/CSS for mobile/desktop 

Instead of just turning fullpage.js off for mobile, is there a way to run one of them if people are on mobile and another instance on desktop? I have #fullpage and #fullpage2 as ids in one HTML file. .mobile-2018 .desktop-2018 in one CSS

Is that possible? This is what I have so far it works fine for mobile does not load for desktop.

`
  if ($(window).width() < 960) {
    if ($('.mobile-2018').length > 0) {
      $('#fullpage').fullpage({
        anchors: ['page1', 'page2', 'page3', 'page4', 'page5'],
        touchSensitivity: 20
      });
      $('img.responsimg').responsImg();
    }

      else {
        if ($('.desktop-2018').length > 0) {
          $('#fullpage2').fullpage({
            anchors: ['desktop-page1', 'desktop-page2', 'desktop-page3'],
            touchSensitivity: 20
          });
          $('img.responsimg').responsImg();
        }
      }
    }
`

Thanks

**Comment by Grahamfleminghsc** [comment]
Thanks for the help everyone. That all works great but I am trying to run two different HTML/CSS for mobile/desktop

Instead of just turning fullpage.js off for mobile, is there a way to run one of them if people are on mobile and another instance on desktop? I have #fullpage and #fullpage2 as ids in one HTML file. .mobile-2018 .desktop-2018 in one CSS

Is that possible? This is what I have so far it works fine for mobile does not load for desktop.

`
if ($(window).width() < 960) {
if ($('.mobile-2018').length > 0) {
$('#fullpage').fullpage({
anchors: ['page1', 'page2', 'page3', 'page4', 'page5'],
touchSensitivity: 20
});
$('img.responsimg').responsImg();
}
else {
    if ($('.desktop-2018').length > 0) {
      $('#fullpage2').fullpage({
        anchors: ['desktop-page1', 'desktop-page2', 'desktop-page3'],
        touchSensitivity: 20
      });
      $('img.responsimg').responsImg();
    }
  }
}
`

Thanks

**Comment by Grahamfleminghsc** [comment]
Thanks for the help everyone. That all works great but I am trying to run two different HTML/CSS for mobile/desktop

Instead of just turning fullpage.js off for mobile, is there a way to run one of them if people are on mobile and another instance on desktop? I have #fullpage and #fullpage2 as ids in one HTML file. .mobile-2018 .desktop-2018 in one CSS

Is that possible? This is what I have so far it works fine for mobile does not load for desktop.

`
if ($(window).width() < 960) {
if ($('.mobile-2018').length > 0) {
$('#fullpage').fullpage({
anchors: ['page1', 'page2', 'page3', 'page4', 'page5'],
touchSensitivity: 20
});
$('img.responsimg').responsImg();
 }

  else {
    if ($('.desktop-2018').length > 0) {
      $('#fullpage2').fullpage({
        anchors: ['desktop-page1', 'desktop-page2', 'desktop-page3'],
        touchSensitivity: 20
      });
      $('img.responsimg').responsImg();
    }
  }
}
`

Thanks

**Comment by Grahamfleminghsc** [comment]
Thanks for the help everyone. That all works great but I am trying to run two different HTML/CSS for mobile/desktop

Instead of just turning fullpage.js off for mobile, is there a way to run one of them if people are on mobile and another instance on desktop? I have #fullpage and #fullpage2 as ids in one HTML file. .mobile-2018 .desktop-2018 in one CSS

Is that possible? This is what I have so far it works fine for mobile does not load for desktop.

`if ($(window).width() < 960) {
if ($('.mobile-2018').length > 0) {
$('#fullpage').fullpage({
anchors: ['page1', 'page2', 'page3', 'page4', 'page5'],
touchSensitivity: 20
});
$('img.responsimg').responsImg();
}

  else {
    if ($('.desktop-2018').length > 0) {
      $('#fullpage2').fullpage({
        anchors: ['desktop-page1', 'desktop-page2', 'desktop-page3'],
        touchSensitivity: 20
      });
      $('img.responsimg').responsImg();
    }
  }
}`
Thanks

**Comment by Grahamfleminghsc** [comment]
Thanks for the help everyone. That all works great but I am trying to run two different HTML/CSS for mobile/desktop

Instead of just turning fullpage.js off for mobile, is there a way to run one of them if people are on mobile and another instance on desktop? I have #fullpage and #fullpage2 as ids in one HTML file. .mobile-2018 .desktop-2018 in one CSS

Is that possible? This is what I have so far it works fine for mobile does not load for desktop.

if ($(window).width() < 960) {
  if ($('.mobile-2018').length > 0) {
    $('#fullpage').fullpage({
      anchors: ['page1', 'page2', 'page3', 'page4', 'page5'],
      touchSensitivity: 20
    });
    $('img.responsimg').responsImg();
}

  else {
    if ($('.desktop-2018').length > 0) {
      $('#fullpage2').fullpage({
        anchors: ['desktop-page1', 'desktop-page2', 'desktop-page3'],
        touchSensitivity: 20
      });
      $('img.responsimg').responsImg();
    }
  }
}

Thanks

**Comment by Grahamfleminghsc** [comment]
Thanks for the help everyone. That all works great but I am trying to run two different HTML/CSS for mobile/desktop

Instead of just turning fullpage.js off for mobile, is there a way to run one of them if people are on mobile and another instance on desktop? I have #fullpage and #fullpage2 as ids in one HTML file. .mobile-2018 .desktop-2018 in one CSS

Is that possible? This is what I have so far it works fine for mobile does not load for desktop.

 if ($(window).width() < 960) {
   if ($('.mobile-2018').length > 0) { 
    $('#fullpage').fullpage({
       anchors: ['page1', 'page2', 'page3', 'page4', 'page5'], 
      touchSensitivity: 20 
    });
     $('img.responsimg').responsImg(); 
 }

  else {
    if ($('.desktop-2018').length > 0) {
      $('#fullpage2').fullpage({
        anchors: ['desktop-page1', 'desktop-page2', 'desktop-page3'],
        touchSensitivity: 20
      });
      $('img.responsimg').responsImg();
    }
  }
}

Thanks
