### ISSUE TITLE
It it possible to use iscroll.js with fullpage.js?

### ISSUE THREAD

**Issue by kyle-jennings** [alvarotrigo/fullPage.js#623]
First of all, I love this plugin. I'm using it on my site howfuckedisthemetro.com and it works great.

The only issue I have is using slimScroll.js for the scroll hijacking (its very choppy on mobile) on the scrollable sections/slides I've opted to try iscroll for a better mobile experience but I cant seem to get it to work.

I have my scrollable area inside of a slide (which gives it a set height which I need) and Im applying the iscroll directtly to the `div.slide`. iscroll looks like it adds the appropriate CSS to the first child of div.slide which is `div.container` as seen below

`<div id="line-start" class="slide scroll-wrapper active" style="width: 50%;">
        <div class="container" style="transition: 0ms cubic-bezier(0.1, 0.57, 0.1, 1); -webkit-transition: 0ms cubic-bezier(0.1, 0.57, 0.1, 1); transform: translate(0px, 0px) translateZ(0px);">`

But I cannot click and drag the `div.container` element.

I have my iScroll javascript well after loading fullpage.js:

```javascript
`var scrollStart, scrollEnd;
function iScrollLoaded() {
    scrollStart = new IScroll('#line-start',{
      mouseWheel: true,
      scrollbars: true
    });
}
setTimeout( iScrollLoaded(), 5000 );`
```
 and tried loading it before hand as well) and I dont see any console errors but `div.container` simply will not scroll.

I also set the `normalScrolling` option to ignore that `div.container`
Any suggestions?

**Comment by Torquin** [comment]
Hi guys, 

Instead of using iScroll or slimscroll (that still doesn't have any momentum), set scrollOverflow to false and add $('.slide .active').css('overflow-y','auto'); in the afterSlideLoad function. This should set the native scrollbar with momentum to devices ;)

**Comment by alvarotrigo** [comment]
@Torquin the native one looks quite ugly from a computer. iScroll.js has momentum.

**Comment by ivanhalen** [comment]
Now that support for older IE versions is over, maybe iScroll would be a better alternative :-) https://www.microsoft.com/en-US/WindowsForBusiness/End-of-IE-support

**Comment by alvarotrigo** [comment]
> Now that support for older IE versions is over, maybe iScroll would be a better alternative :-)

Not really. IE 9 still being used out there. 
fullpage.js is ready to support other external libraries for the scrollOverflow feature, in fact, there's [a GIST](https://gist.github.com/rmarscher/5f3a62b960f5f903a6af) that includes iScroll.js rather than slimScroll.js, but as I pointed out in [this conversation](https://github.com/alvarotrigo/fullPage.js/pull/1543) it doesn't seem to be such a great alternative as it will show the default scroll bar on Windows rather than the mac style one.

**Comment by mac2net** [comment]
LOL you think giving IE9 users Wndows style scroll bars is a problem?

**Comment by alvarotrigo** [comment]
@mac2net who said the scroll bar is only a problem for IE 9? I said "it will show the scroll bar on Windows". All browsers, all versions. (LOL)

**Comment by padjodev** [comment]
Im back!! My fix for this issue is pretty much useless - Has anyone come up with anything that will solidly work for the overflow scrolling slides. Ive seen all sorts of solutions like using underscores debounce etc etc but nothing seems to be solid and slimscroll have little or no solutions. would really like to get this sorted as its a massive site im working on and I dont want to have to scrap the idea just because of this scrolling on osx

**Comment by alvarotrigo** [comment]
fullpage.js changed from slimScroll.js to iScroll.js in 2.8.0.
