### ISSUE TITLE
iOS 8.1 Mobile Auto Scrolling Off

### ISSUE THREAD

**Issue by rajenms** [alvarotrigo/fullPage.js#799]
Hi, great plugin, thanks for all your work on it.

I've noticed that ever since I've upgraded to iOS 8.1, there are still remnants of auto scrolling on the actual iPhone device when scrolling through the page. For instance, try the following steps:

1) Go to your demo page - http://alvarotrigo.com/fullPage - on iPhone/Safari
2) Open up web inspector
3) Turn auto scrolling off... $.fn.fullpage.setAutoScrolling(false)
4) Scroll up and down

You should notice that the page jumps around as you scroll, when you really should expect the page to scroll smoothly. 

I'm going to investigate this in the source code, but I was wondering if you can look to and if you had any ideas off the top of your head.

Thanks!

**Comment by maciejtatol** [comment]
#### Tags: iOS, height, fix, problem
Sometimes when I use fullpage.js on iOS devices there is problem with height adjust (height of section is sometimes caluculated 10 times bigger than it is). My solution for this is to use this function:
```javascript
function getWindowHeight(){
  return window.innerHeight ? window.innerHeight : $(window).height();
}
```
inside afterRender and afterResize event like that
```javascript
...
    afterRender: function(){
      $(".section").height(getWindowHeight());
    },
    afterResize: function(){
      $(".section").height(getWindowHeight());
    }
...
```
This solves problem with random section height on iPads and iPhones. I suggest use this solution to retrieve height on jquery.fullPage.js:462(v 2.6.9)

**Comment by rohanchambers** [comment]
Hello Alvaro.
Like everyone has said before, amazing plugin. Thank you so much. 
I am having the issue that everyone has mentioned above but with **iOS10**. Sorry, wasn't sure if I should have raised a new issue. 
So on mobile when I scroll up a little it jumps to the top, most likely because of the the address bar in the top changes its size like you mentioned. Below is what I use to initialise fullpage.
I was wondering if you had come across this and if there was a fix for it?
Many thanks 

	    $('#fullpage').fullpage({
	    	anchors:['section-intro', 'section-about-us', 'section-investments', 'section-past-projects', 'section-team', 'section-bafta-support'],
			navigation: true,
			navigationPosition: 'right',
			navigationTooltips: ['Intro', 'About us', 'Investments', 'Past Projects', 'Team', 'BAFTA Support'],
			scrollingSpeed: 1000,
			scrollBar: true,
			keyboardScrolling: true,
			responsiveWidth: 600,
			css3: false,
			lazyLoading: false,
			autoScrolling: true,

			onLeave: function(anchorLink, index){
				var videos = $('video');
				videos.get(0).pause();
			  	videos.currentTime = 0;
			},

			afterLoad: function(anchorLink, index){
				var videos = $('video');
				videos.load();			
			}
	    });

**Comment by alvarotrigo** [comment]
@rohanchambers I'm not able to reproduce it in [the scrollBar demo](http://alvarotrigo.com/fullPage/examples/scrollBar.html).
Please add a link or a video of the issue ideally.

**Comment by rohanchambers** [comment]
Hi Alvaro, 

I can’t replicate the bug on the scrollbar demo. However the issue occurs when responsiveWidth: 600
If you could have a look at this link and try and scroll up it just jumps straight to the top.

http://www.slamdunkdigital.co.uk/clients/varcale/ <http://www.slamdunkdigital.co.uk/clients/varcale/>

Many thanks for your support

Rohan

**Comment by alvarotrigo** [comment]
@rohanchambers you'll have to provide an isolated reproduction with no external CSS or JS so I can check it to make sure the problem is in fullPage.js and not in your side.

**Comment by rohanchambers** [comment]
Sorry to get back so late. I did an isolated version like you said and the issue didn't occur. I narrowed it down and the culprit was using the skrollr plugin when using fullpage. 
Thanks again for responding so quickly and for creating a kick ass plugin!

Just in case anyone runs in to the same problem, on resize() I was using the skrollr.init().destroy() function to remove skrollr below the width of 768 and if it was a mobile. However by doing this it caused the issue in question of jumping to the top of the window on mobile when swiping up.
I lost some functionality when resizing on desktop browsers but that's ok. Below is what I changed to get it to work properly.


// Issue code
$(window).resize(function() {
		// Initialize skrollr if the window width is higher than 768px wide else destroy skrollr
		if ($(window).width() < tabletWidth || isMobile() ) {
			skrollr.init().destroy();
		} else {
			skrollr.init({
			    forceHeight: false
			});
		}
	};
});

// Solved with 

$(window).resize(function() {
		if ($(window).width() > tabletWidth) {
			skrollr.init({
			    forceHeight: false
			});
		}
});
