### ISSUE TITLE
1px gap on the right side of slides

### ISSUE THREAD

**Issue by sandrodz** [alvarotrigo/fullPage.js#828]
I've noticed slides have 1px gap on the right side (chrome) from slide to slide demo:

https://sandbox.idev.ge/roomshotel/mobile_html5_v1/#section-touch

Any thoughts?

Your plugin is so good btw, much better than scrollsections :)

**Comment by andrewtibbetts** [comment]
3 slides. It's the 33.33333333333% width.
Chrome 44.0.2403.89
OSX 10.10.4
![fp-1px-gap](https://cloud.githubusercontent.com/assets/296908/8883751/dd13a9f4-3216-11e5-87e0-a4e05c5ce202.jpg)

**Comment by wagnerpaul** [comment]
I can confirm the bug in chrome on a mac.  I spent a little time figuring out exactly what causes it.

It seems to be a subpixel rounding error as the line on the right doesn't look to be a full pixel width.

It happens for me with 3 slides at certain random widths (probably specific numbers that don't divide well by 3) that are usually when the viewport is very large. 

The code setting the width is here: https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L693 and https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L711

I did a few tests and discovered that although js in the console of 100 / 3 produces  33.333333333333336 when inserted into the dom chrome rounds it to 33.3333%

This is not enough precision to overcome subpixel rounding errors.  Perhaps computing to actual pixels instead of percent based widths would correct the problem.

In any case I can happily report that @sandrodz fix in https://github.com/alvarotrigo/fullPage.js/issues/828#issuecomment-62763039 does indeed work for me.
