### ISSUE TITLE
Consider using 100vw / 100vh CSS units to make things full page

### ISSUE THREAD

**Issue by contentfree** [alvarotrigo/fullPage.js#854]
CSS3 gives us viewport-relative units. 100vw means 100% of the viewport width. 100vh; 100% of the height. Very handy when doing full screen slides… It also has good support: http://caniuse.com/#feat=viewport-units

**Comment by tezro** [comment]
Please never implement vw/vh related behaviour.

**Comment by alvarotrigo** [comment]
@tezro could you elaborate that?

**Comment by tezro** [comment]
Sure. IE8 is still more popular than IE9. Also vw/vh is extremely inconsistent from browser to browser.

**Comment by contentfree** [comment]
Yeah, but IE8 only represents [~4% of global usage](http://beta.caniuse.com/#search=vh) (about the same as "UC Browser for Android 9.9"…) and IE9/10/11 together represent ~12%. 

Please source "vw/vh is extremely inconsistent from browser to browser." Again, using caniuse.com as a source, there's few known issues specific to vw/vh (a notable exception being Safari on iOS 7.1 when you leave the page and come back more than 60 seconds later).

**Comment by tezro** [comment]
What we do at work is install top 5 versions of all browsers, each in separate VM. Run minimal tests for needed CSS or JS features. Compare screenshots and values pixel by pixel. You don't really need to source anything when you do web dev every day and know the issues. vw/vh and of course vmax is inconsistent depending on the browser and the OS.

**Comment by alvarotrigo** [comment]
Closed as it doesn't seem to be a good solution.

**Comment by Quaked** [comment]
You're talking about a solution for what fullPage should utilize by default. I'm not ( #1515 ).

Here's the gist. Make it up to the developer and use pixels as default value – but don't disallow vh/vw. Why? Because using 100vh for example would mean less lookup for jQuery in terms of finding out window.height() on init AND on resize. This is no longer needed. 100vh is 100vh. Ultimately this means better performance and cleaner code (nothing needs to be inline styled except the container).

I'd go with better performance over IE8 support any day. Even IE9. That's me. And it should be up to the dev and project, no? As well as custom classes for container (fullpage-wrapper) and sections (fp-section) and vertically centered sections (fp-table). More options for the developer. 

Why would this be bad?

**Comment by alvarotrigo** [comment]
> I'd go with better performance over IE8 support any day. Even IE9

Sorry but I prefer to keep providing support for them. I haven't researched much about `vh` and `vm` but it seems it is not very consistent as @tezro  said:

> vw/vh and of course vmax is inconsistent depending on the browser and the OS.

Using pixels instead won't create any real performance problem in your site. The difference will be negligible... They are only recalculated on window resize every 350 milliseconds, which is not a bad delay. 
Using other measures can lead to problems with other options such as `scrollOverflow`. 

If you are so worry about performance, you'd better use [the pure javascript fullpage.js version](https://github.com/alvarotrigo/fullPage.js/tree/master/pure%20javascript%20(Alpha)). It is still under development, as I have no much time or it, but be sure it will be much faster than the jQuery version. (plus it is not using pixels as it doesn't work with `scrollOverflow`).

**Comment by Quaked** [comment]
I'm asking for options, not for you to change the default from pixels to vh. There's a difference!

If not, then how can I extend/replace functionality without having to fork/modify yours? Basically I'd just want to access the variables you've registered to hold the element classes as well as rewriting scrollPage function etc. Can I redefine them somehow? Like extending/overwriting.

The point being, give the tools for the developer to develop using your plugin. Don't limit the developer, give them options to decide how they'd want to use the functionality you've written?

Personally I'd want to use vh for this project. I'd also want to not have jQuery do so much inline to the DOM but use classes instead. The only thing needed to be inline would be on the container, switching sections using translate3d but with 'vh' instead of 'px', so I'd make a variable for the unit.

**Comment by alvarotrigo** [comment]
> The point being, give the tools for the developer to develop using your plugin. Don't limit the developer, give them options to decide how they'd want to use the functionality you've written?

Yep, that'd be nice. I'll keep it in mind as a possible enhancement for the future.
I don't have time for it now and I still have other high priority issues or bugs to solve for the next release. 

Feel free to commit a pull request if you think you can add the option into the plugin.

**Comment by Quaked** [comment]
Understood.

I would like to know how I can extend it though, as a module. Overwriting said functions "outside" the scope of the plugin. How can I do that? 

Can I access e.g. `var WRAPPER = 'myWrapperClass'` outside the plugin and redefine it?

Also, can I replace functions, such as the scrollPage function outside the plugin? Something like `$.fn.fullpage.scrollPage = function( stuff ) { more stuff; }`?

**Comment by alvarotrigo** [comment]
@Quaked there's no way to do it at the moment. fullpage.js would need to be modified to support that.

**Comment by Quaked** [comment]
Any updates on supporting optional 100vh/vw transition? Or being able to extend fullPage.js?

**Comment by alvarotrigo** [comment]
Not really.
