### ISSUE TITLE
Can't scroll with Youtube in iframe?

### ISSUE THREAD

**Issue by resting** [alvarotrigo/fullPage.js#887]
FullPage.js works nicely for all sections except for the one embedded with Youtube in an iFrame.
I suspect the scroll event is not captured cause the page doesn't scroll when the mouse is over the video.
Moving the mouse off the video scrolls properly again.

I've tried to disable auto scroll in that section, but it didn't help.

Any idea how to overcome this?
This problem exists in latest FF (mac), Safari (mac) and IE 11.

**Comment by Easter1021** [comment]
@resting My solution is "make a mask on the iframe"

**Comment by rredfearn32** [comment]
I'm going down the iframe-mask route too. The only problem is that it prevents hovering over the iframe, which makes showing the YouTube controls quite tricky. Of course, I could make them always display, but that can sometimes obscure the video. Hey ho...

**Comment by maddumajohnerick** [comment]
But masking the iframes cancels its mouse event. Also having trouble with it on embedded pens from codepen. Once I reached the section where my pens are, the swipe events aren't working anymore

**Comment by infloent** [comment]
Hey Everyone!

I had the same problem.. all the navigation controls(space, arrows, scroll) were not working when hovering over an youtube iframe. This is caused because cross-domain iframe don't bubble up the events, so this will happen with any other cross-domain iframe.

My solution for this was to set with css "pointer-event: none;" on the youtube iframe, same effect as with a mask but simpler.

But this will disable the video controls. I was lucky cause I was already using a video plugin for custom style controls. Another way could be to use the youtube iframe API to create your own youtube controls.
