### ISSUE TITLE
IE11 Windows 8.1 Touchscreen- bug with mouse movement and scrolling back

### ISSUE THREAD

**Issue by igorlebedev** [alvarotrigo/fullPage.js#937]
On ie11 with windows 8.1 old bug with mouse movement exist (moving pointer - scrolling back or forward). I'm using fullPage.js v2.5.2. My pc is lenovo yoga 13 it has touchscreen and x64 windows 8.1, if it is matters. On laptop without touchscreen and on Windows7 with ie11 - everything works fine.

**Comment by neo125874** [comment]
I'm sorry to bother you, is that possible or how to use javascript to distinguish the device,
triggered the movement by touchscreen or by touchpad or by mouse?
could you share the key word or the method? Thanks.

**Comment by alvarotrigo** [comment]
@neo125874 I haven't work on it yet, but I would recommend to use stackoverflow.com for that kind of questions.

**Comment by alvarotrigo** [comment]
It doesn't seem to be a proper solution:
http://stackoverflow.com/questions/7838680/detecting-that-the-browser-has-no-mouse-and-is-touch-only

[Discussion on Modernizr](https://github.com/Modernizr/Modernizr/issues/869#issuecomment-15264101)

**Comment by alvarotrigo** [comment]
@neo125874 @igorlebedev  If anybody is really interested to solve it somehow, [contact me](http://alvarotrigo.com/#contact-page).

**Comment by alvarotrigo** [comment]
@neo125874 @igorlebedev  If anybody is really interested in getting a solution for it somehow as soon as possible, [contact me](http://alvarotrigo.com/#contact-page).

**Comment by neo125874** [comment]
What could I do for you?

**Comment by plaidduckdesign** [comment]
I'm interested in this as well. Everything looked great across the board browser-wise until I just loaded IE11 on Win 8.1 with a touchscreen. The slightest mouse movement triggers a scroll event. I'll try increasing the delay but am a little panicked at the moment to say the least.

**Comment by alvarotrigo** [comment]
@plaidduckdesign as I said previously. If anyone really needs this to be solved, [contact me](http://alvarotrigo.com/#contact-page).

**Comment by ajgagnon** [comment]
Is there a way to turn off touch scrolling via a public function or method? That way I can use my own detection methods for ie and turn it off accordingly.

**Comment by alvarotrigo** [comment]
@ajgagnon you won't be able to know if the user is using IE in a touch screen or not. As touch screen computers can use mouse, or touch and change between them whenever the user wants.

**Comment by ajgagnon** [comment]
Good call. Since I needed to figure out a solution, I created a temporary workaround that's a not ideal, but it does temporarily fix the issue.

Since the bug only affects ie11, I used the `pointermove` event: http://caniuse.com/#search=pointermove

I added this to the afterRender callback:

``` javascript
document.addEventListener("pointermove",handleMove,false);
function handleMove(evt) {
	if(evt.pointerType == "mouse") {
		$(document).off('pointerdown');
		$(document).off('pointermove');
	}
	document.removeEventListener("pointermove",handleMove,false);
}
```

and this to the afterResize callback:

``` javascript
document.addEventListener("pointermove",handleMove,false);
function handleMove(evt) {
	if(evt.pointerType == "mouse") {
		setTimeout(function(){
			$(document).off('pointerdown');
			$(document).off('pointermove');
		}, 1);
	}
	document.removeEventListener("pointermove",handleMove,false);
}
```

The only caveat I can think of is once a user starts using a mouse on the page, touch will no longer work. You could also combine this with ie11 browser detection to make sure it only affects the issue.

Again, super hacky, and not ideal solution, but for me it's better than the current bug in ie11.

**Comment by plaidduckdesign** [comment]
Interesting hack but helped me in a different situation just now so cheers
for that.

My IE issue turned out to be a tiny syntax error that screwed everything
up. The biggest issue I have with IE and touch at the moment is somewhere,
some exception is thrown which causes the script to navigate slides or
sections with the most subtle of touch. Adjusting thresholds has no effect.
But double clicking with the mouse or interacting with the site on another
way seems to fix it. Its the strangest thing.

I will contact you to see what assistance I can be just haven't had a
chance yet.

**Comment by tripletto** [comment]
I would love to see this fixed as well. If you have trouble to reproduce the bug, you can use the jquery/PEP and chrome. I installed it in my local copy of your demo-page and now the pages behaves exactly like it does in IE11 in google chrome (of course not in firefox... this would be way to easy, wouldn't it?). It seems that PEP integrates very well in chrome  ;).

```
if(window.PointerEvent){
     pointer = { down: "pointerdown", move: "pointermove"};
}
```

For your convenience, I added my version which was compiled on 13.02.2015
http://www.justbeamit.com/3m4nc

**Comment by alvarotrigo** [comment]
Solved now in version 2.5.7!

**Comment by berlinercode** [comment]
nice!

**Comment by alvarotrigo** [comment]
Can you guys confirm if it works on IE 11 by using touch actions?
I know it works well now with the mouse, but I got someone telling me it doesn't scroll when using fingers on a touch screen computer.

**Comment by edlefebvre** [comment]
Hi Álvaro,I don't have acced to the right device to test this (it was a complaint from a client). It seems that there is no such problem though.

**Comment by ryanbuiltthat** [comment]
On Win8.1 with IE11 the touchscreen works, and it scrolls however...

On my page I have a simple down arrow. Each arrow called the function to move one slide down. I have fitToSection = true (sorry if that's not the exact name ) but IE is ignoring that. It's not stopping at the top of the section nor is it moving back to the top of the section when the touchevent is over.

Another thing I noticed, let's say I do a small flick down on the screen. It'll scroll many sections down. Each section has a down navigation arrow. If I click the button on the active slide, after the flick or scroll down, it'll target the next slide from where I started the scroll. Not where I landed.

**Comment by alvarotrigo** [comment]
@ryanbuiltthat you are naming many problems. 
You have to specify if those only happens when you use the touch events on the screen or if they happen as well when you scroll with the mouse wheel or the trackpad. 

In case they take place with the mouse/trackpad, then could you provide a link to reproduce the problem?

**Comment by ryanbuiltthat** [comment]
Apologies for that. I've been neck deep in this library for many days now
and haven't noticed any mouse issues but I recently changed configurations
and haven't retested in IE yet. I can do that tomorrow.
