### ISSUE TITLE
Safari - complete disaster

### ISSUE THREAD

**Issue by Nikolaus91** [alvarotrigo/fullPage.js#946]
The page works well only for fullHD res now. 

It is based on fullPage.js and Foundation 5. On the following browsers everything works fine:

1. Firefox
2.Opera
3. Chrome
4. IE 11

but for latest safari it look like total disaster. Do you have a clue what it can be?

Please help. http://pr.ilee.iq.pl

**Comment by alvarotrigo** [comment]
I see fullPage.js working properly in Safari 8. You can also test it in browserstack.com.
I believe you have some caching problem.

**Comment by alvarotrigo** [comment]
Safari dropped windows support time ago [with version 6](http://www.ghacks.net/2012/07/28/safari-for-windows-discontinued/).
Safari for Mac is available in version 8, as you can see, a big difference.

[It seems](http://stackoverflow.com/questions/10555514/why-does-html5-video-not-work-in-the-new-windows-version-of-safari) as well that in order to support html5 videos you need to have quicktime installed.

I'd recommend you to disable video for Safari in Windows and change it for an image.
